<template>
  <!--
    Layout is owned by the scoped CSS below (NOT MpFlex utility props) on purpose.
    MpFlex lays out via Pixel's atomic utility classes (.mp-d_flex, …) generated by
    @mekari/pixel3-postcss. In dev those generated rules can go stale after heavy HMR
    and drop out, collapsing this always-visible shell to display:block. Scoped styles
    are unlayered (beat Pixel's @layer rules) and compiled per-component (not via Panda
    extraction), so the header stays laid out regardless. We still use MpFlex/MpAvatar/
    MpText for tokens + typography — only the structural layout is ours.
  -->
  <MpFlex as="header" class="erp-header" backgroundColor="background.header">
    <!-- Left: Logo (+ warehouse switcher when assigned >1 warehouse) -->
    <MpFlex class="erp-header__left">
      <img :src="logoSrc" :alt="logoAlt" class="erp-header__logo" />
      <ErpWarehouseSwitcher v-if="hasWarehouseContext" />
    </MpFlex>

    <!-- Center: Search — hidden on Home, where the hero already has a search box -->
    <MpFlex class="erp-header__center">
      <QuickSearch v-if="currentPageKey !== 'Home'" />
    </MpFlex>

    <!-- Right: Actions + User -->
    <MpFlex class="erp-header__right">
      <MpFlex class="erp-header__actions">
        <!-- Quick-create (+) and the monitor/display shortcut are ERP-only -->
        <ErpQuickCreateMenu v-if="!isWms" />
        <IconButton icon="help" />
        <IconButton v-if="!isWms" icon="desktop" />
        <IconButton icon="notification" />
      </MpFlex>

      <!-- User snapshot menu (avatar + name → account popover) -->
      <ErpUserMenu />
    </MpFlex>
  </MpFlex>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { MpFlex } from "@mekari/pixel3";
import erpLogo from "~/assets/images/mekari-erp-logo.svg?url";
import wmsLogo from "~/assets/images/mekari-wms-logo.svg?url";

// Swap the brand lockup to the WMS logo whenever a WMS scenario is active.
const { activeScenario } = useScenario();
const isWms = computed(() => activeScenario.value.startsWith("WMS"));
const logoSrc = computed(() => (isWms.value ? wmsLogo : erpLogo));
const logoAlt = computed(() => (isWms.value ? "Mekari WMS" : "Mekari ERP"));

// Warehouse label next to the logo whenever the user is scoped to a warehouse
// (Ops). Static for one warehouse (Ops 1), switchable for several (Ops 2).
const { hasWarehouseContext } = useWarehouseContext();

// Home has its own hero search — drop the header search there to avoid redundancy.
const { currentPageKey } = useNavigation();
</script>

<style scoped>
.erp-header {
  display: flex;
  align-items: center;
  gap: var(--mp-spacing-2); /* 8px */
  height: 56px;
  padding-left: var(--mp-spacing-4); /* 16px */
  padding-right: var(--mp-spacing-3); /* 12px */
  background-color: var(--mp-colors-background-header); /* #142D26 */
  z-index: var(--mp-z-indices-sticky, 1100);
}

.erp-header__left {
  display: flex;
  align-items: center;
  gap: var(--mp-spacing-2);
  flex: 1;
}

.erp-header__logo {
  height: var(--mp-spacing-5); /* 20px */
  width: auto;
  /* Defeat the global `img { max-width: 100% }` reset: when the header row
     gets tight (narrow viewport, search column claiming width), that cap
     collapses the logo's width toward 0 while its height stays 20px —
     squishing it. flex-shrink: 0 keeps it from shrinking as a flex item;
     object-fit: contain guarantees the aspect ratio even if constrained. */
  max-width: none;
  object-fit: contain;
  display: block;
  flex-shrink: 0;
}

.erp-header__center {
  display: flex;
  flex: 1;
  width: 100%;
}

.erp-header__right {
  display: flex;
  align-items: center;
  gap: var(--mp-spacing-2);
  flex: 1;
  justify-content: flex-end;
}

.erp-header__actions {
  display: none;
  align-items: center;
  gap: var(--mp-spacing-1); /* 4px */
}

/* md ≥ 768px — show quick-action icons, fix search to 280px */
@media (min-width: 768px) {
  .erp-header__center {
    flex: 0 0 280px;
    width: 280px;
  }
  .erp-header__actions {
    display: flex;
  }
}

/* lg ≥ 992px — widen search to 400px (user name/company handled in ErpUserMenu) */
@media (min-width: 992px) {
  .erp-header__center {
    flex: 0 0 400px;
    width: 400px;
  }
}
</style>
