<script setup lang="ts">
/**
 * NumberFormatSettingsModal — reusable "auto-numbering format" settings modal
 * (Figma Master Pages 1975-13507 → 2307-11897). Opened from a settings gear next
 * to any auto-generated code field (transaction no., account code, invoice no., …).
 *
 * Default view: "<caption>" + "Next number: <nextNumber>" + a full-width
 * "Customize format" button. Clicking it swaps the SAME modal to the customize
 * view — a Number format radio group (Auto / Select existing format / Create new
 * format) with a Save changes footer.
 *
 * Context is parameterised so the exact same component reads as "Transaction no.
 * settings", "Account code settings", etc.:
 *   <NumberFormatSettingsModal
 *     v-model:open="open"
 *     :title="t('Account code settings')"
 *     :caption="t('Account codes are auto-generated by the system.')"
 *     :next-number="10009"
 *     :existing-formats="[{ label: '1-[Auto]', value: '1-[Auto]' }]"
 *     @save="onSave" />
 */
import { ref, computed, watch } from 'vue'
import {
  MpModal, MpModalContent, MpModalHeader, MpModalBody, MpModalFooter,
  MpModalOverlay, MpModalCloseButton, MpRadio, MpAutocomplete, MpInput, MpButton,
} from '@mekari/pixel3'

export interface NumberFormatConfig {
  mode: 'auto' | 'existing' | 'new'
  existingFormat?: string
  prefix?: string
  suffix?: string
  startFrom?: string
}

const props = withDefaults(defineProps<{
  open: boolean
  /** Modal heading, e.g. "Transaction no. settings" / "Account code settings". */
  title: string
  /** One-liner under the heading in the default view. */
  caption?: string
  /** The next auto number — shown for "Auto" and substituted for `[Auto]` in previews. */
  nextNumber: string | number
  /** Existing saved formats for the "Select existing format" dropdown. `[Auto]` is
   *  the placeholder replaced by `nextNumber` in the preview. */
  existingFormats?: { label: string; value: string }[]
}>(), {
  caption: 'Numbers are auto-generated by the system.',
  existingFormats: () => [
    { label: 'TRX/[Auto]/JKT', value: 'TRX/[Auto]/JKT' },
    { label: '[Auto]', value: '[Auto]' },
    { label: 'INV/[Auto]', value: 'INV/[Auto]' },
    { label: 'CASH/[Auto]/HO', value: 'CASH/[Auto]/HO' },
  ],
})
const emit = defineEmits<{ 'update:open': [boolean]; save: [NumberFormatConfig] }>()

const { t } = useLocale()

const customizing = ref(false)
const mode = ref<'auto' | 'existing' | 'new'>('auto')
const existingFormat = ref('')
const prefix = ref('')
const suffix = ref('')
const startFrom = ref('')

// Reset to the default view + defaults every time the modal opens.
watch(() => props.open, (o) => {
  if (!o) return
  customizing.value = false
  mode.value = 'auto'
  existingFormat.value = props.existingFormats[0]?.value ?? ''
  prefix.value = ''
  suffix.value = ''
  startFrom.value = ''
})

const existingPreview = computed(() => existingFormat.value.replace('[Auto]', String(props.nextNumber)))

function close() { emit('update:open', false) }
function save() {
  emit('save', {
    mode: mode.value,
    existingFormat: existingFormat.value,
    prefix: prefix.value,
    suffix: suffix.value,
    startFrom: startFrom.value,
  })
  close()
}
</script>

<template>
  <MpModal :is-close-on-esc="false" :is-close-on-overlay-click="false"
    :id="`nf-modal`"
    :is-open="open"
    size="md"
    :is-keep-alive="false"
    @close="close"
  >
    <MpModalContent>
      <MpModalHeader>
        {{ title }}
        <MpModalCloseButton />
      </MpModalHeader>

      <!-- Default view -->
      <MpModalBody v-if="!customizing">
        <p class="nf-caption">{{ caption }}</p>
        <p class="nf-next">{{ t('Next number') }}: {{ nextNumber }}</p>
        <MpButton class="btn-enterprise btn-enterprise--secondary nf-customize-btn" @click="customizing = true">
          {{ t('Customize format') }}
        </MpButton>
      </MpModalBody>

      <!-- Customize view -->
      <MpModalBody v-else>
        <p class="nf-section">{{ t('Number format') }}</p>
        <div class="nf-radio-group">
          <!-- Auto -->
          <label class="nf-radio">
            <MpRadio id="nf-auto" name="nf-mode" value="auto" :is-checked="mode === 'auto'" @change="mode = 'auto'" />
            <span>{{ t('Auto') }}</span>
          </label>
          <p v-if="mode === 'auto'" class="nf-preview nf-indent">{{ t('Next number') }}: <strong>{{ nextNumber }}</strong></p>

          <!-- Select existing format -->
          <label class="nf-radio">
            <MpRadio id="nf-existing" name="nf-mode" value="existing" :is-checked="mode === 'existing'" @change="mode = 'existing'" />
            <span>{{ t('Select existing format') }}</span>
          </label>
          <div v-if="mode === 'existing'" class="nf-indent nf-existing">
            <MpAutocomplete
              id="nf-existing-ac" v-model="existingFormat" :data="existingFormats"
              label-prop="label" value-prop="value" use-portal is-full-width
            />
            <p class="nf-preview">{{ t('Next number') }}: <strong>{{ existingPreview }}</strong></p>
          </div>

          <!-- Create new format -->
          <label class="nf-radio">
            <MpRadio id="nf-new" name="nf-mode" value="new" :is-checked="mode === 'new'" @change="mode = 'new'" />
            <span>{{ t('Create new format') }}</span>
          </label>
          <div v-if="mode === 'new'" class="nf-indent nf-new">
            <div class="nf-new-grid">
              <label class="nf-mini-label">{{ t('Prefix') }}</label>
              <span aria-hidden="true" />
              <label class="nf-mini-label">{{ t('Suffix') }}</label>
              <MpInput id="nf-prefix" v-model="prefix" :placeholder="t('Ex: TRX/')" />
              <MpInput id="nf-number" :is-disabled="true" :placeholder="t('[Number]')" />
              <MpInput id="nf-suffix" v-model="suffix" :placeholder="t('Ex: /XV')" />
            </div>
            <div class="nf-start">
              <label class="nf-mini-label">{{ t('Start ascending from') }}</label>
              <MpInput id="nf-start" v-model="startFrom" :placeholder="t('Ex: 10001')" />
            </div>
            <p class="nf-hint">{{ t('Transaction number will increase automatically') }}</p>
          </div>
        </div>
      </MpModalBody>

      <MpModalFooter v-if="customizing">
        <div class="nf-footer-btns">
          <MpButton class="btn-enterprise btn-enterprise--ghost" @click="close">{{ t('Cancel') }}</MpButton>
          <MpButton class="btn-enterprise btn-enterprise--primary" @click="save">{{ t('Save changes') }}</MpButton>
        </div>
      </MpModalFooter>
    </MpModalContent>
    <MpModalOverlay />
  </MpModal>
</template>

<style scoped>
.nf-footer-btns { display: flex; justify-content: flex-end; gap: var(--mp-spacing-2); width: 100%; }

.nf-caption { margin: 0; font-size: var(--mp-font-sizes-md); color: var(--mp-text-secondary); }
.nf-next { margin: var(--mp-spacing-1) 0 var(--mp-spacing-4); font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); }
.nf-customize-btn { width: 100%; justify-content: center; }

.nf-section { margin: 0 0 var(--mp-spacing-3); font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.nf-radio-group { display: flex; flex-direction: column; gap: var(--mp-spacing-3); }
/* gap:0 — MpRadio renders its own 12px control-to-label gap (see docs/patterns/Form.md). */
.nf-radio { display: inline-flex; align-items: center; gap: 0; cursor: pointer; font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); width: fit-content; }
/* Content revealed under a radio lines up with the radio LABEL text (control 16px + 12px gap). */
.nf-indent { margin-left: calc(var(--mp-sizes-4, 16px) + var(--mp-spacing-3)); }
.nf-preview { margin: 0; font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); }
.nf-existing { display: flex; flex-direction: column; gap: var(--mp-spacing-2); }

.nf-new { display: flex; flex-direction: column; gap: var(--mp-spacing-3); }
.nf-new-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: var(--mp-spacing-1) var(--mp-spacing-3); align-items: center; }
.nf-mini-label { font-size: var(--mp-font-sizes-sm); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.nf-start { display: flex; flex-direction: column; gap: var(--mp-spacing-1); }
.nf-hint { margin: 0; font-size: 12px; line-height: 16px; color: var(--mp-text-secondary); }
</style>
