import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { OutgoingOrder } from '~/data/outgoing'
import { shippingLabelInfo, type ShipLabelInfo } from '~/data/shippingLabels'
import { orderSkuLines } from '~/data/inventory'

export interface ShippingLabelEntry { order: OutgoingOrder; info: ShipLabelInfo }

function toEntries(input: Array<ShippingLabelEntry | OutgoingOrder>): ShippingLabelEntry[] {
  return input.map((x) => ('order' in x ? x : { order: x, info: shippingLabelInfo(x) }))
}
function channelOf(source: string): string {
  const i = source.indexOf(':')
  return i >= 0 ? source.slice(0, i).trim() : source
}

/**
 * Shipping label, one per page (bulk = multi-page). Two shapes:
 *
 *  - Marketplace (source label): we don't design it — the real label comes from
 *    the marketplace channel. Render a simple PLACEHOLDER page saying so.
 *  - Non-marketplace (WMS label): a plain internal label — the order's products
 *    with SKU and qty, nothing more.
 */
export async function generateShippingLabelPdf(
  input: Array<ShippingLabelEntry | OutgoingOrder>,
): Promise<jsPDF> {
  const entries = toEntries(input)
  const doc = new jsPDF({ unit: 'mm', format: 'a5', orientation: 'portrait' })
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const M = 12

  entries.forEach(({ order, info }, i) => {
    if (i > 0) doc.addPage()

    if (info.kind === 'source') {
      // Marketplace → placeholder only (the channel provides the real label).
      doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.setTextColor(0)
      doc.text('Shipping label placeholder', W / 2, H / 2 - 14, { align: 'center' })
      doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(90)
      doc.text(`Provided by the marketplace (${channelOf(order.source)}).`, W / 2, H / 2 - 6, { align: 'center' })
      doc.text('Not generated by WMS — print from the marketplace channel.', W / 2, H / 2, { align: 'center' })
      doc.setTextColor(0); doc.setFontSize(9)
      doc.text(`Order no.: ${order.number}`, W / 2, H / 2 + 10, { align: 'center' })
      if (info.code) doc.text(`Resi: ${info.code}`, W / 2, H / 2 + 16, { align: 'center' })
      return
    }

    // Non-marketplace (WMS) → plain label: header + product / SKU / qty table.
    let y = M
    doc.setFont('helvetica', 'bold'); doc.setFontSize(14); doc.text('Shipping label', M, y); y += 8
    doc.setFont('helvetica', 'normal'); doc.setFontSize(9)
    doc.text(`Order no.: ${order.number}`, M, y); y += 5
    doc.text(`Customer: ${order.customer ?? '—'}`, M, y); y += 5
    doc.text(`Warehouse: ${order.warehouseName}`, M, y); y += 6

    const lines = orderSkuLines(order)
    const totalQty = lines.reduce((s, l) => s + l.qty, 0)
    autoTable(doc, {
      startY: y,
      margin: { left: M, right: M },
      head: [['#', 'Product', 'SKU', 'Qty']],
      body: lines.map((l, idx) => [String(idx + 1), l.product.name, l.sku, String(l.qty)]),
      styles: { fontSize: 9, cellPadding: 2 },
      headStyles: { fillColor: [240, 241, 243], textColor: 40, fontStyle: 'bold' },
      columnStyles: { 0: { cellWidth: 10 }, 3: { cellWidth: 16, halign: 'right' } },
    })
    const endY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y
    doc.setFont('helvetica', 'bold'); doc.setFontSize(10)
    doc.text(`Total qty: ${totalQty}`, W - M, endY + 7, { align: 'right' })
  })

  return doc
}
