import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { OutgoingOrder } from '~/data/outgoing'
import { shippingLabelInfo, type ShipLabelInfo } from '~/data/shippingLabels'
import { orderSkuLines } from '~/data/inventory'
import { formatDateTimeLong } from './date'
import { loadImagesByUrl } from './pdfImage'

export interface ShippingLabelEntry { order: OutgoingOrder; info: ShipLabelInfo }

const PHOTO_COL_WIDTH = 48
const PHOTO_SIZE = 38
const PHOTO_ROW_HEIGHT = 46

function toEntries(input: Array<ShippingLabelEntry | OutgoingOrder>): ShippingLabelEntry[] {
  return input.map((x) => ('order' in x ? x : { order: x, info: shippingLabelInfo(x) }))
}
function channelOf(source: string): string {
  const i = source.indexOf(':')
  return i >= 0 ? source.slice(0, i).trim() : source
}

/**
 * Shipping label, one order per page (bulk = multi-page). Same document layout
 * as the picking/packing lists (title, rule, info block, grid table, totals) so
 * the three read as one family. Two shapes:
 *
 *  - Marketplace (source label): we don't design it — the real label comes from
 *    the marketplace channel. Render a PLACEHOLDER note (same header, no table).
 *  - Non-marketplace (WMS label): a plain internal label — the order's products
 *    with SKU and qty, in the same grid table as the packing list.
 */
export async function generateShippingLabelPdf(
  input: Array<ShippingLabelEntry | OutgoingOrder>,
): Promise<jsPDF> {
  const entries = toEntries(input)
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const marginX = 40

  for (let i = 0; i < entries.length; i++) {
    const { order, info } = entries[i]!
    if (i > 0) doc.addPage()

    let y = 44
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(18)
    doc.text('SHIPPING LABEL', marginX, y)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    doc.text(order.number, pageWidth - marginX, y, { align: 'right' })

    y += 16
    doc.setDrawColor(200)
    doc.setLineWidth(0.75)
    doc.line(marginX, y, pageWidth - marginX, y)
    y += 22

    const leftInfo: [string, string][] = [
      ['Sales order', order.salesNo || '-'],
      ['Customer', order.customer || '-'],
      ['Warehouse', order.warehouseName || '-'],
    ]
    if (info.code) leftInfo.push([info.kind === 'source' ? 'Resi' : 'Tracking no.', info.code])
    const rightInfo: [string, string][] = [
      ['Printed on', formatDateTimeLong(new Date().toISOString())],
    ]

    doc.setFontSize(10)
    const rightX = pageWidth / 2 + 20
    let ly = y
    for (const [label, value] of leftInfo) {
      doc.setFont('helvetica', 'bold'); doc.text(`${label}:`, marginX, ly)
      doc.setFont('helvetica', 'normal'); doc.text(value, marginX + 92, ly)
      ly += 16
    }
    let ry = y
    for (const [label, value] of rightInfo) {
      doc.setFont('helvetica', 'bold'); doc.text(`${label}:`, rightX, ry)
      doc.setFont('helvetica', 'normal'); doc.text(value, rightX + 92, ry)
      ry += 16
    }
    y = Math.max(ly, ry) + 12

    if (info.kind === 'source') {
      // Marketplace → placeholder note (the channel provides the real label).
      doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(0)
      doc.text('Shipping label placeholder', marginX, y + 8)
      doc.setFont('helvetica', 'normal'); doc.setFontSize(10); doc.setTextColor(90)
      doc.text(`Provided by the marketplace (${channelOf(order.source)}).`, marginX, y + 26)
      doc.text('Not generated by WMS — print from the marketplace channel.', marginX, y + 42)
      doc.setTextColor(0)
      continue
    }

    // Non-marketplace (WMS) → same grid table as the packing list.
    const lines = orderSkuLines(order)
    const totalQty = lines.reduce((s, l) => s + l.qty, 0)
    const imagesByUrl = await loadImagesByUrl(lines.map((l) => l.product.img))
    autoTable(doc, {
      startY: y,
      theme: 'grid',
      head: [['No.', 'Photo', 'SKU', 'Product', 'Qty', 'Unit']],
      body: lines.map((l, idx) => [idx + 1, '', l.sku, l.product.name, l.qty, l.product.unit]),
      styles: { fontSize: 9, cellPadding: 5, lineColor: [220, 220, 220], lineWidth: 0.5 },
      headStyles: { fillColor: [235, 235, 235], textColor: 20, fontStyle: 'bold' },
      columnStyles: {
        0: { cellWidth: 28, halign: 'center' },
        1: { cellWidth: PHOTO_COL_WIDTH, minCellHeight: PHOTO_ROW_HEIGHT },
        2: { cellWidth: 60 },
        4: { cellWidth: 60, halign: 'right' },
        5: { cellWidth: 50 },
      },
      margin: { left: marginX, right: marginX },
      didDrawCell: (data) => {
        if (data.section !== 'body' || data.column.index !== 1) return
        const loaded = imagesByUrl.get(lines[data.row.index]?.product.img ?? '')
        if (!loaded) return
        const px = data.cell.x + (data.cell.width - PHOTO_SIZE) / 2
        const py = data.cell.y + (data.cell.height - PHOTO_SIZE) / 2
        doc.addImage(loaded.dataUrl, loaded.format, px, py, PHOTO_SIZE, PHOTO_SIZE)
      },
    })

    // @ts-expect-error lastAutoTable is attached to the doc instance by the plugin at runtime
    let finalY: number = (doc.lastAutoTable?.finalY ?? y) + 24
    if (finalY + 30 > pageHeight - marginX) { doc.addPage(); finalY = 44 }
    doc.setFontSize(10)
    doc.setFont('helvetica', 'bold')
    doc.text(`Total SKU: ${lines.length}     Total qty: ${totalQty}`, marginX, finalY)
  }

  return doc
}
