import { warehouses } from './warehouses'
import type { Warehouse } from './types'

/** A tracked batch (lot) of a product within a warehouse (Batches tab).
 *  A batch sits in one bin; a batch split across bins is modelled as separate rows. */
export interface ProductBatch {
  batchNo: string
  /** ISO date — used to flag near/expired stock */
  expiryDate: string
  /** storage bin location */
  location: string
  onHand: number
  reserved: number
  available: number
}

/** A single serialized unit — one serial number lives in exactly one bin. */
export interface SerialUnit {
  serial: string
  location: string
}

/** Serial-number tracking for a product (Serial numbers tab). */
export interface ProductSerials {
  available: SerialUnit[]
  reserved: SerialUnit[]
}

/** A single product's stock row within a warehouse (Products tab). */
export interface WarehouseStockItem {
  id: string
  name: string
  /** product photo URL (thumbnail) */
  photo: string
  /** muted subtitle under the name (variant / roast / colour, …) */
  subtitle: string
  sku: string
  barcode: string
  category: string
  onHand: number
  reserved: number
  available: number
  onTheWay: number
  minStock: number
  unit: string
  /** one or more bin locations */
  locations: string[]
  defaultSalesPrice: number
  averageCost: number
  lastPurchaseCost: number
  defaultPurchaseCost: number
  /** batch/lot tracking — only for batch-tracked products (Batches tab) */
  batches?: ProductBatch[]
  /** serial-number tracking — only for serial-tracked products (Serial numbers tab) */
  serials?: ProductSerials
}

export interface WarehouseDetail extends Warehouse {
  description: string
  pic: string
  stock: WarehouseStockItem[]
}

/**
 * Product catalogue template (coffee-shop inventory). The warehouse stock is
 * generated by cycling this pool up to the warehouse's `skuTotal`, so the count
 * shown in the index ("SKU Total") matches the rows in the detail Products tab.
 * Photos live in public/products/ so they load same-origin in the preview.
 */
interface ProductTemplate {
  name: string
  photo: string
  subtitle: string
  category: string
  unit: string
  salesPrice: number
  /** batch-tracked product → appears in the Batches tab */
  batches?: Omit<ProductBatch, never>[]
  /** serial-tracked product → appears in the Serial numbers tab */
  serials?: ProductSerials
}

// Photos available (public/products): ws-1 = retail coffee bag, ws-2 = espresso
// machine, ws-4 = roasted beans, ws-5 = brewed espresso. Every template's photo
// matches what it depicts so the image always relates to the product name.
const PRODUCT_POOL: ProductTemplate[] = [
  // ── Roasted beans, sold loose by the Kg → beans photo ──
  {
    name: 'Arabica Aceh Gayo', photo: '/products/ws-4.jpg',
    subtitle: 'Washed Process, Medium Roast', category: 'Coffee Beans', unit: 'Kg', salesPrice: 280_000,
    batches: [
      { batchNo: 'Batch #00001', expiryDate: '2026-01-05', location: 'L1/ZJA01/R01/SA/B001', onHand: 75, reserved: 0, available: 75 },
      { batchNo: 'Batch #00002', expiryDate: '2026-08-20', location: 'L1/ZJA01/R01/SA/B002', onHand: 25, reserved: 0, available: 25 },
    ],
  },
  {
    name: 'Robusta Lampung Gold', photo: '/products/ws-4.jpg',
    subtitle: 'Natural Process, Dark Roast', category: 'Coffee Beans', unit: 'Kg', salesPrice: 120_000,
    batches: [
      { batchNo: 'Batch #00001', expiryDate: '2026-12-15', location: 'L1/ZJA01/R01/SB/B002', onHand: 1_200, reserved: 200, available: 1_000 },
    ],
  },
  { name: 'Arabica Toraja Sapan', photo: '/products/ws-4.jpg', subtitle: 'Washed Process, Medium Roast', category: 'Coffee Beans', unit: 'Kg', salesPrice: 310_000 },
  { name: 'Arabica Java Preanger', photo: '/products/ws-4.jpg', subtitle: 'Honey Process, Medium-Light Roast', category: 'Coffee Beans', unit: 'Kg', salesPrice: 295_000 },
  { name: 'Sumatra Mandheling', photo: '/products/ws-4.jpg', subtitle: 'Wet-Hulled, Dark Roast', category: 'Coffee Beans', unit: 'Kg', salesPrice: 265_000 },
  { name: 'Arabica Kintamani Bali', photo: '/products/ws-4.jpg', subtitle: 'Natural Process, Medium Roast', category: 'Coffee Beans', unit: 'Kg', salesPrice: 288_000 },
  // ── Retail packs (whole bean / ground bags) → bag photo ──
  { name: 'House Blend 250g', photo: '/products/ws-1.jpg', subtitle: 'Whole Bean, Retail Pack', category: 'Retail Pack', unit: 'Pack', salesPrice: 95_000 },
  { name: 'Signature Espresso 250g', photo: '/products/ws-1.jpg', subtitle: 'Whole Bean, Retail Pack', category: 'Retail Pack', unit: 'Pack', salesPrice: 110_000 },
  { name: 'Decaf Colombia 250g', photo: '/products/ws-1.jpg', subtitle: 'Ground, Retail Pack', category: 'Retail Pack', unit: 'Pack', salesPrice: 105_000 },
  { name: 'Cold Brew Blend 250g', photo: '/products/ws-1.jpg', subtitle: 'Coarse Ground, Retail Pack', category: 'Retail Pack', unit: 'Pack', salesPrice: 98_000 },
  // ── Equipment → espresso-machine photo ──
  {
    name: 'La Marzocco Linea Mini', photo: '/products/ws-2.jpg', subtitle: 'Single Group, Dual Boiler, White', category: 'Machines', unit: 'Unit', salesPrice: 95_000_000,
    serials: {
      available: [
        { serial: 'LM00123', location: 'L1/ZEQ01/R03/SA/B011' },
        { serial: 'LM00122', location: 'L1/ZEQ01/R03/SA/B012' },
        { serial: 'LM00121', location: 'L1/ZEQ01/R03/SA/B013' },
        { serial: 'LM00119', location: 'L1/ZEQ01/R03/SB/B004' },
        { serial: 'LM00118', location: 'L1/ZEQ01/R03/SB/B005' },
        { serial: 'LM00115', location: 'L1/ZEQ01/R04/SA/B001' },
        { serial: 'LM00114', location: 'L1/ZEQ01/R04/SA/B002' },
        { serial: 'LM00110', location: 'L1/ZEQ01/R04/SB/B007' },
        { serial: 'LM00109', location: 'L1/ZEQ01/R04/SB/B008' },
      ],
      reserved: [{ serial: 'LM00120', location: 'L1/ZEQ01/R03/SA/B010' }],
    },
  },
  {
    name: 'Rocket Appartamento', photo: '/products/ws-2.jpg', subtitle: 'Single Group, Heat Exchanger', category: 'Machines', unit: 'Unit', salesPrice: 28_000_000,
    serials: {
      available: [{ serial: 'RA00045', location: 'L1/ZEQ01/R05/SA/B003' }],
      reserved: [{ serial: 'RA00046', location: 'L1/ZEQ01/R05/SA/B004' }],
    },
  },
]

// short, stable bin-location codes derived from the row index
function binLocation(seed: number, i: number): string[] {
  const zone = `Z${String((seed % 9) + 1).padStart(2, '0')}`
  const rack = `R${String((i % 40) + 1).padStart(2, '0')}`
  const shelf = String.fromCharCode(65 + (i % 6))         // A–F
  const bin = `B${String((i % 200) + 1).padStart(3, '0')}`
  return [`L1/${zone}/${rack}/S${shelf}/${bin}`]
}

/** Deterministically build `count` stock items for a warehouse (stable per id). */
function generateStock(count: number, seed: number): WarehouseStockItem[] {
  const out: WarehouseStockItem[] = []
  for (let i = 0; i < count; i++) {
    const tpl = PRODUCT_POOL[i % PRODUCT_POOL.length]
    const cycle = Math.floor(i / PRODUCT_POOL.length) + 1   // 1, 2, 3 … for repeats
    const onHand = ((i * 53 + seed * 7 + 17) % 1500) + 5
    const reserved = onHand > 40 ? (i * 13 + seed) % 40 : 0
    const onTheWay = (i * 7) % 60
    const minStock = ((i * 11) % 200) + 10
    out.push({
      id: `${seed}-p${i}`,
      name: cycle > 1 ? `${tpl.name} #${cycle}` : tpl.name,
      photo: tpl.photo,
      subtitle: tpl.subtitle,
      sku: `SKU-${String(seed).padStart(2, '0')}${String(10_000 + i)}`,
      barcode: String(8_991_000_000_000 + seed * 100_000 + i),
      category: tpl.category,
      onHand,
      reserved,
      available: onHand - reserved,
      onTheWay,
      minStock,
      unit: tpl.unit,
      locations: binLocation(seed, i),
      defaultSalesPrice: tpl.salesPrice,
      averageCost: Math.round(tpl.salesPrice * 0.6),
      lastPurchaseCost: Math.round(tpl.salesPrice * 0.62),
      defaultPurchaseCost: Math.round(tpl.salesPrice * 0.58),
      // attach batches/serials only on the first occurrence of a tracked product,
      // so the Batches / Serial numbers tabs stay small, design-matching subsets
      batches: cycle === 1 && tpl.batches ? tpl.batches.map((b) => ({ ...b })) : undefined,
      serials: cycle === 1 && tpl.serials
        ? { available: [...tpl.serials.available], reserved: [...tpl.serials.reserved] }
        : undefined,
    })
  }
  return out
}

/** Per-warehouse description (mock). Falls back to a generic line. */
const descriptions: Record<string, string> = {
  'wh-000': 'Gudang utama',
  'wh-001': 'Gudang utama untuk wilayah Jakarta dan sekitarnya',
  'wh-002': 'Gudang distribusi wilayah Jawa Timur',
  'wh-003': 'Gudang industri kawasan Bandung Selatan',
  'wh-009': 'Gudang fulfillment wilayah Jakarta Timur dan sekitarnya',
  'wh-006': 'Gudang distribusi wilayah Makassar dan Indonesia Timur',
  'wh-010': 'Gudang fulfillment wilayah Makassar Utara dan sekitarnya',
}

// numeric seed from a warehouse id (e.g. 'wh-001' → 1) for stable generation
function seedFromId(id: string): number {
  const n = parseInt(id.replace(/\D/g, ''), 10)
  return Number.isNaN(n) ? 0 : n
}

export function getWarehouseDetail(id: string): WarehouseDetail | undefined {
  const wh = warehouses.find((w) => w.id === id)
  if (!wh) return undefined
  return {
    ...wh,
    description: descriptions[id] ?? '—',
    pic: wh.pics.map((p) => p.name).join(', ') || '—',
    // stock count matches the index "SKU Total" exactly
    stock: generateStock(wh.skuTotal, seedFromId(id)),
  }
}
