<script setup lang="ts">
/**
 * Mekari Cowork — an autonomous AI co-worker surface. Full-screen product (its
 * own dark shell, no ERP chrome). Three states: Home (composer + suggested work),
 * Working (live steps + sources), Completed (grounded briefing).
 *
 * The briefing is generated by Gemini via /api/cowork/plan, grounded on a compact
 * snapshot of the ERP mock DB (HR / CRM / WMS / finance).
 */
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { useCoworkContext } from '~/composables/useCoworkContext'

// Renders inside the standard ERP shell (ErpHeader + ErpSidebar) — the default
// layout. Cowork is a workspace within the ERP, not a separate product surface.

const route = useRoute()
const { build } = useCoworkContext()

type State = 'home' | 'working' | 'completed'
const state = ref<State>('home')

interface Step { title: string; detail: string }
interface Finding { title: string; detail: string }
interface Source { name: string; detail: string }
interface SummaryItem { title: string; detail: string; priority: 'High' | 'Medium' | 'Low' }
interface Plan {
  taskTitle: string
  intro: string
  sources: Source[]
  steps: Step[]
  findings: Finding[]
  metric: string
  summary: SummaryItem[]
  alsoPrepared: { title: string; detail: string }[]
}

const prompt = ref('')
const activeTask = ref('')
const plan = ref<Plan | null>(null)
const planSource = ref<'gemini' | 'fallback' | ''>('')
const errorMsg = ref('')

// Live "what Cowork is doing" progression.
const DEFAULT_STEPS: Step[] = [
  { title: 'Read task context', detail: 'Parsing your request and connected products.' },
  { title: 'Review HR (Talenta)', detail: 'Employees, org, contracts and time-off.' },
  { title: 'Review CRM (Qontak)', detail: 'Customers, open deals and orders.' },
  { title: 'Review WMS & finance', detail: 'Stock levels, receivables and payables.' },
  { title: 'Build briefing', detail: 'Prioritising risks, decisions and actions.' },
]
const liveSteps = ref<Step[]>(DEFAULT_STEPS)
const activeStepIndex = ref(0)
let stepTimer: ReturnType<typeof setInterval> | null = null
const apiDone = ref(false)

const progressPct = computed(() => {
  const total = liveSteps.value.length
  if (!total) return 0
  return Math.min(100, Math.round(((activeStepIndex.value) / total) * 100))
})

const greeting = computed(() => {
  const h = new Date().getHours()
  return h < 12 ? 'Good morning' : h < 18 ? 'Good afternoon' : 'Good evening'
})
const todayLabel = computed(() =>
  new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' }),
)

// Suggested work — grounded prompts tuned to what the mock ERP surfaces.
const suggested = [
  { title: 'Prepare my Monday briefing', badge: 'Needs prep', tone: 'needs',
    sub: 'Cross-check HR, CRM, WMS and finance for what needs attention this week.',
    task: 'Prepare my Monday morning briefing. Review HR, CRM, WMS and finance across the ERP and tell me the top things that need my attention this week.' },
  { title: 'Chase overdue receivables', badge: 'Attention', tone: 'needs',
    sub: 'Find overdue invoices and draft reminders for the biggest ones.',
    task: 'Review overdue receivables in finance, identify the largest overdue invoices, and draft payment reminders. Tell me who to chase first.' },
  { title: 'Reorder low-stock SKUs', badge: 'Attention', tone: 'needs',
    sub: 'Check WMS stock against reorder points and propose a purchase plan.',
    task: 'Check WMS stock levels against reorder points, list the SKUs that are low or out of stock, and propose a reorder plan before they block open sales orders.' },
  { title: 'Review the sales pipeline', badge: 'Review', tone: 'working',
    sub: 'Surface stalled deals and the highest-value customers to prioritise.',
    task: 'Review the Qontak sales pipeline and top customers. Surface the open deals worth prioritising and any stalled ones, and suggest next steps.' },
]

const recent = [
  { title: 'Month-end close checklist', sub: 'Reconciled 3 accounts and flagged 2 unmatched statement lines.' },
  { title: 'Headcount & contracts review', sub: 'Found 2 contracts expiring within 60 days across the org.' },
]

function assignTask(task: string) {
  const t = task.trim()
  if (!t) return
  activeTask.value = t
  prompt.value = t
  plan.value = null
  errorMsg.value = ''
  apiDone.value = false
  liveSteps.value = DEFAULT_STEPS
  activeStepIndex.value = 0
  state.value = 'working'
  startSteps()
  fetchPlan(t)
}

function startSteps() {
  if (stepTimer) clearInterval(stepTimer)
  stepTimer = setInterval(() => {
    if (activeStepIndex.value < liveSteps.value.length) {
      activeStepIndex.value += 1
    }
    maybeComplete()
  }, 1500)
}

async function fetchPlan(task: string) {
  try {
    const res = await $fetch<{ plan: Plan; source: 'gemini' | 'fallback' }>('/api/cowork/plan', {
      method: 'POST',
      body: { task, context: build() },
    })
    plan.value = res.plan
    planSource.value = res.source
    // Swap in the model's real step list (keeps the same reveal position).
    if (res.plan?.steps?.length) {
      liveSteps.value = res.plan.steps
      if (activeStepIndex.value > res.plan.steps.length) activeStepIndex.value = res.plan.steps.length
    }
  } catch (err: any) {
    errorMsg.value = 'Cowork could not reach the model. Showing a grounded summary instead.'
  } finally {
    apiDone.value = true
    maybeComplete()
  }
}

// Advance to the briefing only once the steps have finished revealing AND the
// plan has arrived — so the "work" reads as real, never truncated.
function maybeComplete() {
  if (apiDone.value && plan.value && activeStepIndex.value >= liveSteps.value.length) {
    if (stepTimer) { clearInterval(stepTimer); stepTimer = null }
    setTimeout(() => { state.value = 'completed' }, 700)
  }
}

function reset() {
  if (stepTimer) { clearInterval(stepTimer); stepTimer = null }
  state.value = 'home'
  plan.value = null
  activeTask.value = ''
  prompt.value = ''
}

onMounted(() => {
  // Entry from the header search "Cowork" mode: /cowork?task=...&run=1
  const q = route.query
  if (typeof q.task === 'string' && q.task.trim()) {
    prompt.value = q.task
    if (q.run === '1') assignTask(q.task)
  }
})
onBeforeUnmount(() => { if (stepTimer) clearInterval(stepTimer) })

function badgeClass(tone: string) { return `cw-badge cw-badge--${tone}` }
function priorityTone(p: string) { return p === 'High' ? 'needs' : p === 'Medium' ? 'working' : 'done' }
</script>

<template>
  <div class="cw-app">
    <main class="cw-main">
      <!-- ── Home ── -->
      <section v-if="state === 'home'" class="cw-view">
        <p class="cw-eyebrow">{{ todayLabel }}</p>
        <h1 class="cw-h1">{{ greeting }}, Rizal.</h1>
        <p class="cw-lede">Tell Cowork what you want to get done across your ERP.</p>

        <div class="cw-composer">
          <textarea
            v-model="prompt"
            class="cw-prompt"
            rows="3"
            placeholder="e.g. Review overdue invoices and draft reminders for the biggest ones…"
            @keydown.meta.enter="assignTask(prompt)"
          />
          <div class="cw-composer__foot">
            <div class="cw-chips">
              <span class="cw-chip">Talenta</span><span class="cw-chip">Qontak</span>
              <span class="cw-chip">WMS</span><span class="cw-chip">Jurnal</span>
            </div>
            <button class="cw-btn cw-btn--primary" type="button" @click="assignTask(prompt)">Assign task</button>
          </div>
        </div>

        <p class="cw-section-title">Suggested work</p>
        <div class="cw-grid">
          <button v-for="s in suggested" :key="s.title" class="cw-card cw-card--click" type="button" @click="assignTask(s.task)">
            <div class="cw-card__top">
              <div>
                <h3 class="cw-card__title">{{ s.title }}</h3>
                <p class="cw-muted">{{ s.sub }}</p>
              </div>
              <span :class="badgeClass(s.tone)">{{ s.badge }}</span>
            </div>
          </button>
        </div>

        <p class="cw-section-title">Recent work</p>
        <div class="cw-grid">
          <div v-for="r in recent" :key="r.title" class="cw-card">
            <div class="cw-card__top">
              <div>
                <h3 class="cw-card__title">{{ r.title }}</h3>
                <p class="cw-muted">{{ r.sub }}</p>
              </div>
              <span class="cw-badge cw-badge--done">Done</span>
            </div>
          </div>
        </div>
      </section>

      <!-- ── Working ── -->
      <section v-else-if="state === 'working'" class="cw-view">
        <p class="cw-eyebrow">Task workspace</p>
        <div class="cw-workspace">
          <div class="cw-panel">
            <div class="cw-panel__head">
              <div class="cw-titlerow">
                <div>
                  <h2 class="cw-panel__title">{{ plan?.taskTitle ?? activeTask }}</h2>
                  <p class="cw-muted">{{ plan?.intro ?? 'Cowork is reviewing your ERP data and identifying what needs your attention.' }}</p>
                </div>
                <span class="cw-badge cw-badge--working">Working</span>
              </div>
              <div class="cw-progress"><div class="cw-progress__fill" :style="{ width: progressPct + '%' }" /></div>
            </div>
            <div class="cw-panel__body">
              <p class="cw-section-title cw-section-title--tight">What Cowork is doing</p>
              <div class="cw-steps">
                <div
                  v-for="(s, i) in liveSteps"
                  :key="s.title + i"
                  class="cw-step"
                  :class="{ 'cw-step--done': i < activeStepIndex, 'cw-step--active': i === activeStepIndex }"
                >
                  <span class="cw-dot">{{ i < activeStepIndex ? '✓' : i + 1 }}</span>
                  <div>
                    <strong class="cw-step__title">{{ s.title }}</strong>
                    <p class="cw-step__detail">{{ s.detail }}</p>
                  </div>
                </div>
              </div>

              <template v-if="plan?.findings?.length">
                <p class="cw-section-title">Findings so far</p>
                <div v-for="f in plan.findings" :key="f.title" class="cw-finding">
                  <strong class="cw-finding__title">{{ f.title }}</strong>
                  <p class="cw-finding__detail">{{ f.detail }}</p>
                </div>
              </template>
            </div>
          </div>

          <div class="cw-panel">
            <div class="cw-panel__head"><strong>Sources being used</strong></div>
            <div class="cw-panel__body">
              <div class="cw-source-list">
                <div v-for="s in (plan?.sources ?? [])" :key="s.name" class="cw-source">
                  <span>{{ s.name }}</span><span class="cw-source__detail">{{ s.detail }}</span>
                </div>
                <div v-if="!plan" class="cw-source cw-source--pending"><span>Gathering sources…</span><span class="cw-spinner" /></div>
              </div>
              <button v-if="plan" class="cw-btn cw-btn--primary cw-btn--block" type="button" @click="state = 'completed'">View briefing</button>
              <button class="cw-btn cw-btn--ghost cw-btn--block" type="button" @click="reset">Cancel</button>
            </div>
          </div>
        </div>
      </section>

      <!-- ── Completed ── -->
      <section v-else class="cw-view">
        <p class="cw-eyebrow">Task completed</p>
        <div class="cw-panel">
          <div class="cw-result-hero">
            <div class="cw-titlerow">
              <div>
                <h2 class="cw-panel__title">{{ plan?.taskTitle }} — ready</h2>
                <p class="cw-muted">{{ plan?.intro }}</p>
              </div>
              <span class="cw-badge cw-badge--done">Completed</span>
            </div>
            <p class="cw-metric">{{ plan?.metric }}</p>
            <p v-if="planSource === 'fallback'" class="cw-note">{{ errorMsg || 'Grounded summary (model offline).' }}</p>
            <div class="cw-actions">
              <button class="cw-btn cw-btn--primary" type="button">Create action items</button>
              <button class="cw-btn cw-btn--secondary" type="button">Share briefing</button>
            </div>
          </div>
          <div class="cw-panel__body">
            <p class="cw-section-title cw-section-title--tight">Executive summary</p>
            <div class="cw-summary">
              <div v-for="(s, i) in (plan?.summary ?? [])" :key="s.title" class="cw-summary__item">
                <div>
                  <strong class="cw-summary__title">{{ i + 1 }}. {{ s.title }}</strong>
                  <p class="cw-muted">{{ s.detail }}</p>
                </div>
                <span :class="badgeClass(priorityTone(s.priority))">{{ s.priority }}</span>
              </div>
            </div>

            <template v-if="plan?.alsoPrepared?.length">
              <p class="cw-section-title">Cowork also prepared</p>
              <div class="cw-grid">
                <div v-for="a in plan.alsoPrepared" :key="a.title" class="cw-card">
                  <h3 class="cw-card__title">{{ a.title }}</h3>
                  <p class="cw-muted">{{ a.detail }}</p>
                </div>
              </div>
            </template>

            <div class="cw-actions cw-actions--foot">
              <button class="cw-btn cw-btn--primary" type="button" @click="reset">Done</button>
              <button class="cw-btn cw-btn--secondary" type="button" @click="assignTask(activeTask)">Run again</button>
            </div>
          </div>
        </div>
      </section>
    </main>
  </div>
</template>

<style scoped>
.cw-app {
  --cw-bg: #f6f7f9; --cw-surface: #fff; --cw-text: #17191c; --cw-muted: #6b7280; --cw-line: #e5e7eb;
  --cw-accent: #0d9488; --cw-accent-soft: #e6f4f0; --cw-green: #137a4a; --cw-green-soft: #eaf7f0;
  --cw-amber: #9a6700; --cw-amber-soft: #fff6dc; --cw-shadow: 0 12px 32px rgba(16,24,40,.07);
  /* Sits inside the ERP content-area (ErpHeader + ErpSidebar around it) and owns
     its own vertical scroll. */
  height: 100%; overflow-y: auto; background: var(--cw-bg); color: var(--cw-text);
  font-family: var(--mp-fonts-body, Inter, sans-serif);
}

/* Main */
.cw-main { padding: 32px 40px 64px; max-width: 1080px; width: 100%; margin: 0 auto; }
.cw-eyebrow { color: var(--cw-muted); font-size: 13px; margin: 0 0 8px; }
.cw-h1 { margin: 0 0 8px; font-size: 34px; line-height: 1.15; letter-spacing: -.03em; }
.cw-lede { color: var(--cw-muted); font-size: 15px; margin: 0 0 28px; }

.cw-composer { background: var(--cw-surface); border: 1px solid var(--cw-line); border-radius: 22px; padding: 16px; box-shadow: var(--cw-shadow); margin-bottom: 32px; }
.cw-prompt { width: 100%; border: none; outline: none; resize: vertical; font-family: inherit; font-size: 17px; line-height: 1.55; color: var(--cw-text); padding: 4px 2px 14px; background: none; }
.cw-prompt::placeholder { color: #9aa1ac; }
.cw-composer__foot { display: flex; justify-content: space-between; align-items: center; border-top: 1px solid var(--cw-line); padding-top: 12px; gap: 12px; }
.cw-chips { display: flex; gap: 8px; flex-wrap: wrap; }
.cw-chip { padding: 7px 10px; background: #f3f4f6; border-radius: 999px; font-size: 12px; color: #4b5563; }

.cw-btn { display: inline-flex; align-items: center; justify-content: center; border-radius: 11px; font-weight: 650; cursor: pointer; font-family: inherit; font-size: 14px; border: 1px solid transparent; }
.cw-btn--primary { background: var(--cw-accent); color: #fff; padding: 11px 16px; }
.cw-btn--primary:hover { background: #0b7d72; }
.cw-btn--secondary { border-color: var(--cw-line); background: #fff; color: var(--cw-text); padding: 10px 14px; }
.cw-btn--secondary:hover { border-color: #c9cbd1; }
.cw-btn--ghost { background: none; color: var(--cw-muted); padding: 10px 14px; }
.cw-btn--ghost:hover { color: var(--cw-text); }
.cw-btn--block { width: 100%; margin-top: 10px; }

.cw-section-title { font-size: 14px; font-weight: 700; margin: 26px 0 12px; }
.cw-section-title--tight { margin-top: 0; }
.cw-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 14px; }
.cw-card { background: var(--cw-surface); border: 1px solid var(--cw-line); border-radius: 18px; padding: 18px; text-align: left; }
.cw-card--click { cursor: pointer; font-family: inherit; }
.cw-card--click:hover { border-color: #c9cbd1; box-shadow: 0 8px 24px rgba(16,24,40,.05); }
.cw-card__top { display: flex; justify-content: space-between; align-items: flex-start; gap: 16px; }
.cw-card__title { margin: 0 0 6px; font-size: 16px; }
.cw-muted { color: var(--cw-muted); font-size: 13px; line-height: 1.55; margin: 0; }

.cw-badge { display: inline-flex; align-items: center; gap: 6px; padding: 6px 10px; border-radius: 999px; font-size: 11px; font-weight: 700; white-space: nowrap; }
.cw-badge--working { background: var(--cw-accent-soft); color: var(--cw-accent); }
.cw-badge--done { background: var(--cw-green-soft); color: var(--cw-green); }
.cw-badge--needs { background: var(--cw-amber-soft); color: var(--cw-amber); }

/* Working */
.cw-workspace { display: grid; grid-template-columns: minmax(0, 1fr) 330px; gap: 18px; align-items: start; }
.cw-panel { background: var(--cw-surface); border: 1px solid var(--cw-line); border-radius: 18px; }
.cw-panel__head { padding: 20px 22px; border-bottom: 1px solid var(--cw-line); }
.cw-panel__body { padding: 22px; }
.cw-titlerow { display: flex; justify-content: space-between; gap: 16px; align-items: flex-start; }
.cw-panel__title { margin: 0 0 6px; font-size: 24px; letter-spacing: -.02em; }
.cw-progress { margin-top: 18px; height: 8px; background: #eef0f3; border-radius: 999px; overflow: hidden; }
.cw-progress__fill { height: 100%; background: var(--cw-accent); border-radius: 999px; transition: width 500ms ease; }
.cw-steps { display: flex; flex-direction: column; gap: 12px; }
.cw-step { display: flex; gap: 12px; align-items: flex-start; opacity: .55; transition: opacity 300ms; }
.cw-step--done, .cw-step--active { opacity: 1; }
.cw-dot { width: 24px; height: 24px; border-radius: 50%; background: #eef0f3; display: grid; place-items: center; font-size: 12px; flex: 0 0 auto; }
.cw-step--done .cw-dot { background: var(--cw-green-soft); color: var(--cw-green); }
.cw-step--active .cw-dot { background: var(--cw-accent-soft); color: var(--cw-accent); }
.cw-step__title { font-size: 14px; }
.cw-step__detail { margin: 3px 0 0; color: var(--cw-muted); font-size: 12px; line-height: 1.5; }
.cw-finding { padding: 14px 0; border-bottom: 1px solid var(--cw-line); }
.cw-finding:last-child { border-bottom: 0; }
.cw-finding__title { font-size: 14px; }
.cw-finding__detail { margin: 5px 0 0; color: var(--cw-muted); font-size: 13px; line-height: 1.55; }
.cw-source-list { display: flex; flex-direction: column; gap: 10px; }
.cw-source { padding: 12px; background: #f7f8fa; border-radius: 12px; font-size: 13px; display: flex; justify-content: space-between; gap: 10px; }
.cw-source__detail { color: var(--cw-muted); text-align: right; }
.cw-source--pending { align-items: center; }
.cw-spinner { width: 14px; height: 14px; border: 2px solid #d5d8dd; border-top-color: var(--cw-accent); border-radius: 50%; animation: cw-spin 700ms linear infinite; }
@keyframes cw-spin { to { transform: rotate(360deg); } }

/* Completed */
.cw-result-hero { padding: 22px; background: linear-gradient(180deg, #f6fbfa 0%, #fff 100%); border-bottom: 1px solid var(--cw-line); border-radius: 18px 18px 0 0; }
.cw-metric { font-size: 32px; font-weight: 800; letter-spacing: -.03em; margin: 12px 0 0; }
.cw-note { margin: 8px 0 0; font-size: 12px; color: var(--cw-muted); }
.cw-actions { display: flex; gap: 10px; flex-wrap: wrap; margin-top: 18px; }
.cw-actions--foot { margin-top: 24px; }
.cw-summary { display: grid; gap: 10px; }
.cw-summary__item { display: flex; justify-content: space-between; gap: 16px; padding: 12px 0; border-bottom: 1px solid var(--cw-line); }
.cw-summary__item:last-child { border-bottom: 0; }
.cw-summary__title { font-size: 14px; }

@media (max-width: 900px) {
  .cw-main { padding: 24px 18px 48px; }
  .cw-grid, .cw-workspace { grid-template-columns: 1fr; }
}
</style>
