<script setup lang="ts">
/**
 * Cowork — the ERP's AI co-worker. Renders inside the standard stage (white
 * main area) with the page title bar supplied by [...slug].vue.
 *
 * Built from Pixel 3 Enterprise (DT 2.4) components — MpButton, MpBadge,
 * MpTextarea, MpSelect, MpProgress, MpToggle, MpModal, MpIcon — plus the
 * established ERP enterprise-card + table conventions. Sections are chosen by the
 * Cowork level-2 submenu (ErpSidebar panel): /cowork, /cowork-tasks,
 * /cowork-schedule, /cowork-connections. Nothing bespoke.
 *
 * Cowork takes on tasks across every module (HR, Sales/CRM, WMS, Finance,
 * Production), can schedule them to recur, and works over connected products.
 * Task briefings are generated by Gemini (/api/cowork/plan), grounded on the
 * mock DB via useCoworkContext.
 */
import { h, ref, reactive, computed, watch, onMounted, onBeforeUnmount, nextTick } from 'vue'
import {
  MpButton, MpBadge, MpIcon, MpProgress, MpSpinner, MpToggle, MpSkeleton, MpSelect, MpInput,
  MpPopover, MpPopoverTrigger, MpPopoverContent, MpPopoverList, MpPopoverListItem,
  MpModal, MpModalContent, MpModalHeader, MpModalBody, MpModalFooter, MpModalCloseButton, MpModalOverlay,
  css, toast,
} from '@mekari/pixel3'
import ErpStatusBadge from '~/components/patterns/ErpStatusBadge.vue'
import ErpPagination from '~/components/patterns/ErpPagination.vue'
import { infoToast } from '~/utils/toasts'
import { getEmployee } from '~/data'
import { useCoworkContext } from '~/composables/useCoworkContext'
import { useGoogleConnect } from '~/composables/useGoogleConnect'
import { formatDateTime } from '~/utils/date'
import {
  coworkTasks, coworkConnections,
  COWORK_CATALOG, COWORK_BUILTIN, COWORK_CONNECTION_CATEGORIES,
  addTask, updateTask, deleteTask, getTask,
  setTaskScheduleEnabled, unscheduleTask, setConnection, addCoworkConnection, removeCoworkConnection,
  type CoworkTask, type CoworkModule, type CoworkCadence, type CoworkConnection, type CoworkConnectionCategory,
} from '~/data/cowork'

const route = useRoute()
const router = useRouter()
const { build } = useCoworkContext()

// First-load skeleton (ERP guideline: solid rows, ~1.2s) for Tasks + Schedule.
const loading = ref(true)
onMounted(() => { setTimeout(() => { loading.value = false }, 1200) })

// ── Tasks table state — status filter (left) + search (right) + pagination ────
const taskStatusOptions = [
  { value: 'running',   label: 'Running' },
  { value: 'completed', label: 'Completed' },
  { value: 'failed',    label: 'Failed' },
  { value: 'scheduled', label: 'Scheduled' },
]
const taskSource = computed(() => coworkTasks)
const {
  search: taskSearch, statusFilter: taskStatus, currentPage: taskPage, perPage: taskPerPage,
  paginated: taskRows, total: taskTotal, setPage: taskSetPage, setPerPage: taskSetPerPage,
} = useTableState<CoworkTask>(taskSource, {
  perPage: 10,
  filterFn: (t, s, status) =>
    (!s || t.title.toLowerCase().includes(s) || t.id.toLowerCase().includes(s) || t.module.toLowerCase().includes(s))
    && (!status || t.status === status),
})
const taskStatusLabel = computed(() => taskStatusOptions.find((o) => o.value === taskStatus.value)?.label ?? '')

// ── Schedule table state — status filter (left) + search (right) + pagination ─
const schedStatusOptions = [
  { value: 'active', label: 'Active' },
  { value: 'paused', label: 'Paused' },
]
// The Schedule page lists tasks that HAVE a schedule (derived from the tasks list,
// so deleting a task removes its schedule here automatically).
const schedSource = computed(() => coworkTasks.filter((t) => t.schedule))
const {
  search: schedSearch, statusFilter: schedStatus, currentPage: schedPage, perPage: schedPerPage,
  paginated: schedRows, total: schedTotal, setPage: schedSetPage, setPerPage: schedSetPerPage,
} = useTableState<CoworkTask>(schedSource, {
  perPage: 10,
  filterFn: (s, q, status) =>
    (!q || s.title.toLowerCase().includes(q) || s.module.toLowerCase().includes(q))
    && (!status || (status === 'active' ? !!s.schedule?.enabled : !s.schedule?.enabled)),
})
const schedStatusLabel = computed(() => schedStatusOptions.find((o) => o.value === schedStatus.value)?.label ?? '')

// Gemini mark — a 4-point star with Google's multi-hue gradient (not the Airene
// purple sparkle) for the model picker.
const GeminiMark = (props: { size?: number }) =>
  h('svg', { width: props.size ?? 16, height: props.size ?? 16, viewBox: '0 0 24 24', fill: 'none', 'aria-hidden': 'true' }, [
    h('defs', [
      h('linearGradient', { id: 'cw-gemini', x1: '2', y1: '3', x2: '22', y2: '21', gradientUnits: 'userSpaceOnUse' }, [
        h('stop', { offset: '0', 'stop-color': '#1BA1E3' }),
        h('stop', { offset: '0.3', 'stop-color': '#5489D6' }),
        h('stop', { offset: '0.55', 'stop-color': '#9B72CB' }),
        h('stop', { offset: '0.8', 'stop-color': '#D96570' }),
        h('stop', { offset: '1', 'stop-color': '#F49C46' }),
      ]),
    ]),
    h('path', { d: 'M12 2c.3 4.9 4.8 9.4 9.7 9.7v.6C16.8 12.6 12.3 17.1 12 22h-.6c-.3-4.9-4.8-9.4-9.7-9.7v-.6C6.6 11.4 11.1 6.9 11.4 2H12z', fill: 'url(#cw-gemini)' }),
  ])

// The active section is driven by the Cowork level-2 submenu (ErpSidebar panel):
// /cowork = Overview, /cowork/tasks, /cowork/schedule, /cowork/connections.
const section = computed(() => {
  const p = route.path
  if (p.startsWith('/cowork-tasks')) return 'Tasks'
  if (p.startsWith('/cowork-schedule')) return 'Schedule'
  if (p.startsWith('/cowork-connections')) return 'Connections'
  if (p.startsWith('/cowork-agents')) return 'Agents'
  if (p.startsWith('/cowork-skills')) return 'Skills'
  return 'Overview'
})

// ── Composer ─────────────────────────────────────────────────────────────────
const prompt = ref('')
const promptEl = ref<HTMLTextAreaElement | null>(null)
function focusPrompt() { requestAnimationFrame(() => promptEl.value?.focus()) }
function soon(what: string) { infoToast(`${what} — coming soon`) }

// ── Run workspace ────────────────────────────────────────────────────────────
interface Step { title: string; detail: string }
interface Source { name: string; detail: string }
interface SummaryItem { title: string; detail: string; priority: 'High' | 'Medium' | 'Low' }
interface ActionItem { title: string; detail: string; owner: string; due: string; priority: 'High' | 'Medium' | 'Low' }
interface Artifacts {
  briefing?: { summary: SummaryItem[]; findings: { title: string; detail: string }[] }
  actionItems?: ActionItem[]
  email?: { to: string; subject: string; body: string }
  spreadsheet?: { title: string; columns: string[]; rows: string[][] }
  pdf?: { title: string; sections: { heading: string; body: string }[] }
}
interface Plan {
  taskTitle: string; intro: string; metric: string
  sources: Source[]; steps: Step[]
  artifacts: Artifacts
}

const openTaskId = ref<string | null>(null)
const openTask = computed(() => (openTaskId.value ? getTask(openTaskId.value) : null))
const plan = ref<Plan | null>(null)
const planSource = ref<'gemini' | 'fallback' | ''>('')
const runState = ref<'working' | 'completed'>('working')

const DEFAULT_STEPS: Step[] = [
  { title: 'Read task context', detail: 'Parsing your request and connected products.' },
  { title: 'Pull the relevant data', detail: 'Employees, customers, stock, invoices, work orders.' },
  { title: 'Cross-check the modules', detail: 'Reconciling figures across HR, CRM, WMS and finance.' },
  { title: 'Prioritise what matters', detail: 'Ranking risks, decisions and actions.' },
  { title: 'Build the briefing', detail: 'Writing the summary and follow-ups.' },
]
const liveSteps = ref<Step[]>(DEFAULT_STEPS)
const activeStepIndex = ref(0)
const apiDone = ref(false)
let stepTimer: ReturnType<typeof setInterval> | null = null

const progressValue = computed(() => {
  const total = liveSteps.value.length || 1
  return String(Math.min(100, Math.round((activeStepIndex.value / total) * 100)))
})

// `run` = execute immediately (composer send, or a card's "Run task"); false =
// just create the task and open its detail page in the pre-run state.
function assign(taskPrompt: string, title?: string, module?: CoworkModule, run = true) {
  const p = taskPrompt.trim()
  if (!p) return
  // A predefined card (module given) scopes to its own module; a free-form
  // composer prompt uses the sources the user toggled on.
  const fromCatalog = !!module
  const active = sources.value.filter((s) => isSourceOn(s.id)).map((s) => s.name) as CoworkModule[]
  const primary = module ?? inferModule(p)
  const modules = fromCatalog ? [primary] : (active.length ? active : [primary])
  const task = addTask({
    title: title ?? (p.length > 52 ? p.slice(0, 50) + '…' : p),
    prompt: p,
    module: primary,
    modules,
    status: run ? 'running' : 'scheduled',
    createdAt: new Date().toISOString(),
    outputs: OUTPUTS.filter((o) => isOutputOn(o.id)).map((o) => o.name),
    sources: modules,
    model: model.value,
  })
  prompt.value = ''
  // Running (when requested) happens on the task detail page, which owns the run
  // history + result; otherwise the detail opens in its pre-run state.
  router.push({ path: `/cowork-tasks/${task.id}`, query: run ? { run: '1' } : {} })
}

function inferModule(text: string): CoworkModule {
  const t = text.toLowerCase()
  if (/(payroll|attendance|employee|contract|resign|leave|hr\b)/.test(t)) return 'HR'
  if (/(stock|warehouse|sku|inbound|outbound|fulfil|pick|pack|cycle count)/.test(t)) return 'WMS'
  if (/(invoice|receivable|payable|bill|reconcil|cash|payment|close)/.test(t)) return 'Finance'
  if (/(work order|production|bom|manufactur)/.test(t)) return 'Production'
  if (/(order|deliver|ship)/.test(t)) return 'Sales'
  return 'CRM'
}

function startRun(task: CoworkTask) {
  openTaskId.value = task.id
  plan.value = null
  planSource.value = ''
  apiDone.value = false
  runState.value = 'working'
  liveSteps.value = DEFAULT_STEPS
  activeStepIndex.value = 0
  if (stepTimer) clearInterval(stepTimer)
  stepTimer = setInterval(() => {
    if (activeStepIndex.value < liveSteps.value.length) activeStepIndex.value += 1
    maybeComplete()
  }, 1400)
  fetchPlan(task)
}

async function fetchPlan(task: CoworkTask) {
  try {
    const activeSources = sources.value.filter((s) => isSourceOn(s.id)).map((s) => s.name)
    const activeOutputs = OUTPUTS.filter((o) => isOutputOn(o.id)).map((o) => o.name)
    const res = await $fetch<{ plan: Plan; source: 'gemini' | 'fallback' }>('/api/cowork/plan', {
      method: 'POST',
      body: { task: task.prompt, context: build(), model: model.value, sources: activeSources, outputs: activeOutputs },
    })
    plan.value = res.plan
    planSource.value = res.source
    if (res.plan?.steps?.length) liveSteps.value = res.plan.steps
  } catch {
    planSource.value = 'fallback'
  } finally {
    apiDone.value = true
    maybeComplete()
  }
}

function maybeComplete() {
  if (apiDone.value && plan.value && activeStepIndex.value >= liveSteps.value.length) {
    if (stepTimer) { clearInterval(stepTimer); stepTimer = null }
    setTimeout(finishRun, 600)
  }
}
function finishRun() {
  if (!openTask.value || !plan.value) return
  runState.value = 'completed'
  updateTask(openTask.value.id, {
    status: 'completed',
    completedAt: new Date().toISOString(),
    metric: plan.value.metric,
    planJson: JSON.stringify(plan.value),
  })
}

// ── Artifact downloads ───────────────────────────────────────────────────────
function downloadBlob(name: string, mime: string, content: string) {
  const url = URL.createObjectURL(new Blob([content], { type: mime }))
  const a = document.createElement('a')
  a.href = url; a.download = name; a.click()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}
function downloadCsv() {
  const s = plan.value?.artifacts?.spreadsheet
  if (!s) return
  const esc = (v: string) => `"${String(v ?? '').replace(/"/g, '""')}"`
  const csv = [s.columns, ...s.rows].map((r) => r.map(esc).join(',')).join('\n')
  downloadBlob(`${(s.title || 'cowork').replace(/\s+/g, '-').toLowerCase()}.csv`, 'text/csv', csv)
}
async function downloadPdf() {
  const p = plan.value?.artifacts?.pdf
  if (!p) return
  const { default: JsPDF } = await import('jspdf')
  const doc = new JsPDF({ unit: 'pt', format: 'a4' })
  const M = 48; let y = M
  doc.setFontSize(18); doc.text(p.title || 'Report', M, y); y += 28
  doc.setFontSize(11)
  for (const sec of p.sections) {
    doc.setFont('helvetica', 'bold'); doc.text(sec.heading, M, y); y += 18
    doc.setFont('helvetica', 'normal')
    for (const line of doc.splitTextToSize(sec.body, 500)) {
      if (y > 780) { doc.addPage(); y = M }
      doc.text(line, M, y); y += 15
    }
    y += 12
  }
  doc.save(`${(p.title || 'cowork').replace(/\s+/g, '-').toLowerCase()}.pdf`)
}
function copyEmail() {
  const e = plan.value?.artifacts?.email
  if (!e) return
  navigator.clipboard?.writeText(`To: ${e.to}\nSubject: ${e.subject}\n\n${e.body}`)
  toast.notify({ variant: 'success', title: 'Email copied' })
}

// Open a task on its detail page (run history + result live there).
function openTaskDetail(task: CoworkTask) {
  router.push(`/cowork-tasks/${task.id}`)
}

function backToIndex() {
  if (stepTimer) { clearInterval(stepTimer); stepTimer = null }
  openTaskId.value = null
  plan.value = null
}
function rerun() { if (openTask.value) startRun(openTask.value) }
function removeTask(id: string) {
  deleteTask(id)
  toast.notify({ variant: 'success', title: 'Task deleted' })
}

// ── Overview data ────────────────────────────────────────────────────────────
// Suggested tasks grouped by module (Finance, HR, Sales, CRM, WMS, Production).
const MODULE_ORDER: CoworkModule[] = ['Finance', 'HR', 'Sales', 'CRM', 'WMS', 'Production']
const suggestedGroups = computed(() =>
  MODULE_ORDER
    .map((m) => ({ module: m, items: COWORK_CATALOG.filter((c) => c.module === m) }))
    .filter((g) => g.items.length),
)
// Employees (Talenta HR DB) who have run a predefined task before → avatar stack.
function usedAvatars(ids?: string[]) {
  return (ids ?? []).map((id) => getEmployee(id)).filter(Boolean).slice(0, 4)
}
// Signed-in user (no auth in the prototype → Rizal Candra, EMP-0001). If they've
// already run a predefined task, the "Run task" affordance is dropped.
const CURRENT_USER_ID = 'EMP-0001'
function hasRun(item: { usedBy?: string[] }) { return !!item.usedBy?.includes(CURRENT_USER_ID) }

// ── Model picker ─────────────────────────────────────────────────────────────
const MODELS = [
  { id: 'gemini-flash-latest', label: 'Gemini Flash' },
  { id: 'gemini-pro-latest', label: 'Gemini Pro' },
  { id: 'gemini-flash-lite-latest', label: 'Gemini Flash Lite' },
]
const model = ref(MODELS[0].id)
const modelLabel = computed(() => MODELS.find((m) => m.id === model.value)?.label ?? 'Gemini Flash')

// ── Sources (which ERP domains Cowork may read) ──────────────────────────────
const SOURCE_MODULES = ['Finance', 'HR', 'Sales', 'CRM', 'WMS', 'Production']
const sources = computed(() => SOURCE_MODULES.map((name) => ({ id: name, name })))
const sourceOff = reactive<Record<string, boolean>>({})   // id → excluded
function isSourceOn(id: string) { return !sourceOff[id] }
function toggleSource(id: string, on: boolean) { sourceOff[id] = !on }
const activeSourceCount = computed(() => sources.value.filter((s) => isSourceOn(s.id)).length)

// ── Output (what Cowork should produce for the task) ─────────────────────────
const OUTPUTS = [
  { id: 'briefing', name: 'Briefing summary' },
  { id: 'action-items', name: 'Action items' },
  { id: 'email', name: 'Email draft' },
  { id: 'spreadsheet', name: 'Spreadsheet' },
  { id: 'pdf', name: 'PDF report' },
  { id: 'slack', name: 'Slack message', disabled: true },
]
const outputOn = reactive<Record<string, boolean>>({ briefing: true })
function isOutputOn(id: string) { return !!outputOn[id] }
function toggleOutput(id: string, on: boolean) { outputOn[id] = on }
const activeOutputCount = computed(() => OUTPUTS.filter((o) => isOutputOn(o.id)).length)

// A task's modules (multi-source → multiple); falls back to the single module.
function taskModules(t: CoworkTask): CoworkModule[] {
  return t.modules && t.modules.length ? t.modules : [t.module]
}
// Schedule cell — "Weekly at 09:00" / "Monthly at 15:00", or "No schedule".
function taskScheduleLabel(t: CoworkTask): string {
  return t.schedule ? `${t.schedule.cadence} at ${t.schedule.time}` : 'No schedule'
}

function statusProps(s: CoworkTask['status']) {
  if (s === 'running') return { status: 'in progress', label: 'Running' }
  if (s === 'completed') return { status: 'completed', label: 'Completed' }
  if (s === 'failed') return { status: 'failed', label: 'Failed' }
  return { status: 'draft', label: 'Scheduled' }
}

// ── Schedule ─────────────────────────────────────────────────────────────────
// The task being scheduled IS the composer prompt — the popover only sets cadence
// and time. Empty prompt → just focus the composer so the user writes one.
const schedCadence = ref<CoworkCadence>('Weekly')
const schedTime = ref('08:00')
const schedOpen = ref(false)   // controlled schedule popover (so the real button can close it)
function fmtTime(hhmm: string): string {
  const [h, m] = hhmm.split(':').map(Number)
  const ap = h! < 12 ? 'am' : 'pm'
  const h12 = h! % 12 || 12
  return m ? `${h12}:${String(m).padStart(2, '0')}${ap}` : `${h12}${ap}`
}
const cadenceWord: Record<CoworkCadence, string> = { Daily: 'day', Weekly: 'week', Monthly: 'month' }
// The schedule shown reflects whether the CURRENT prompt already maps to a task
// that has a schedule (matched on prompt text) — a schedule always belongs to a task.
const matchedTask = computed(() => {
  const t = prompt.value.trim()
  return t ? (coworkTasks.find((x) => x.prompt === t && x.schedule) ?? null) : null
})
const scheduleLabel = computed(() => {
  const s = matchedTask.value?.schedule
  return s ? `Every ${cadenceWord[s.cadence]} at ${fmtTime(s.time)}` : 'Schedule'
})
// Opening the popover prefills cadence/time from the existing schedule (if any).
function openSchedulePopover() {
  const s = matchedTask.value?.schedule
  if (s) { schedCadence.value = s.cadence; schedTime.value = s.time }
  schedOpen.value = !schedOpen.value
}
function scheduleFromPrompt() {
  const t = prompt.value.trim()
  if (!t) { focusPrompt(); return }
  const nextRun = schedCadence.value === 'Daily' ? `Tomorrow · ${schedTime.value}`
    : schedCadence.value === 'Weekly' ? `Next Mon · ${schedTime.value}`
    : `1st of month · ${schedTime.value}`
  const schedule = { cadence: schedCadence.value, time: schedTime.value, nextRun, enabled: true }
  const title = t.length > 52 ? t.slice(0, 50) + '…' : t
  // Scheduling attaches the recurrence to the task (existing prompt → update it;
  // otherwise create the task with the schedule so it shows in both Tasks & Schedule).
  const existing = coworkTasks.find((x) => x.prompt === t)
  if (existing) {
    updateTask(existing.id, { schedule })
    toast.notify({ variant: 'success', title: 'Schedule updated' })
  } else {
    const active = sources.value.filter((s) => isSourceOn(s.id)).map((s) => s.name) as CoworkModule[]
    const primary = inferModule(t)
    addTask({ title, prompt: t, module: primary, modules: active.length ? active : [primary], status: 'scheduled', createdAt: new Date().toISOString(), schedule })
    toast.notify({ variant: 'success', title: 'Task scheduled' })
  }
}

// ── Connections ──────────────────────────────────────────────────────────────
const google = useGoogleConnect()
const connecting = ref('')                          // id currently authorising
const connError = reactive<Record<string, string>>({})   // inline error per card
const connSample = reactive<Record<string, string>>({})  // live proof per card (e.g. email)

async function connectGoogle(c: CoworkConnection) {
  connError[c.id] = ''
  if (!google.isConfigured.value) {
    connError[c.id] = 'Google client ID not configured yet (NUXT_PUBLIC_GOOGLE_CLIENT_ID).'
    return
  }
  connecting.value = c.id
  try {
    const { sample } = await google.connect(c.scope!)
    setConnection(c.id, true)
    if (sample) connSample[c.id] = sample
    toast.notify({ variant: 'success', title: `${c.name} connected` })
  } catch (e: any) {
    connError[c.id] = e?.message === 'Google client ID not configured'
      ? 'Google client ID not configured yet.'
      : 'Could not connect. Please try again.'
  } finally {
    connecting.value = ''
  }
}
function disconnectConnection(c: CoworkConnection) {
  if (c.provider === 'google' && c.scope) google.disconnect(c.scope)
  delete connSample[c.id]
  // A custom MCP server is uninstalled (removed) rather than just disconnected.
  if (c.id.startsWith('custom-')) {
    removeCoworkConnection(c.id)
    toast.notify({ variant: 'success', title: `${c.name} uninstalled` })
    return
  }
  setConnection(c.id, false)
  toast.notify({ variant: 'success', title: `${c.name} disconnected` })
}
function connectFake(c: CoworkConnection) {
  setConnection(c.id, true)
  toast.notify({ variant: 'success', title: `${c.name} connected` })
}
function addConnection() { openMcpModal() }

// ── Custom MCP server modal ───────────────────────────────────────────────────
const mcpOpen = ref(false)
const mcpUrl = ref('')
const mcpName = ref('')
const mcpAuth = ref<'OAuth' | 'API key' | 'None'>('OAuth')
const mcpAdvanced = ref(false)
const mcpClientId = ref('')
const mcpClientSecret = ref('')
const mcpScope = ref('')
const mcpError = ref('')
const mcpRedirectUrl = computed(() =>
  (typeof window !== 'undefined' ? window.location.origin : 'https://mekari-erp.vercel.app') + '/cowork/mcp/oauth/callback')
const mcpUrlValid = computed(() => /^https?:\/\/.+\..+/.test(mcpUrl.value.trim()))
function openMcpModal() {
  mcpUrl.value = ''; mcpName.value = ''; mcpAuth.value = 'OAuth'; mcpAdvanced.value = false
  mcpClientId.value = ''; mcpClientSecret.value = ''; mcpScope.value = ''; mcpError.value = ''
  mcpOpen.value = true
}
function closeMcpModal() { mcpOpen.value = false }
function copyRedirectUrl() {
  navigator.clipboard?.writeText(mcpRedirectUrl.value)
  infoToast('Redirect URL copied')
}
function connectMcp() {
  if (!mcpUrlValid.value) { mcpError.value = 'Enter a valid MCP server URL starting with https://'; return }
  let host = mcpUrl.value.trim()
  try { host = new URL(mcpUrl.value.trim()).hostname.replace(/^www\./, '') } catch { /* keep raw */ }
  const name = mcpName.value.trim() || host
  // A Mekari AI MCP server carries the Mekari sparkle; others fall back to a monogram.
  const isMekari = /mekari\./i.test(host)
  addCoworkConnection({
    name, categories: ['Featured'], connected: true, provider: 'fake',
    detail: `Custom MCP · ${host}`,
    color: isMekari ? '#7C3AED' : '#3a4749',
    logo: isMekari ? '/connectors/mekari-mcp.svg' : undefined,
  })
  toast.notify({ variant: 'success', title: `${name} connected` })
  closeMcpModal()
}

// ── Connections marketplace grid (responsive category sections) ───────────────
// Mirrors the WMS Reports index: edge-to-edge cards whose 1px right/bottom borders
// draw the grid; incomplete last rows are padded with empty cells. Columns scale
// with width — 3 at a normal stage, up to 6 when very wide.
const connSearch = ref('')
// Left filter = connection status (All / Connected / Not connected).
const connStatus = ref<'all' | 'connected' | 'not'>('all')
const connStatusOptions = [
  { value: 'all', label: 'All connections' },
  { value: 'connected', label: 'Connected' },
  { value: 'not', label: 'Not connected' },
] as const
const connStatusLabel = computed(() => connStatusOptions.find((o) => o.value === connStatus.value)?.label ?? '')
// Logo tile falls back to a coloured monogram if the favicon fails to load.
const connLogoFailed = reactive<Record<string, boolean>>({})
const CONN_MIN_CARD = 300   // ~3 cols on a normal stage, scaling up to 6 when very wide
const CONN_MAX_COLS = 6
const connGridEl = ref<HTMLElement | null>(null)
const connCols = ref(3)
function recomputeConnCols() {
  const w = connGridEl.value?.clientWidth ?? 0
  if (!w) return
  connCols.value = Math.max(1, Math.min(CONN_MAX_COLS, Math.floor(w / CONN_MIN_CARD)))
}
let connRo: ResizeObserver | null = null
watch([section, connGridEl], async () => {
  if (section.value !== 'Connections') { connRo?.disconnect(); connRo = null; return }
  await nextTick()
  recomputeConnCols()
  if (connGridEl.value && 'ResizeObserver' in window && !connRo) {
    connRo = new ResizeObserver(recomputeConnCols)
    connRo.observe(connGridEl.value)
  }
}, { immediate: true })
onBeforeUnmount(() => connRo?.disconnect())

function connLogo(name: string): string {
  return name.replace(/[^A-Za-z0-9 ]/g, '').split(/\s+/).filter(Boolean).slice(0, 2).map((w) => w[0]!.toUpperCase()).join('').slice(0, 2)
}

interface ConnSection { category: CoworkConnectionCategory; items: CoworkConnection[]; filler: number }
const connSections = computed<ConnSection[]>(() => {
  const q = connSearch.value.trim().toLowerCase()
  const out: ConnSection[] = []
  for (const cat of COWORK_CONNECTION_CATEGORIES) {
    const items = coworkConnections.filter((c) =>
      c.categories.includes(cat)
      && (connStatus.value === 'all' || (connStatus.value === 'connected' ? c.connected : !c.connected))
      && (!q || c.name.toLowerCase().includes(q) || (c.detail ?? '').toLowerCase().includes(q)))
    if (!items.length) continue
    const rem = items.length % connCols.value
    out.push({ category: cat, items, filler: rem === 0 ? 0 : connCols.value - rem })
  }
  return out
})
function toggleConnection(c: CoworkConnection) {
  if (c.connected) { disconnectConnection(c); return }
  if (c.provider === 'google') connectGoogle(c)
  else connectFake(c)
}
function manageConnection(c: CoworkConnection) {
  infoToast(`Manage ${c.name} — coming soon`)
}

// Leaving a section (clicking a submenu item) closes any open task workspace.
watch(() => route.path, (n, o) => { if (openTaskId.value && n !== o) backToIndex() })

// Title-bar actions (rendered by [...slug].vue) drive the page via the URL:
//   /cowork?focus=1        → focus the composer (from "+ New task" on Tasks)
//   /cowork-schedule?new=1 → open the schedule modal (from the Schedule action)
function handleQueryTriggers() {
  const q = route.query
  if (q.focus === '1') { focusPrompt(); router.replace({ path: '/cowork', query: {} }) }
  if (q.add === '1' && section.value === 'Connections') { addConnection(); router.replace({ path: '/cowork-connections', query: {} }) }
}
watch(() => route.fullPath, handleQueryTriggers)

onMounted(() => {
  const q = route.query
  if (typeof q.task === 'string' && q.task.trim() && q.run === '1') {
    // assign() creates the task and navigates to its detail page (which runs it).
    assign(q.task)
    return
  }
  handleQueryTriggers()
})
onBeforeUnmount(() => { if (stepTimer) clearInterval(stepTimer) })
</script>

<template>
  <div class="cowork">
    <!-- ══ RUN WORKSPACE ══ -->
    <template v-if="openTask">
      <button class="cw-back" type="button" @click="backToIndex">
        <MpIcon name="chevrons-left" size="sm" /> All tasks
      </button>

      <!-- Working -->
      <div v-if="runState === 'working'" class="cw-run">
        <section class="cw-card cw-card--main">
          <header class="cw-run__head">
            <div>
              <h2 class="cw-run__title">{{ plan?.taskTitle ?? openTask.title }}</h2>
              <p class="cw-muted">{{ plan?.intro ?? 'Cowork is reviewing your ERP data and identifying what needs your attention.' }}</p>
            </div>
            <ErpStatusBadge status="in progress" label="Running" badge-for="additionalInformation" />
          </header>
          <MpProgress :value="progressValue" size="sm" color="positive" :class="css({ marginTop: '16px' })" />
          <p class="cw-eyebrow cw-mt-24">What Cowork is doing</p>
          <ul class="cw-steps">
            <li v-for="(s, i) in liveSteps" :key="s.title + i" class="cw-step" :class="{ 'is-done': i < activeStepIndex, 'is-active': i === activeStepIndex }">
              <span class="cw-step__dot"><MpIcon v-if="i < activeStepIndex" name="check" size="sm" /><template v-else>{{ i + 1 }}</template></span>
              <div>
                <p class="cw-step__title">{{ s.title }}</p>
                <p class="cw-muted">{{ s.detail }}</p>
              </div>
            </li>
          </ul>
        </section>
        <aside class="cw-card cw-card--side">
          <p class="cw-side__title">Sources being used</p>
          <ul class="cw-sources">
            <li v-for="s in (plan?.sources ?? [])" :key="s.name" class="cw-source"><span>{{ s.name }}</span><span class="cw-muted">{{ s.detail }}</span></li>
            <li v-if="!plan" class="cw-source"><span class="cw-muted">Gathering sources…</span><MpSpinner size="sm" /></li>
          </ul>
        </aside>
      </div>

      <!-- Completed briefing -->
      <div v-else class="cw-run cw-run--single">
        <section class="cw-card cw-card--main">
          <header class="cw-run__head">
            <div>
              <h2 class="cw-run__title">{{ plan?.taskTitle }}</h2>
              <p class="cw-muted">{{ plan?.intro }}</p>
            </div>
            <ErpStatusBadge status="completed" badge-for="additionalInformation" />
          </header>
          <p class="cw-metric">{{ plan?.metric }}</p>
          <p v-if="planSource === 'fallback'" class="cw-note">Grounded summary (AI model offline) — figures still from your data.</p>
          <div class="cw-actions">
            <MpButton is-rounded variant="ghost" @click="rerun">Run again</MpButton>
          </div>

          <!-- Briefing summary -->
          <template v-if="plan?.artifacts?.briefing">
            <p class="cw-eyebrow cw-mt-24">Executive summary</p>
            <ul class="cw-summary">
              <li v-for="(s, i) in plan.artifacts.briefing.summary" :key="s.title" class="cw-summary__row">
                <div>
                  <p class="cw-summary__title">{{ i + 1 }}. {{ s.title }}</p>
                  <p class="cw-muted">{{ s.detail }}</p>
                </div>
                <ErpStatusBadge :status="s.priority.toLowerCase()" :label="s.priority" />
              </li>
            </ul>
            <template v-if="plan.artifacts.briefing.findings?.length">
              <p class="cw-eyebrow cw-mt-24">Key findings</p>
              <ul class="cw-findings">
                <li v-for="f in plan.artifacts.briefing.findings" :key="f.title" class="cw-finding">
                  <p class="cw-summary__title">{{ f.title }}</p><p class="cw-muted">{{ f.detail }}</p>
                </li>
              </ul>
            </template>
          </template>

          <!-- Action items -->
          <template v-if="plan?.artifacts?.actionItems?.length">
            <p class="cw-eyebrow cw-mt-24">Action items</p>
            <ul class="cw-summary">
              <li v-for="(a, i) in plan.artifacts.actionItems" :key="a.title + i" class="cw-summary__row">
                <div>
                  <p class="cw-summary__title">{{ a.title }}</p>
                  <p class="cw-muted">{{ a.detail }}</p>
                  <p class="cw-muted cw-ai-meta">{{ a.owner }} · {{ a.due }}</p>
                </div>
                <ErpStatusBadge :status="a.priority.toLowerCase()" :label="a.priority" />
              </li>
            </ul>
          </template>

          <!-- Email draft -->
          <template v-if="plan?.artifacts?.email">
            <div class="cw-art-head cw-mt-24">
              <p class="cw-eyebrow" style="margin:0">Email draft</p>
              <MpButton is-rounded variant="tertiary" size="sm" @click="copyEmail"><MpIcon name="copy" size="sm" /> Copy</MpButton>
            </div>
            <div class="cw-email">
              <p class="cw-email__row"><span class="cw-email__k">To</span> {{ plan.artifacts.email.to }}</p>
              <p class="cw-email__row"><span class="cw-email__k">Subject</span> {{ plan.artifacts.email.subject }}</p>
              <pre class="cw-email__body">{{ plan.artifacts.email.body }}</pre>
            </div>
          </template>

          <!-- Spreadsheet -->
          <template v-if="plan?.artifacts?.spreadsheet">
            <div class="cw-art-head cw-mt-24">
              <p class="cw-eyebrow" style="margin:0">{{ plan.artifacts.spreadsheet.title || 'Spreadsheet' }}</p>
              <MpButton is-rounded variant="tertiary" size="sm" @click="downloadCsv"><MpIcon name="download" size="sm" /> Download CSV</MpButton>
            </div>
            <div class="cw-table-wrap">
              <table class="cw-table">
                <thead><tr><th v-for="c in plan.artifacts.spreadsheet.columns" :key="c">{{ c }}</th></tr></thead>
                <tbody>
                  <tr v-for="(r, ri) in plan.artifacts.spreadsheet.rows" :key="ri">
                    <td v-for="(cell, ci) in r" :key="ci">{{ cell }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </template>

          <!-- PDF report -->
          <template v-if="plan?.artifacts?.pdf">
            <div class="cw-art-head cw-mt-24">
              <p class="cw-eyebrow" style="margin:0">{{ plan.artifacts.pdf.title || 'PDF report' }}</p>
              <MpButton is-rounded variant="tertiary" size="sm" @click="downloadPdf"><MpIcon name="download" size="sm" /> Download PDF</MpButton>
            </div>
            <div class="cw-findings">
              <div v-for="sec in plan.artifacts.pdf.sections" :key="sec.heading" class="cw-finding">
                <p class="cw-summary__title">{{ sec.heading }}</p><p class="cw-muted">{{ sec.body }}</p>
              </div>
            </div>
          </template>
        </section>

        <aside class="cw-card cw-card--side">
          <p class="cw-side__title">Sources used</p>
          <ul class="cw-sources">
            <li v-for="s in (plan?.sources ?? [])" :key="s.name" class="cw-source"><span>{{ s.name }}</span><span class="cw-muted">{{ s.detail }}</span></li>
          </ul>
        </aside>
      </div>
    </template>

    <!-- ══ INDEX (section chosen by the page-tab bar rendered outside the stage) ══ -->
    <template v-else>
        <!-- ── Overview (Figma) ── -->
        <section v-if="section === 'Overview'" class="cw-ov">
          <div class="cw-ov__inner">
            <h1 class="cw-hero">What can I do for you?</h1>

            <!-- Composer -->
            <div class="cw-composer2">
              <textarea
                ref="promptEl"
                v-model="prompt"
                class="cw-composer2__input"
                rows="3"
                placeholder="Assign a task to Cowork — it works across HR, Sales, CRM, WMS, finance & production…"
                @keydown.enter.exact.prevent="assign(prompt)"
              />
              <div class="cw-composer2__foot">
                <div class="cw-composer2__left">
                  <!-- Output popover: what Cowork should produce for this task -->
                  <MpPopover id="cw-output" placement="bottom-start">
                    <MpPopoverTrigger>
                      <button class="cw-foot-btn" type="button"><MpIcon name="doc" size="sm" /> Output<span v-if="activeOutputCount"> ({{ activeOutputCount }})</span></button>
                    </MpPopoverTrigger>
                    <MpPopoverContent :class="css({ minWidth: '260px' })">
                      <div class="cw-src">
                        <p class="cw-src__head">Output</p>
                        <p class="cw-src__hint">Choose what Cowork should produce.</p>
                        <div v-for="o in OUTPUTS" :key="o.id" class="cw-src__row" :class="{ 'is-disabled': o.disabled }">
                          <span class="cw-src__name">{{ o.name }}<span v-if="o.disabled" class="cw-soon">Coming soon</span></span>
                          <MpToggle v-if="!o.disabled" :is-checked="isOutputOn(o.id)" :aria-label="`Toggle ${o.name}`" @update:is-checked="(v: boolean) => toggleOutput(o.id, v)" />
                          <MpToggle v-else :is-checked="false" is-disabled aria-label="Slack coming soon" />
                        </div>
                      </div>
                    </MpPopoverContent>
                  </MpPopover>

                  <!-- Sources popover: connected sources with on/off toggles -->
                  <MpPopover id="cw-source" placement="bottom-start">
                    <MpPopoverTrigger>
                      <button class="cw-foot-btn" type="button"><MpIcon name="add" size="sm" /> Sources<span v-if="activeSourceCount"> ({{ activeSourceCount }})</span></button>
                    </MpPopoverTrigger>
                    <MpPopoverContent :class="css({ minWidth: '260px' })">
                      <div class="cw-src">
                        <p class="cw-src__head">Sources</p>
                        <p class="cw-src__hint">Choose which connected data Cowork may use.</p>
                        <div v-for="s in sources" :key="s.id" class="cw-src__row">
                          <span class="cw-src__name">{{ s.name }}</span>
                          <MpToggle :is-checked="isSourceOn(s.id)" :aria-label="`Toggle ${s.name}`" @update:is-checked="(v: boolean) => toggleSource(s.id, v)" />
                        </div>
                      </div>
                    </MpPopoverContent>
                  </MpPopover>

                  <!-- Schedule popover: cadence + time (the task is the prompt above) -->
                  <MpPopover id="cw-schedule" is-manual :is-open="schedOpen" placement="bottom-start" use-portal :is-keep-alive="false" @close="schedOpen = false">
                    <MpPopoverTrigger>
                      <button class="cw-foot-btn" type="button" :class="{ 'is-set': matchedTask }" @click="openSchedulePopover"><MpIcon name="time" size="sm" /> {{ scheduleLabel }}</button>
                    </MpPopoverTrigger>
                    <MpPopoverContent :class="css({ minWidth: '260px' })">
                      <div class="cw-src">
                        <p class="cw-src__head">Schedule this task</p>
                        <p class="cw-src__hint">Cowork runs your prompt automatically.</p>
                        <p class="cw-sched-label">Cadence</p>
                        <div class="cw-seg">
                          <button v-for="c in ['Daily','Weekly','Monthly']" :key="c" type="button" class="cw-seg__btn" :class="{ 'is-active': schedCadence === c }" @click="schedCadence = c as CoworkCadence">{{ c }}</button>
                        </div>
                        <p class="cw-sched-label">Time</p>
                        <div class="cw-seg">
                          <button v-for="t in ['07:00','08:00','09:00','18:00']" :key="t" type="button" class="cw-seg__btn" :class="{ 'is-active': schedTime === t }" @click="schedTime = t">{{ t }}</button>
                        </div>
                        <MpButton is-rounded variant="primary" is-full-width :class="css({ marginTop: '16px' })" @click="scheduleFromPrompt(); schedOpen = false">
                          {{ matchedTask ? 'Update schedule' : `Set schedule ${schedCadence.toLowerCase()} at ${schedTime}` }}
                        </MpButton>
                      </div>
                    </MpPopoverContent>
                  </MpPopover>
                </div>

                <div class="cw-composer2__right">
                  <!-- Model picker -->
                  <MpPopover id="cw-model" is-close-on-select placement="bottom-end">
                    <MpPopoverTrigger>
                      <button class="cw-model-btn" type="button">
                        <GeminiMark :size="16" />
                        {{ modelLabel }}
                        <MpIcon name="caret-down" size="sm" />
                      </button>
                    </MpPopoverTrigger>
                    <MpPopoverContent :class="css({ minWidth: '200px' })">
                      <MpPopoverList>
                        <MpPopoverListItem v-for="m in MODELS" :key="m.id" :is-active="m.id === model" @click="model = m.id">{{ m.label }}</MpPopoverListItem>
                      </MpPopoverList>
                    </MpPopoverContent>
                  </MpPopover>

                  <!-- Send / create task -->
                  <button class="cw-send-btn" type="button" aria-label="Assign task" @click="assign(prompt)">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true">
                      <path d="M12 19V5M12 5L6 11M12 5L18 11" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                  </button>
                </div>
              </div>
            </div>

            <!-- Suggested for you -->
            <div class="cw-suggest">
              <h3 class="cw-h3">Suggested for you</h3>
              <p class="cw-muted">Ready-made tasks across your ERP — run one to see Cowork work.</p>
              <template v-for="g in suggestedGroups" :key="g.module">
                <p class="cw-module-label">{{ g.module }}</p>
                <div class="cw-suggest-grid">
                  <!-- Card body opens the task detail (before running); "Run task" runs it. -->
                  <div v-for="c in g.items" :key="c.title" class="cw-suggest-item" role="button" tabindex="0" @click="assign(c.prompt, c.title, c.module, false)" @keydown.enter="assign(c.prompt, c.title, c.module, false)">
                    <span class="cw-suggest-icon">
                      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M13 2 4.5 13.5H11l-1 8.5 8.5-11.5H12l1-8.5Z" fill="currentColor"/></svg>
                    </span>
                    <span class="cw-suggest-text">
                      <span class="cw-suggest-title">{{ c.title }}</span>
                      <span class="cw-muted">{{ c.desc }}</span>
                      <span v-if="c.usedBy?.length" class="cw-suggest-used">
                        <span class="cw-avatars">
                          <img v-for="e in usedAvatars(c.usedBy)" :key="e!.id" :src="e!.photo" :alt="e!.fullName" class="cw-avatar" :title="e!.fullName">
                        </span>
                        Used {{ c.usedBy.length }} {{ c.usedBy.length === 1 ? 'time' : 'times' }}
                      </span>
                      <button v-if="!hasRun(c)" class="cw-suggest-run" type="button" @click.stop="assign(c.prompt, c.title, c.module, true)">Run task <MpIcon name="arrows-right" size="sm" /></button>
                    </span>
                  </div>
                </div>
              </template>
            </div>
          </div>
        </section>

        <!-- ── Tasks ── -->
        <section v-else-if="section === 'Tasks'">
          <!-- Filter bar: status (left) + search (right) -->
          <div class="cw-filter">
            <div class="cw-filter__left">
              <MpPopover id="cw-task-status" is-close-on-select>
                <MpPopoverTrigger>
                  <MpSelect id="cw-task-status-sel" placeholder="Status" :model-value="taskStatus" is-clearable :class="css({ width: '160px' })" @mousedown.prevent @clear="taskStatus = ''">
                    <option v-if="taskStatus" :value="taskStatus">{{ taskStatusLabel }}</option>
                  </MpSelect>
                </MpPopoverTrigger>
                <MpPopoverContent :class="css({ minWidth: '160px', width: 'max-content' })">
                  <MpPopoverList>
                    <MpPopoverListItem v-for="o in taskStatusOptions" :key="o.value" :is-active="o.value === taskStatus" @click="taskStatus = o.value">{{ o.label }}</MpPopoverListItem>
                  </MpPopoverList>
                </MpPopoverContent>
              </MpPopover>
            </div>
            <div class="cw-filter__right">
              <div class="cw-search">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M22 22L20 20M21 11.5C21 16.747 16.747 21 11.5 21C6.253 21 2 16.747 2 11.5C2 6.253 6.253 2 11.5 2C16.747 2 21 6.253 21 11.5Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>
                <input v-model="taskSearch" class="cw-search__input" type="text" placeholder="Search...">
                <button v-if="taskSearch" class="cw-search__clear" type="button" aria-label="Clear search" @click="taskSearch = ''">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M18 6L6 18M6 6l12 12" stroke="currentColor" stroke-width="1.75" stroke-linecap="round"/></svg>
                </button>
              </div>
            </div>
          </div>

          <div class="cw-table-wrap">
            <table class="cw-table">
              <thead>
                <tr><th>Task</th><th>Module</th><th>Status</th><th>Schedule</th><th>Last updated</th><th class="cw-th-actions" /></tr>
              </thead>
              <!-- First-load skeleton -->
              <tbody v-if="loading">
                <tr v-for="n in 3" :key="`sk-${n}`">
                  <td><MpSkeleton class="cw-skeleton" width="200px" height="14px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="72px" height="18px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="80px" height="18px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="110px" height="14px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="120px" height="14px" rounded="sm" duration="0s" /></td>
                  <td class="cw-td-actions" />
                </tr>
              </tbody>
              <tbody v-else>
                <tr v-for="t in taskRows" :key="t.id">
                  <td>
                    <span class="cw-cell-link" @click="openTaskDetail(t)">{{ t.title }}</span>
                  </td>
                  <td>
                    <span class="cw-modules">
                      <MpBadge v-for="m in taskModules(t)" :key="m" for="additionalInformation" type="announcement" size="sm">{{ m }}</MpBadge>
                    </span>
                  </td>
                  <td><ErpStatusBadge v-bind="statusProps(t.status)" /></td>
                  <td :class="{ 'cw-muted': !t.schedule }">{{ taskScheduleLabel(t) }}</td>
                  <td>{{ formatDateTime(t.completedAt ?? t.createdAt) }}</td>
                  <td class="cw-td-actions" @click.stop>
                    <MpPopover :id="`cw-task-${t.id}`" is-close-on-select use-portal :is-keep-alive="false" placement="bottom-end">
                      <MpPopoverTrigger>
                        <button class="cw-kebab" type="button" aria-label="Actions"><MpIcon name="menu-kebab" size="md" /></button>
                      </MpPopoverTrigger>
                      <MpPopoverContent :class="css({ minWidth: '160px' })">
                        <MpPopoverList>
                          <MpPopoverListItem @click="openTaskDetail(t)">Open</MpPopoverListItem>
                          <MpPopoverListItem @click="removeTask(t.id)">Delete</MpPopoverListItem>
                        </MpPopoverList>
                      </MpPopoverContent>
                    </MpPopover>
                  </td>
                </tr>
                <tr v-if="!taskRows.length"><td colspan="6" class="cw-empty">No tasks match your filters.</td></tr>
              </tbody>
            </table>
          </div>
          <ErpPagination :current-page="taskPage" :per-page="taskPerPage" :total="taskTotal" @page-change="taskSetPage" @per-page-change="taskSetPerPage" />
        </section>

        <!-- ── Schedule ── -->
        <section v-else-if="section === 'Schedule'">
          <!-- Filter bar: status (left) + search (right) -->
          <div class="cw-filter">
            <div class="cw-filter__left">
              <MpPopover id="cw-sched-status" is-close-on-select>
                <MpPopoverTrigger>
                  <MpSelect id="cw-sched-status-sel" placeholder="Status" :model-value="schedStatus" is-clearable :class="css({ width: '160px' })" @mousedown.prevent @clear="schedStatus = ''">
                    <option v-if="schedStatus" :value="schedStatus">{{ schedStatusLabel }}</option>
                  </MpSelect>
                </MpPopoverTrigger>
                <MpPopoverContent :class="css({ minWidth: '160px', width: 'max-content' })">
                  <MpPopoverList>
                    <MpPopoverListItem v-for="o in schedStatusOptions" :key="o.value" :is-active="o.value === schedStatus" @click="schedStatus = o.value">{{ o.label }}</MpPopoverListItem>
                  </MpPopoverList>
                </MpPopoverContent>
              </MpPopover>
            </div>
            <div class="cw-filter__right">
              <div class="cw-search">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M22 22L20 20M21 11.5C21 16.747 16.747 21 11.5 21C6.253 21 2 16.747 2 11.5C2 6.253 6.253 2 11.5 2C16.747 2 21 6.253 21 11.5Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>
                <input v-model="schedSearch" class="cw-search__input" type="text" placeholder="Search...">
                <button v-if="schedSearch" class="cw-search__clear" type="button" aria-label="Clear search" @click="schedSearch = ''">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M18 6L6 18M6 6l12 12" stroke="currentColor" stroke-width="1.75" stroke-linecap="round"/></svg>
                </button>
              </div>
            </div>
          </div>

          <div class="cw-table-wrap">
            <table class="cw-table">
              <thead>
                <tr><th>Task</th><th>Module</th><th>Cadence</th><th>Next run</th><th>Active</th><th class="cw-th-actions" /></tr>
              </thead>
              <!-- First-load skeleton -->
              <tbody v-if="loading">
                <tr v-for="n in 3" :key="`sk-${n}`">
                  <td><MpSkeleton class="cw-skeleton" width="200px" height="14px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="72px" height="18px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="110px" height="14px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="120px" height="14px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="36px" height="20px" rounded="sm" duration="0s" /></td>
                  <td class="cw-td-actions" />
                </tr>
              </tbody>
              <tbody v-else>
                <tr v-for="s in schedRows" :key="s.id">
                  <td><span class="cw-cell-link" @click="openTaskDetail(s)">{{ s.title }}</span></td>
                  <td>
                    <span class="cw-modules">
                      <MpBadge v-for="m in taskModules(s)" :key="m" for="additionalInformation" type="announcement" size="sm">{{ m }}</MpBadge>
                    </span>
                  </td>
                  <td>{{ s.schedule!.cadence }} · {{ s.schedule!.time }}</td>
                  <td>{{ s.schedule!.nextRun ?? '—' }}</td>
                  <td><MpToggle :is-checked="!!s.schedule!.enabled" :aria-label="`Toggle ${s.title}`" @update:is-checked="(v: boolean) => setTaskScheduleEnabled(s.id, v)" /></td>
                  <td class="cw-td-actions">
                    <button class="cw-kebab" type="button" aria-label="Remove schedule" @click="unscheduleTask(s.id)"><MpIcon name="delete" size="md" /></button>
                  </td>
                </tr>
                <tr v-if="!schedRows.length"><td colspan="6" class="cw-empty">No scheduled tasks.</td></tr>
              </tbody>
            </table>
          </div>
          <ErpPagination :current-page="schedPage" :per-page="schedPerPage" :total="schedTotal" @page-change="schedSetPage" @per-page-change="schedSetPerPage" />
        </section>

        <!-- ── Connections ── -->
        <section v-else-if="section === 'Connections'" class="cw-connections">
          <!-- Filter bar: status (left) + search (right) — same pattern as Tasks -->
          <div class="cw-filter">
            <div class="cw-filter__left">
              <MpPopover id="cw-conn-status" is-close-on-select>
                <MpPopoverTrigger>
                  <MpSelect id="cw-conn-status-sel" placeholder="Status" :model-value="connStatus" :class="css({ width: '180px' })" @mousedown.prevent>
                    <option :value="connStatus">{{ connStatusLabel }}</option>
                  </MpSelect>
                </MpPopoverTrigger>
                <MpPopoverContent :class="css({ minWidth: '180px', width: 'max-content' })">
                  <MpPopoverList>
                    <MpPopoverListItem v-for="o in connStatusOptions" :key="o.value" :is-active="o.value === connStatus" @click="connStatus = o.value">{{ o.label }}</MpPopoverListItem>
                  </MpPopoverList>
                </MpPopoverContent>
              </MpPopover>
            </div>
            <div class="cw-filter__right">
              <div class="cw-search">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M22 22L20 20M21 11.5C21 16.747 16.747 21 11.5 21C6.253 21 2 16.747 2 11.5C2 6.253 6.253 2 11.5 2C16.747 2 21 6.253 21 11.5Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>
                <input v-model="connSearch" class="cw-search__input" type="text" placeholder="Search connectors...">
                <button v-if="connSearch" class="cw-search__clear" type="button" aria-label="Clear search" @click="connSearch = ''">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M18 6L6 18M6 6l12 12" stroke="currentColor" stroke-width="1.75" stroke-linecap="round"/></svg>
                </button>
              </div>
            </div>
          </div>

          <div ref="connGridEl" class="cw-conn-sections">
            <section v-for="sec in connSections" :key="sec.category" class="cw-conn-section">
              <h2 class="cw-conn-cat-title">{{ sec.category }}</h2>
              <div class="cw-conn-clip">
                <div class="cw-conn-grid" :style="{ '--cols': connCols }">
                  <div v-for="c in sec.items" :key="sec.category + '-' + c.id" class="cw-conn-cell">
                    <div class="cw-conn-main">
                      <div class="cw-conn-head">
                        <img v-if="!connLogoFailed[c.id]" class="cw-conn-logo-img" :src="c.logo || `/connectors/${c.id}.png`" :alt="c.name" loading="lazy" @error="connLogoFailed[c.id] = true" />
                        <span v-else class="cw-conn-logo" :style="{ background: c.color || '#3a4749' }">{{ connLogo(c.name) }}</span>
                        <span class="cw-conn-name">{{ c.name }}</span>
                      </div>
                      <p class="cw-conn-desc">{{ c.detail }}</p>
                      <p v-if="connSample[c.id]" class="cw-conn-sample"><MpIcon name="check" size="sm" /> {{ connSample[c.id] }}</p>
                      <p v-if="connError[c.id]" class="cw-form-error cw-conn-err">{{ connError[c.id] }}</p>
                    </div>
                    <!-- Connected → kebab menu (Manage / Uninstall); otherwise a "+" to connect. -->
                    <MpPopover v-if="c.connected" :id="'cw-conn-menu-' + c.id" is-close-on-select placement="bottom-end">
                      <MpPopoverTrigger>
                        <button class="cw-conn-action is-connected" type="button" :aria-label="'Manage ' + c.name">
                          <MpIcon name="menu-kebab" size="md" />
                        </button>
                      </MpPopoverTrigger>
                      <MpPopoverContent :class="css({ minWidth: '160px' })">
                        <MpPopoverList>
                          <MpPopoverListItem @click="manageConnection(c)">Manage</MpPopoverListItem>
                          <MpPopoverListItem @click="disconnectConnection(c)">Uninstall</MpPopoverListItem>
                        </MpPopoverList>
                      </MpPopoverContent>
                    </MpPopover>
                    <button
                      v-else
                      class="cw-conn-action"
                      type="button"
                      :title="'Connect ' + c.name"
                      :aria-label="'Connect ' + c.name"
                      @click="toggleConnection(c)"
                    >
                      <MpSpinner v-if="connecting === c.id" size="sm" />
                      <MpIcon v-else name="add" size="md" />
                    </button>
                  </div>
                  <!-- Empty cells complete the last row (grid stays a full rectangle). -->
                  <div v-for="n in sec.filler" :key="sec.category + '-filler-' + n" class="cw-conn-cell cw-conn-cell--filler" aria-hidden="true" />
                </div>
              </div>
            </section>

            <p v-if="!connSections.length" class="cw-muted cw-conn-noresult">No connectors match “{{ connSearch }}”.</p>
          </div>
        </section>

        <!-- ── Agents ── -->
        <section v-else-if="section === 'Agents'" class="cw-placeholder">
          <MpIcon name="magic" size="lg" class="cw-placeholder__icon" />
          <h3 class="cw-placeholder__title">Agents are coming soon</h3>
          <p class="cw-placeholder__caption">Build focused AI agents — each with its own instructions, tools and connections — to run a slice of your ERP on autopilot.</p>
        </section>

        <!-- ── Skills ── -->
        <section v-else-if="section === 'Skills'" class="cw-placeholder">
          <MpIcon name="doc" size="lg" class="cw-placeholder__icon" />
          <h3 class="cw-placeholder__title">Skills are coming soon</h3>
          <p class="cw-placeholder__caption">Teach Cowork reusable skills — saved procedures and prompts it can apply across tasks, agents and modules.</p>
        </section>
    </template>

    <!-- ── Custom MCP server modal ── -->
    <MpModal id="cw-mcp-modal" :is-open="mcpOpen" size="md" is-close-on-esc is-close-on-overlay-click :is-keep-alive="false" @close="closeMcpModal">
      <MpModalContent>
        <MpModalHeader>
          <span class="mcp-title">Custom MCP server <MpBadge for="additionalInformation" type="announcement" size="sm">Beta</MpBadge></span>
          <MpModalCloseButton />
        </MpModalHeader>
        <MpModalBody>
          <p class="mcp-subtitle">Add your own server</p>

          <label class="mcp-label" for="mcp-url">MCP server URL</label>
          <div class="mcp-input-wrap" :class="{ 'is-valid': mcpUrlValid }">
            <input id="mcp-url" v-model="mcpUrl" class="mcp-input" type="url" @input="mcpError = ''" />
            <MpIcon v-if="mcpUrlValid" name="check" size="sm" class="mcp-valid-icon" />
          </div>
          <p v-if="mcpError" class="cw-form-error">{{ mcpError }}</p>

          <label class="mcp-label" for="mcp-name">Name</label>
          <input id="mcp-name" v-model="mcpName" class="mcp-input mcp-input--plain" type="text" />

          <div class="mcp-auth-row">
            <label class="mcp-label mcp-label--inline" for="mcp-auth">Authentication</label>
            <select id="mcp-auth" v-model="mcpAuth" class="mcp-auth-select">
              <option value="OAuth">OAuth</option>
              <option value="API key">API key</option>
              <option value="None">None</option>
            </select>
          </div>
          <p class="mcp-help">You will be redirected to the third party website to complete authentication when you connect.</p>

          <!-- Advanced settings accordion -->
          <button class="mcp-adv-toggle" type="button" @click="mcpAdvanced = !mcpAdvanced">
            <span>Advanced settings</span>
            <MpIcon :name="mcpAdvanced ? 'caret-down' : 'arrows-right'" size="sm" />
          </button>
          <div v-if="mcpAdvanced" class="mcp-adv">
            <p class="mcp-help mcp-help--adv">For MCP servers that require you to pre-register your own OAuth application, enter your client ID and client secret below. Use the redirect URL shown here when registering your app. Check the MCP provider’s documentation to learn more.</p>

            <label class="mcp-label" for="mcp-redirect">Redirect URL</label>
            <div class="mcp-input-wrap mcp-input-wrap--readonly">
              <input id="mcp-redirect" :value="mcpRedirectUrl" class="mcp-input" type="text" readonly />
              <button class="mcp-copy" type="button" aria-label="Copy redirect URL" @click="copyRedirectUrl"><MpIcon name="copy" size="sm" /></button>
            </div>

            <label class="mcp-label" for="mcp-cid">OAuth Client ID (optional)</label>
            <input id="mcp-cid" v-model="mcpClientId" class="mcp-input mcp-input--plain" type="text" />

            <label class="mcp-label" for="mcp-secret">OAuth Client Secret (optional)</label>
            <input id="mcp-secret" v-model="mcpClientSecret" class="mcp-input mcp-input--plain" type="password" />

            <label class="mcp-label" for="mcp-scope">Scope (optional)</label>
            <input id="mcp-scope" v-model="mcpScope" class="mcp-input mcp-input--plain" type="text" />
            <p class="mcp-help">Space-separated scopes to include in the authorization request. Leave blank to use server defaults.</p>
          </div>

          <!-- Trust warning -->
          <div class="mcp-warn">
            <p class="mcp-warn__title"><MpIcon name="warning-triangle" size="sm" /> Mekari Cowork hasn’t reviewed this server</p>
            <p class="mcp-warn__body">Once connected, it can access and modify your agent’s content and share data externally. Only connect servers you trust.</p>
          </div>
        </MpModalBody>
        <MpModalFooter>
          <div class="mcp-footer">
            <MpButton is-rounded variant="ghost" @click="closeMcpModal">Cancel</MpButton>
            <MpButton is-rounded variant="primary" @click="connectMcp">Connect</MpButton>
          </div>
        </MpModalFooter>
      </MpModalContent>
      <MpModalOverlay />
    </MpModal>
  </div>
</template>

<style scoped>
.cowork { display: flex; flex-direction: column; }

/* Enterprise card — border 1px, no drop-shadow (surface rule). */
.cw-card { border: 1px solid var(--mp-border-default, #e3e7e9); border-radius: var(--mp-radii-xl, 12px); background: var(--mp-background-neutral, #fff); padding: var(--mp-spacing-5, 20px); }
.cw-muted { margin: 0; color: var(--mp-text-secondary, #3a4749); font-size: var(--mp-font-sizes-sm, 12px); line-height: var(--mp-line-heights-sm, 16px); }
.cw-eyebrow { margin: 0 0 var(--mp-spacing-3); font-size: var(--mp-font-sizes-sm); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-h3 { margin: 0; font-size: var(--mp-font-sizes-lg, 16px); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-mt-24 { margin-top: var(--mp-spacing-6, 24px); }

/* Composer */
.cw-composer { margin-top: 0; }

/* ── Overview (Figma) — centered composer + module-grouped suggestions ── */
.cw-ov__inner { max-width: 880px; margin: 0 auto; width: 100%; }
.cw-hero { text-align: center; margin: var(--mp-spacing-2) 0 var(--mp-spacing-6); font-size: var(--mp-font-sizes-2xl, 24px); line-height: var(--mp-line-heights-xl, 32px); font-weight: var(--mp-font-weights-semi-bold); letter-spacing: var(--mp-letter-spacings-tight, -0.2px); color: var(--mp-text-default); }

/* Gray-subtle tray (20px), holding a fully-rounded white input card on top and
   the footer row below — so the input has rounded corners top AND bottom. */
.cw-composer2 { border: 1px solid var(--mp-border-default, #e3e7e9); border-radius: 20px; background: var(--mp-background-neutral-subtle, #f8f9f9); padding: var(--mp-spacing-1, 4px); }
.cw-composer2__input { display: block; width: 100%; border: 1px solid var(--mp-border-default, #e3e7e9); border-radius: 20px; outline: none; resize: none; font-family: inherit; font-size: var(--mp-font-sizes-md, 14px); line-height: var(--mp-line-heights-md, 20px); color: var(--mp-text-default); padding: var(--mp-spacing-4); background: var(--mp-background-neutral, #fff); min-height: 76px; }
.cw-composer2__input::placeholder { color: var(--mp-text-placeholder, #6e7a7c); }
.cw-composer2__input:focus { border-color: var(--mp-border-bold, #8c9596); }
/* Symmetric gap around the button row: the 4px tray padding below is topped up by
   the footer's 4px bottom so buttons→edge equals buttons→input (8px). */
.cw-composer2__foot { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); padding: var(--mp-spacing-2) var(--mp-spacing-2) var(--mp-spacing-1); background: var(--mp-background-neutral-subtle, #f8f9f9); }
.cw-composer2__left { display: flex; align-items: center; gap: var(--mp-spacing-1); }
.cw-foot-btn { display: inline-flex; align-items: center; gap: 4px; background: none; border: none; cursor: pointer; font-family: inherit; font-size: var(--mp-font-sizes-md); color: var(--mp-text-secondary); padding: var(--mp-spacing-1\.5, 6px) var(--mp-spacing-3); border-radius: var(--mp-radii-full, 999px); }
.cw-foot-btn:hover { background: var(--mp-background-neutral-pressed, #ebf0f1); color: var(--mp-text-default); }
.cw-foot-btn.is-set { color: var(--mp-text-selected, #0f6d4d); }
.cw-foot-btn.is-set :deep(svg), .cw-foot-btn.is-set :deep(path) { color: var(--mp-text-selected, #0f6d4d); }
.cw-foot-btn :deep(svg) { color: var(--mp-icon-default, #536062); }
.cw-composer2__right { display: flex; align-items: center; gap: var(--mp-spacing-2); }
.cw-send-btn { display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0; width: 36px; height: 36px; border: none; border-radius: var(--mp-radii-full, 999px); background: var(--mp-background-brand-bold, #029861); color: var(--mp-text-inverse, #fff); cursor: pointer; transition: filter .12s ease; }
.cw-send-btn:hover { filter: brightness(0.94); }
.cw-model-btn { display: inline-flex; align-items: center; gap: var(--mp-spacing-2); background: none; border: none; cursor: pointer; font-family: inherit; font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-regular); color: var(--mp-text-default); padding: var(--mp-spacing-1\.5, 6px) var(--mp-spacing-2); border-radius: var(--mp-radii-md, 8px); }
.cw-model-btn:hover { background: var(--mp-background-neutral-pressed, #ebf0f1); }
.cw-model-btn > svg:first-child { flex-shrink: 0; }

.cw-src { padding: var(--mp-spacing-2); }
.cw-src__head { margin: 0; font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-src__hint { margin: 2px 0 var(--mp-spacing-2); font-size: var(--mp-font-sizes-sm); color: var(--mp-text-secondary); }
.cw-src__row { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); padding: var(--mp-spacing-1\.5, 6px) var(--mp-spacing-1); }
.cw-src__name { font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); }
.cw-sched-label { margin: var(--mp-spacing-3) 0 var(--mp-spacing-1); font-size: var(--mp-font-sizes-sm); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-secondary); }
.cw-seg { display: flex; gap: var(--mp-spacing-1); flex-wrap: wrap; }
.cw-seg__btn { flex: 1 1 auto; min-width: 52px; padding: 6px 10px; border: 1px solid var(--mp-border-default, #e3e7e9); background: var(--mp-background-neutral, #fff); border-radius: var(--mp-radii-full, 999px); font-size: var(--mp-font-sizes-sm); color: var(--mp-text-default); cursor: pointer; font-family: inherit; }
.cw-seg__btn.is-active { border-color: var(--mp-text-selected, #0f6d4d); background: var(--mp-background-brand-selected, #d6f4e9); color: var(--mp-text-selected, #0f6d4d); font-weight: var(--mp-font-weights-semi-bold); }

.cw-suggest { margin-top: var(--mp-spacing-8, 32px); }
.cw-suggest .cw-h3 { font-size: var(--mp-font-sizes-xl, 20px); line-height: var(--mp-line-heights-xl, 28px); }
.cw-suggest > .cw-muted { margin-top: 2px; }
.cw-module-label { margin: var(--mp-spacing-10, 40px) 0 var(--mp-spacing-3); font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
/* First module label sits right under the "Suggested for you" caption. */
.cw-suggest > .cw-muted + .cw-module-label { margin-top: var(--mp-spacing-6, 24px); }
.cw-suggest-grid { display: grid; grid-template-columns: 1fr 1fr; gap: var(--mp-spacing-3) var(--mp-spacing-10, 40px); }
.cw-suggest-item { display: flex; gap: var(--mp-spacing-3); align-items: flex-start; background: none; border: none; padding: var(--mp-spacing-2) 0; cursor: pointer; text-align: left; font-family: inherit; }
.cw-suggest-icon { flex: 0 0 auto; width: 40px; height: 40px; border-radius: var(--mp-radii-full, 999px); background: #F8F8F8; border: 1px solid var(--mp-border-bold, #8c9596); box-shadow: 0 1px 2px rgba(16, 24, 40, 0.08); display: flex; align-items: center; justify-content: center; color: var(--mp-text-default); }
.cw-suggest-text { display: flex; flex-direction: column; gap: 2px; min-width: 0; }
.cw-suggest-title { font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-suggest-run { align-self: flex-start; display: inline-flex; align-items: center; gap: 4px; margin-top: var(--mp-spacing-2); padding: 0; background: none; border: none; cursor: pointer; font-family: inherit; font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-regular); color: var(--mp-text-link, #165082); }
.cw-suggest-run:hover { text-decoration: underline; text-underline-offset: 2px; }
.cw-suggest-used { display: inline-flex; align-items: center; gap: var(--mp-spacing-2); margin-top: var(--mp-spacing-2); font-size: var(--mp-font-sizes-md); color: var(--mp-text-secondary); }
.cw-avatars { display: inline-flex; }
.cw-avatar { width: 32px; height: 32px; border-radius: var(--mp-radii-full, 999px); object-fit: cover; border: 2px solid var(--mp-background-neutral, #fff); background: var(--mp-background-neutral-subtle, #f8f9f9); }
.cw-avatar + .cw-avatar { margin-left: -12px; }
.cw-suggest-item:hover .cw-suggest-run { text-decoration: underline; text-underline-offset: 2px; }
@media (max-width: 900px) { .cw-suggest-grid { grid-template-columns: 1fr; } }
.cw-composer__foot { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); margin-top: var(--mp-spacing-3); }
.cw-conn-chips { display: flex; flex-wrap: wrap; gap: var(--mp-spacing-2); }
.cw-conn-chip { display: inline-flex; align-items: center; gap: 4px; font-size: var(--mp-font-sizes-sm); color: var(--mp-text-secondary); background: var(--mp-background-neutral-subtle, #f8f9f9); border-radius: var(--mp-radii-full, 999px); padding: 3px 10px; }
.cw-conn-chip :deep(svg) { color: var(--mp-text-success, #186f4a); }

/* Section head */
.cw-section-head { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); margin: var(--mp-spacing-8) 0 var(--mp-spacing-4); }

/* Card grid */
.cw-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: var(--mp-spacing-4); }
.cw-card--click { text-align: left; cursor: pointer; display: flex; flex-direction: column; gap: var(--mp-spacing-2); font-family: inherit; transition: border-color 100ms; }
.cw-card--click:hover { border-color: var(--mp-border-bold, #8c9596); }
.cw-card__title { margin: 4px 0 0; font-size: var(--mp-font-sizes-md, 14px); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-card__cta { margin-top: auto; display: inline-flex; align-items: center; gap: 4px; font-size: var(--mp-font-sizes-sm); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-link, #165082); padding-top: var(--mp-spacing-2); }

/* Recent list */
.cw-list { display: flex; flex-direction: column; border: 1px solid var(--mp-border-default); border-radius: var(--mp-radii-xl, 12px); overflow: hidden; }
.cw-list-row { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); padding: var(--mp-spacing-3) var(--mp-spacing-4); background: var(--mp-background-neutral, #fff); border: none; border-top: 1px solid var(--mp-border-default); cursor: pointer; font-family: inherit; text-align: left; }
.cw-list-row:first-child { border-top: none; }
.cw-list-row:hover { background: var(--mp-background-neutral-subtle, #f8f9f9); }
.cw-list-row__main { display: flex; align-items: center; gap: var(--mp-spacing-3); min-width: 0; }
.cw-list-row__title { font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); font-weight: var(--mp-font-weights-regular); }
.cw-list-row__meta { display: flex; align-items: center; gap: var(--mp-spacing-4); flex-shrink: 0; }
.cw-empty { padding: var(--mp-spacing-6); text-align: center; color: var(--mp-text-secondary); font-size: var(--mp-font-sizes-sm); margin: 0; }

/* Table (ERP convention: no outer border, header fill, row bottom-border) */
/* Filter bar (Tasks): status left, search right — mirrors the ERP index filter bar. */
.cw-filter { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-4); margin-bottom: var(--mp-spacing-4); }
.cw-filter__left { display: flex; align-items: center; gap: var(--mp-spacing-3); }
.cw-filter__right { display: flex; align-items: center; gap: var(--mp-spacing-3); }
.cw-search { display: flex; align-items: center; gap: var(--mp-spacing-2); width: 248px; padding: var(--mp-spacing-2) var(--mp-spacing-3); background: var(--mp-background-neutral, #fff); border: 1px solid var(--mp-border-default); border-radius: var(--mp-radii-full, 999px); color: var(--mp-text-subtle); }
.cw-search__input { flex: 1; border: none; outline: none; background: transparent; font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); min-width: 0; }
.cw-search__input::placeholder { color: var(--mp-text-placeholder); }
.cw-search__clear { display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0; width: 18px; height: 18px; padding: 0; border: none; background: none; cursor: pointer; color: var(--mp-text-secondary); border-radius: 999px; }
.cw-search__clear:hover { background: var(--mp-background-neutral-hovered); }

/* First-load skeleton — solid, no shimmer/animation (ERP guideline). */
.cw-skeleton { background-image: none !important; background-color: var(--mp-border-default) !important; animation: none !important; }

/* Multiple module badges (multi-source task) wrap within the cell. */
.cw-modules { display: inline-flex; flex-wrap: wrap; gap: var(--mp-spacing-1); }

.cw-table-wrap { overflow-x: auto; }
.cw-table { width: 100%; border-collapse: collapse; }
.cw-table thead th { text-align: left; padding: var(--mp-spacing-2) var(--mp-spacing-3); background: var(--mp-background-neutral-subtle, #f8f9f9); font-size: var(--mp-font-sizes-sm); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-secondary); white-space: nowrap; }
.cw-table tbody td { padding: var(--mp-spacing-2) var(--mp-spacing-3); border-bottom: 1px solid var(--mp-border-default); font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); vertical-align: middle; }
.cw-th-actions, .cw-td-actions { width: 52px; text-align: right; }
.cw-cell-link { color: var(--mp-text-link, #165082); cursor: pointer; font-weight: var(--mp-font-weights-regular); }
.cw-cell-link:hover { text-decoration: underline; }
.cw-cell-sub { display: block; font-size: var(--mp-font-sizes-sm); color: var(--mp-text-secondary); }
.cw-kebab { display: inline-flex; align-items: center; justify-content: center; width: 32px; height: 32px; border: none; background: none; border-radius: var(--mp-radii-md); color: var(--mp-text-secondary); cursor: pointer; }
.cw-kebab:hover { background: var(--mp-background-neutral-subtle); color: var(--mp-text-default); }

/* ── Connections marketplace (Figma 1612:33080) ── */
.cw-connections { display: flex; flex-direction: column; }
.cw-connections .cw-filter { margin-bottom: var(--mp-spacing-5, 20px); }

.cw-conn-sections { display: flex; flex-direction: column; gap: var(--mp-spacing-8, 32px); }
/* Gap between the section title and its grid is 0 (per design). */
.cw-conn-cat-title { margin: 0; font-size: var(--mp-font-sizes-xl, 20px); font-weight: var(--mp-font-weights-semi-bold, 600); line-height: var(--mp-line-heights-xl, 32px); color: var(--mp-text-default, #080d0e); }

/* Edge-to-edge cards; borders draw the grid (clip the outer right/bottom). */
.cw-conn-clip { overflow: hidden; }
.cw-conn-grid { display: grid; grid-template-columns: repeat(var(--cols, 3), minmax(0, 1fr)); align-items: stretch; margin: 0 -1px -1px 0; }
.cw-conn-cell {
  display: flex; align-items: flex-start; justify-content: space-between; gap: var(--mp-spacing-2, 8px);
  min-height: 104px;
  padding: var(--mp-spacing-5, 20px);
  border-right: 1px solid var(--mp-border-default, #e3e7e9);
  border-bottom: 1px solid var(--mp-border-default, #e3e7e9);
}
.cw-conn-cell--filler { padding: 0; min-height: 104px; }
.cw-conn-main { flex: 1; min-width: 0; }
.cw-conn-head { display: flex; align-items: center; gap: var(--mp-spacing-2, 8px); }
.cw-conn-logo, .cw-conn-logo-img { width: 24px; height: 24px; flex-shrink: 0; border-radius: var(--mp-radii-md, 6px); }
.cw-conn-logo-img { object-fit: contain; }
.cw-conn-logo { display: inline-flex; align-items: center; justify-content: center; font-size: 10px; font-weight: var(--mp-font-weights-bold, 700); color: #fff; line-height: 1; }
.cw-conn-name { font-size: var(--mp-font-sizes-lg, 16px); font-weight: var(--mp-font-weights-semi-bold, 600); line-height: var(--mp-line-heights-lg, 24px); color: var(--mp-text-default, #080d0e); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.cw-conn-desc { margin: var(--mp-spacing-1, 4px) 0 0; font-size: var(--mp-font-sizes-md, 14px); line-height: var(--mp-line-heights-md, 20px); color: var(--mp-text-secondary, #3a4749); display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
.cw-conn-sample { display: inline-flex; align-items: center; gap: 4px; margin: var(--mp-spacing-1, 4px) 0 0; font-size: var(--mp-font-sizes-sm); color: var(--mp-text-success, #186f4a); }
.cw-conn-sample :deep(svg) { color: var(--mp-text-success, #186f4a); }
.cw-conn-err { font-size: var(--mp-font-sizes-xs, 12px); }

/* Right action: ghost "+" to connect, green check when connected. */
.cw-conn-action { display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0; width: 36px; height: 36px; border: none; background: none; border-radius: var(--mp-radii-md, 6px); cursor: pointer; color: var(--mp-icon-default, #536062); }
.cw-conn-action:hover { background: var(--mp-background-neutral-subtle, #f1f3f4); }
.cw-conn-action.is-connected { color: var(--mp-text-success, #186f4a); }
.cw-conn-noresult { padding: var(--mp-spacing-6, 24px) 0; }

/* ── Custom MCP server modal ── */
.mcp-title { display: inline-flex; align-items: center; gap: var(--mp-spacing-2, 8px); }
.mcp-subtitle { margin: 0 0 var(--mp-spacing-5, 20px); font-size: var(--mp-font-sizes-md, 14px); color: var(--mp-text-secondary, #3a4749); }
.mcp-label { display: block; margin: var(--mp-spacing-4, 16px) 0 var(--mp-spacing-2, 8px); font-size: var(--mp-font-sizes-md, 14px); font-weight: var(--mp-font-weights-semi-bold, 600); color: var(--mp-text-default, #080d0e); }
.mcp-input-wrap { position: relative; display: flex; align-items: center; }
.mcp-input { width: 100%; height: 40px; padding: 0 var(--mp-spacing-3, 12px); border: 1px solid var(--mp-border-form, #d0d5dd); border-radius: var(--mp-radii-md, 8px); background: var(--mp-background-neutral, #fff); font-family: inherit; font-size: var(--mp-font-sizes-md, 14px); color: var(--mp-text-default); outline: none; }
.mcp-input:focus { border-color: #2f6feb; box-shadow: 0 0 0 3px rgba(47,111,235,0.12); }
.mcp-input-wrap.is-valid .mcp-input { border-color: #2f6feb; padding-right: 36px; }
.mcp-valid-icon { position: absolute; right: 10px; color: #2f6feb; }
.mcp-input-wrap--readonly .mcp-input { background: var(--mp-background-neutral-subtle, #f8f9f9); color: var(--mp-text-secondary); padding-right: 40px; }
.mcp-copy { position: absolute; right: 6px; display: inline-flex; align-items: center; justify-content: center; width: 28px; height: 28px; border: none; background: none; border-radius: var(--mp-radii-md, 6px); color: var(--mp-icon-default, #536062); cursor: pointer; }
.mcp-copy:hover { background: var(--mp-background-neutral-hovered, #ebf0f1); }
.mcp-auth-row { display: flex; align-items: center; justify-content: space-between; margin-top: var(--mp-spacing-4, 16px); }
.mcp-label--inline { margin: 0; }
.mcp-auth-select { border: none; background: none; font-family: inherit; font-size: var(--mp-font-sizes-md, 14px); font-weight: var(--mp-font-weights-semi-bold, 600); color: var(--mp-text-default); cursor: pointer; }
.mcp-help { margin: var(--mp-spacing-2, 8px) 0 0; font-size: var(--mp-font-sizes-md, 14px); color: var(--mp-text-secondary, #3a4749); line-height: var(--mp-line-heights-md, 20px); }
.mcp-adv-toggle { display: flex; align-items: center; justify-content: space-between; width: 100%; margin-top: var(--mp-spacing-4, 16px); padding: var(--mp-spacing-3, 12px) var(--mp-spacing-4, 16px); border: 1px solid var(--mp-border-default, #e3e7e9); border-radius: var(--mp-radii-md, 8px); background: var(--mp-background-neutral, #fff); font-family: inherit; font-size: var(--mp-font-sizes-md, 14px); font-weight: var(--mp-font-weights-semi-bold, 600); color: var(--mp-text-default); cursor: pointer; }
.mcp-adv-toggle:hover { background: var(--mp-background-neutral-subtle, #f8f9f9); }
.mcp-adv { margin-top: var(--mp-spacing-3, 12px); }
.mcp-help--adv { margin-top: 0; }
.mcp-warn { margin-top: var(--mp-spacing-5, 20px); border: 1px solid var(--mp-border-warning, #f2d98d); border-radius: var(--mp-radii-md, 8px); overflow: hidden; }
.mcp-warn__title { display: flex; align-items: center; gap: var(--mp-spacing-1, 6px); margin: 0; padding: var(--mp-spacing-3, 12px) var(--mp-spacing-4, 16px); background: var(--mp-background-warning-subtle, #fdf6e3); color: var(--mp-text-warning, #9a6700); font-size: var(--mp-font-sizes-md, 14px); font-weight: var(--mp-font-weights-semi-bold, 600); }
.mcp-warn__body { margin: 0; padding: var(--mp-spacing-3, 12px) var(--mp-spacing-4, 16px); font-size: var(--mp-font-sizes-md, 14px); color: var(--mp-text-secondary, #3a4749); line-height: var(--mp-line-heights-md, 20px); }
.mcp-footer { display: flex; justify-content: flex-end; gap: var(--mp-spacing-2, 8px); width: 100%; }

/* ── Agents / Skills placeholder ── */
.cw-placeholder { display: flex; flex-direction: column; align-items: center; text-align: center; padding: var(--mp-spacing-10, 64px) var(--mp-spacing-6, 24px); max-width: 480px; margin: 0 auto; }
.cw-placeholder__icon { color: var(--mp-icon-default, #536062); margin-bottom: var(--mp-spacing-4, 16px); }
.cw-placeholder__title { margin: 0 0 var(--mp-spacing-2, 8px); font-size: var(--mp-font-sizes-lg, 16px); font-weight: var(--mp-font-weights-semi-bold, 600); color: var(--mp-text-default); }
.cw-placeholder__caption { margin: 0; font-size: var(--mp-font-sizes-md, 14px); line-height: var(--mp-line-heights-md, 20px); color: var(--mp-text-secondary, #3a4749); }

/* Form row */
.cw-form-row { display: grid; grid-template-columns: 1fr 1fr; gap: var(--mp-spacing-4); }
.cw-form-error { margin: var(--mp-spacing-2) 0 0; color: var(--mp-text-danger, #a8352d); font-size: var(--mp-font-sizes-sm); }

/* Run workspace — the left (task summary) column is not boxed; only the side rail is. */
.cw-run .cw-card--main, .cw-run--single .cw-card--main { border: none; background: none; padding: 0; }
.cw-note { margin: var(--mp-spacing-2) 0 0; font-size: var(--mp-font-sizes-sm); color: var(--mp-text-secondary); }
.cw-ai-meta { margin-top: 2px; }
.cw-soon { margin-left: var(--mp-spacing-2); font-size: var(--mp-font-sizes-xs, 11px); color: var(--mp-text-secondary); }
.cw-src__row.is-disabled .cw-src__name { color: var(--mp-text-secondary); }
.cw-art-head { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); margin-top: var(--mp-spacing-6); margin-bottom: var(--mp-spacing-3); }
.cw-email { border: 1px solid var(--mp-border-default); border-radius: var(--mp-radii-xl, 12px); padding: var(--mp-spacing-4); background: var(--mp-background-neutral, #fff); }
.cw-email__row { margin: 0 0 var(--mp-spacing-1); font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); }
.cw-email__k { display: inline-block; min-width: 56px; color: var(--mp-text-secondary); font-weight: var(--mp-font-weights-semi-bold); }
.cw-email__body { margin: var(--mp-spacing-3) 0 0; padding-top: var(--mp-spacing-3); border-top: 1px solid var(--mp-border-default); font-family: inherit; font-size: var(--mp-font-sizes-md); line-height: var(--mp-line-heights-md, 20px); color: var(--mp-text-default); white-space: pre-wrap; }
.cw-conn-lead { margin-bottom: var(--mp-spacing-4); }
.cw-back { display: inline-flex; align-items: center; gap: 4px; background: none; border: none; cursor: pointer; color: var(--mp-text-secondary); font-size: var(--mp-font-sizes-md); font-family: inherit; padding: 0; margin-bottom: var(--mp-spacing-4); }
.cw-back:hover { color: var(--mp-text-default); }
.cw-run { display: grid; grid-template-columns: minmax(0, 1fr) 320px; gap: var(--mp-spacing-4); align-items: start; }
.cw-run--single { grid-template-columns: minmax(0, 1fr) 320px; }
.cw-run__head { display: flex; align-items: flex-start; justify-content: space-between; gap: var(--mp-spacing-4); }
.cw-run__title { margin: 0 0 4px; font-size: var(--mp-font-sizes-xl, 20px); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-metric { margin: var(--mp-spacing-4) 0 0; font-size: var(--mp-font-sizes-2xl, 24px); font-weight: var(--mp-font-weights-semi-bold); letter-spacing: -0.2px; color: var(--mp-text-default); }
.cw-actions { display: flex; flex-wrap: wrap; gap: var(--mp-spacing-2); margin-top: var(--mp-spacing-4); }
.cw-steps { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: var(--mp-spacing-3); }
.cw-step { display: flex; gap: var(--mp-spacing-3); align-items: flex-start; opacity: .5; transition: opacity 250ms; }
.cw-step.is-done, .cw-step.is-active { opacity: 1; }
.cw-step__dot { flex: 0 0 auto; width: 24px; height: 24px; border-radius: 999px; background: var(--mp-background-neutral-subtle, #eef0f3); display: flex; align-items: center; justify-content: center; font-size: 12px; color: var(--mp-text-secondary); }
.cw-step.is-done .cw-step__dot { background: var(--mp-background-success-subtle, #e7f4ee); color: var(--mp-text-success, #186f4a); }
.cw-step.is-active .cw-step__dot { background: var(--mp-background-information-subtle, #dbe7f4); color: var(--mp-text-link, #165082); }
.cw-step__title { margin: 0; font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-side__title { margin: 0 0 var(--mp-spacing-3); font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-sources, .cw-prepared, .cw-summary, .cw-findings { list-style: none; margin: 0; padding: 0; }
.cw-source { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-2); padding: var(--mp-spacing-2) 0; border-bottom: 1px solid var(--mp-border-default); font-size: var(--mp-font-sizes-sm); }
.cw-source:last-child { border-bottom: none; }
.cw-prepared__item { display: flex; gap: var(--mp-spacing-3); padding: var(--mp-spacing-3) 0; border-bottom: 1px solid var(--mp-border-default); }
.cw-prepared__item:last-child { border-bottom: none; }
.cw-prepared__item :deep(svg) { color: var(--mp-text-secondary); flex-shrink: 0; }
.cw-summary__row { display: flex; align-items: flex-start; justify-content: space-between; gap: var(--mp-spacing-4); padding: var(--mp-spacing-3) 0; border-bottom: 1px solid var(--mp-border-default); }
.cw-summary__row:last-child { border-bottom: none; }
.cw-summary__title { margin: 0; font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-finding { padding: var(--mp-spacing-3) 0; border-bottom: 1px solid var(--mp-border-default); }
.cw-finding:last-child { border-bottom: none; }

@media (max-width: 900px) {
  .cw-grid { grid-template-columns: 1fr; }
  .cw-run, .cw-run--single { grid-template-columns: 1fr; }
  .cw-form-row { grid-template-columns: 1fr; }
}
</style>
