<script setup lang="ts">
/**
 * Cowork — the ERP's AI co-worker. Renders inside the standard stage (white
 * main area) with the page title bar supplied by [...slug].vue.
 *
 * Built from Pixel 3 Enterprise (DT 2.4) components — MpButton, MpBadge,
 * MpTextarea, MpSelect, MpProgress, MpToggle, MpModal, MpIcon — plus the
 * established ERP enterprise-card + table conventions. Sections are chosen by the
 * Cowork level-2 submenu (ErpSidebar panel): /cowork, /cowork-tasks,
 * /cowork-schedule, /cowork-connections. Nothing bespoke.
 *
 * Cowork takes on tasks across every module (HR, Sales/CRM, WMS, Finance,
 * Production), can schedule them to recur, and works over connected products.
 * Task briefings are generated by Gemini (/api/cowork/plan), grounded on the
 * mock DB via useCoworkContext.
 */
import { ref, reactive, computed, watch, onMounted, onBeforeUnmount } from 'vue'
import {
  MpButton, MpBadge, MpIcon, MpTextarea, MpProgress, MpSpinner, MpToggle,
  MpSelect, MpPopover, MpPopoverTrigger, MpPopoverContent, MpPopoverList, MpPopoverListItem,
  MpModal, MpModalOverlay, MpModalContent, MpModalHeader, MpModalCloseButton, MpModalBody, MpModalFooter,
  MpFormControl, MpFormLabel, css, toast,
} from '@mekari/pixel3'
import ErpStatusBadge from '~/components/patterns/ErpStatusBadge.vue'
import { useCoworkContext } from '~/composables/useCoworkContext'
import { useGoogleConnect } from '~/composables/useGoogleConnect'
import { formatDateTime } from '~/utils/date'
import {
  coworkTasks, coworkSchedules, coworkConnections,
  COWORK_CATALOG, COWORK_MODULES, COWORK_BUILTIN,
  addTask, updateTask, deleteTask, getTask,
  addSchedule, toggleSchedule, deleteSchedule, setConnection,
  type CoworkTask, type CoworkModule, type CoworkCadence, type CoworkConnection,
} from '~/data/cowork'

const route = useRoute()
const router = useRouter()
const { build } = useCoworkContext()

// The active section is driven by the Cowork level-2 submenu (ErpSidebar panel):
// /cowork = Overview, /cowork/tasks, /cowork/schedule, /cowork/connections.
const section = computed(() => {
  const p = route.path
  if (p.startsWith('/cowork-tasks')) return 'Tasks'
  if (p.startsWith('/cowork-schedule')) return 'Schedule'
  if (p.startsWith('/cowork-connections')) return 'Connections'
  return 'Overview'
})

// ── Composer ─────────────────────────────────────────────────────────────────
const prompt = ref('')
// Built-in Mekari sources are always on; add any connected external ones.
const connectedApps = computed(() => [
  ...COWORK_BUILTIN,
  ...coworkConnections.filter((c) => c.connected).map((c) => c.name),
])

// ── Run workspace ────────────────────────────────────────────────────────────
interface Step { title: string; detail: string }
interface Source { name: string; detail: string }
interface SummaryItem { title: string; detail: string; priority: 'High' | 'Medium' | 'Low' }
interface Plan {
  taskTitle: string; intro: string; sources: Source[]; steps: Step[]
  findings: { title: string; detail: string }[]; metric: string
  summary: SummaryItem[]; alsoPrepared: { title: string; detail: string }[]
}

const openTaskId = ref<string | null>(null)
const openTask = computed(() => (openTaskId.value ? getTask(openTaskId.value) : null))
const plan = ref<Plan | null>(null)
const planSource = ref<'gemini' | 'fallback' | ''>('')
const runState = ref<'working' | 'completed'>('working')

const DEFAULT_STEPS: Step[] = [
  { title: 'Read task context', detail: 'Parsing your request and connected products.' },
  { title: 'Pull the relevant data', detail: 'Employees, customers, stock, invoices, work orders.' },
  { title: 'Cross-check the modules', detail: 'Reconciling figures across HR, CRM, WMS and finance.' },
  { title: 'Prioritise what matters', detail: 'Ranking risks, decisions and actions.' },
  { title: 'Build the briefing', detail: 'Writing the summary and follow-ups.' },
]
const liveSteps = ref<Step[]>(DEFAULT_STEPS)
const activeStepIndex = ref(0)
const apiDone = ref(false)
let stepTimer: ReturnType<typeof setInterval> | null = null

const progressValue = computed(() => {
  const total = liveSteps.value.length || 1
  return String(Math.min(100, Math.round((activeStepIndex.value / total) * 100)))
})

function assign(taskPrompt: string, title?: string, module?: CoworkModule) {
  const p = taskPrompt.trim()
  if (!p) return
  const task = addTask({
    title: title ?? (p.length > 52 ? p.slice(0, 50) + '…' : p),
    prompt: p,
    module: module ?? inferModule(p),
    status: 'running',
    createdAt: new Date().toISOString(),
  })
  prompt.value = ''
  startRun(task)
}

function inferModule(text: string): CoworkModule {
  const t = text.toLowerCase()
  if (/(payroll|attendance|employee|contract|resign|leave|hr\b)/.test(t)) return 'HR'
  if (/(stock|warehouse|sku|inbound|outbound|fulfil|pick|pack|cycle count)/.test(t)) return 'WMS'
  if (/(invoice|receivable|payable|bill|reconcil|cash|payment|close)/.test(t)) return 'Finance'
  if (/(work order|production|bom|manufactur)/.test(t)) return 'Production'
  if (/(order|deliver|ship)/.test(t)) return 'Sales'
  return 'CRM'
}

function startRun(task: CoworkTask) {
  openTaskId.value = task.id
  plan.value = null
  planSource.value = ''
  apiDone.value = false
  runState.value = 'working'
  liveSteps.value = DEFAULT_STEPS
  activeStepIndex.value = 0
  if (stepTimer) clearInterval(stepTimer)
  stepTimer = setInterval(() => {
    if (activeStepIndex.value < liveSteps.value.length) activeStepIndex.value += 1
    maybeComplete()
  }, 1400)
  fetchPlan(task)
}

async function fetchPlan(task: CoworkTask) {
  try {
    const res = await $fetch<{ plan: Plan; source: 'gemini' | 'fallback' }>('/api/cowork/plan', {
      method: 'POST',
      body: { task: task.prompt, context: build() },
    })
    plan.value = res.plan
    planSource.value = res.source
    if (res.plan?.steps?.length) liveSteps.value = res.plan.steps
  } catch {
    planSource.value = 'fallback'
  } finally {
    apiDone.value = true
    maybeComplete()
  }
}

function maybeComplete() {
  if (apiDone.value && plan.value && activeStepIndex.value >= liveSteps.value.length) {
    if (stepTimer) { clearInterval(stepTimer); stepTimer = null }
    setTimeout(finishRun, 600)
  }
}
function finishRun() {
  if (!openTask.value || !plan.value) return
  runState.value = 'completed'
  updateTask(openTask.value.id, {
    status: 'completed',
    completedAt: new Date().toISOString(),
    metric: plan.value.metric,
    planJson: JSON.stringify(plan.value),
  })
}

// Reopen a finished task's cached briefing without re-running.
function openTaskDetail(task: CoworkTask) {
  openTaskId.value = task.id
  if (task.status === 'completed' && task.planJson) {
    plan.value = JSON.parse(task.planJson) as Plan
    planSource.value = 'gemini'
    runState.value = 'completed'
  } else {
    startRun(task)
  }
}

function backToIndex() {
  if (stepTimer) { clearInterval(stepTimer); stepTimer = null }
  openTaskId.value = null
  plan.value = null
}
function rerun() { if (openTask.value) startRun(openTask.value) }
function removeTask(id: string) {
  deleteTask(id)
  toast.notify({ variant: 'success', title: 'Task deleted' })
}

// ── Overview data ────────────────────────────────────────────────────────────
const moduleFilter = ref<CoworkModule | ''>('')
const suggested = computed(() =>
  moduleFilter.value ? COWORK_CATALOG.filter((c) => c.module === moduleFilter.value) : COWORK_CATALOG,
)
const recentTasks = computed(() => coworkTasks.slice(0, 5))

function statusProps(s: CoworkTask['status']) {
  if (s === 'running') return { status: 'in progress', label: 'Running' }
  if (s === 'completed') return { status: 'completed', label: 'Completed' }
  if (s === 'failed') return { status: 'failed', label: 'Failed' }
  return { status: 'draft', label: 'Scheduled' }
}

// ── Schedule ─────────────────────────────────────────────────────────────────
const scheduleOpen = ref(false)
const schedTaskTitle = ref('')
const schedCadence = ref<CoworkCadence>('Weekly')
const schedTime = ref('08:00')
const schedError = ref('')
function openSchedule() {
  schedTaskTitle.value = ''
  schedCadence.value = 'Weekly'
  schedTime.value = '08:00'
  schedError.value = ''
  scheduleOpen.value = true
}
function saveSchedule() {
  const cat = COWORK_CATALOG.find((c) => c.title === schedTaskTitle.value)
  if (!cat) { schedError.value = 'Select a task to schedule'; return }
  const nextRun = schedCadence.value === 'Daily' ? `Tomorrow · ${schedTime.value}`
    : schedCadence.value === 'Weekly' ? `Next Mon · ${schedTime.value}`
    : `1st of month · ${schedTime.value}`
  addSchedule({ title: cat.title, prompt: cat.prompt, module: cat.module, cadence: schedCadence.value, time: schedTime.value, nextRun, enabled: true })
  scheduleOpen.value = false
  toast.notify({ variant: 'success', title: 'Task scheduled' })
}

// ── Connections ──────────────────────────────────────────────────────────────
const google = useGoogleConnect()
const connecting = ref('')                          // id currently authorising
const connError = reactive<Record<string, string>>({})   // inline error per card
const connSample = reactive<Record<string, string>>({})  // live proof per card (e.g. email)

async function connectGoogle(c: CoworkConnection) {
  connError[c.id] = ''
  if (!google.isConfigured.value) {
    connError[c.id] = 'Google client ID not configured yet (NUXT_PUBLIC_GOOGLE_CLIENT_ID).'
    return
  }
  connecting.value = c.id
  try {
    const { sample } = await google.connect(c.scope!)
    setConnection(c.id, true)
    if (sample) connSample[c.id] = sample
    toast.notify({ variant: 'success', title: `${c.name} connected` })
  } catch (e: any) {
    connError[c.id] = e?.message === 'Google client ID not configured'
      ? 'Google client ID not configured yet.'
      : 'Could not connect. Please try again.'
  } finally {
    connecting.value = ''
  }
}
function disconnectConnection(c: CoworkConnection) {
  if (c.provider === 'google' && c.scope) google.disconnect(c.scope)
  delete connSample[c.id]
  setConnection(c.id, false)
  toast.notify({ variant: 'success', title: `${c.name} disconnected` })
}
function connectFake(c: CoworkConnection) {
  setConnection(c.id, true)
  toast.notify({ variant: 'success', title: `${c.name} connected` })
}
function addConnection() { toast.notify({ variant: 'info', title: 'Browse the connections marketplace — coming soon' }) }

// Leaving a section (clicking a submenu item) closes any open task workspace.
watch(() => route.path, (n, o) => { if (openTaskId.value && n !== o) backToIndex() })

onMounted(() => {
  const q = route.query
  if (typeof q.task === 'string' && q.task.trim() && q.run === '1') {
    assign(q.task)
    // Strip task/run from the URL; the workspace stays open via openTask.
    router.replace({ path: '/cowork', query: {} })
  }
})
onBeforeUnmount(() => { if (stepTimer) clearInterval(stepTimer) })
</script>

<template>
  <div class="cowork">
    <!-- ══ RUN WORKSPACE ══ -->
    <template v-if="openTask">
      <button class="cw-back" type="button" @click="backToIndex">
        <MpIcon name="chevrons-left" size="sm" /> All tasks
      </button>

      <!-- Working -->
      <div v-if="runState === 'working'" class="cw-run">
        <section class="cw-card cw-card--main">
          <header class="cw-run__head">
            <div>
              <h2 class="cw-run__title">{{ plan?.taskTitle ?? openTask.title }}</h2>
              <p class="cw-muted">{{ plan?.intro ?? 'Cowork is reviewing your ERP data and identifying what needs your attention.' }}</p>
            </div>
            <ErpStatusBadge status="in progress" label="Running" badge-for="additionalInformation" />
          </header>
          <MpProgress :value="progressValue" size="sm" color="positive" :class="css({ marginTop: '16px' })" />
          <p class="cw-eyebrow cw-mt-24">What Cowork is doing</p>
          <ul class="cw-steps">
            <li v-for="(s, i) in liveSteps" :key="s.title + i" class="cw-step" :class="{ 'is-done': i < activeStepIndex, 'is-active': i === activeStepIndex }">
              <span class="cw-step__dot"><MpIcon v-if="i < activeStepIndex" name="check" size="sm" /><template v-else>{{ i + 1 }}</template></span>
              <div>
                <p class="cw-step__title">{{ s.title }}</p>
                <p class="cw-muted">{{ s.detail }}</p>
              </div>
            </li>
          </ul>
        </section>
        <aside class="cw-card cw-card--side">
          <p class="cw-side__title">Sources being used</p>
          <ul class="cw-sources">
            <li v-for="s in (plan?.sources ?? [])" :key="s.name" class="cw-source"><span>{{ s.name }}</span><span class="cw-muted">{{ s.detail }}</span></li>
            <li v-if="!plan" class="cw-source"><span class="cw-muted">Gathering sources…</span><MpSpinner size="sm" /></li>
          </ul>
        </aside>
      </div>

      <!-- Completed briefing -->
      <div v-else class="cw-run cw-run--single">
        <section class="cw-card cw-card--main">
          <header class="cw-run__head">
            <div>
              <h2 class="cw-run__title">{{ plan?.taskTitle }}</h2>
              <p class="cw-muted">{{ plan?.intro }}</p>
            </div>
            <ErpStatusBadge status="completed" badge-for="additionalInformation" />
          </header>
          <p class="cw-metric">{{ plan?.metric }}</p>
          <div class="cw-actions">
            <MpButton is-rounded variant="primary" @click="toast.notify({ variant: 'success', title: 'Action items created' })">Create action items</MpButton>
            <MpButton is-rounded variant="secondary" @click="toast.notify({ variant: 'info', title: 'Shared' })">Share briefing</MpButton>
            <MpButton is-rounded variant="ghost" @click="rerun">Run again</MpButton>
          </div>

          <p class="cw-eyebrow cw-mt-24">Executive summary</p>
          <ul class="cw-summary">
            <li v-for="(s, i) in (plan?.summary ?? [])" :key="s.title" class="cw-summary__row">
              <div>
                <p class="cw-summary__title">{{ i + 1 }}. {{ s.title }}</p>
                <p class="cw-muted">{{ s.detail }}</p>
              </div>
              <ErpStatusBadge :status="s.priority.toLowerCase()" :label="s.priority" />
            </li>
          </ul>

          <template v-if="plan?.findings?.length">
            <p class="cw-eyebrow cw-mt-24">Key findings</p>
            <ul class="cw-findings">
              <li v-for="f in plan.findings" :key="f.title" class="cw-finding">
                <p class="cw-summary__title">{{ f.title }}</p><p class="cw-muted">{{ f.detail }}</p>
              </li>
            </ul>
          </template>
        </section>

        <aside class="cw-card cw-card--side">
          <p class="cw-side__title">Cowork also prepared</p>
          <ul class="cw-prepared">
            <li v-for="a in (plan?.alsoPrepared ?? [])" :key="a.title" class="cw-prepared__item">
              <MpIcon name="document" size="md" />
              <div><p class="cw-summary__title">{{ a.title }}</p><p class="cw-muted">{{ a.detail }}</p></div>
            </li>
          </ul>
          <p class="cw-side__title cw-mt-24">Sources used</p>
          <ul class="cw-sources">
            <li v-for="s in (plan?.sources ?? [])" :key="s.name" class="cw-source"><span>{{ s.name }}</span><span class="cw-muted">{{ s.detail }}</span></li>
          </ul>
        </aside>
      </div>
    </template>

    <!-- ══ INDEX (section chosen by the page-tab bar rendered outside the stage) ══ -->
    <template v-else>
        <!-- ── Overview ── -->
        <section v-if="section === 'Overview'">
          <section class="cw-card cw-composer">
            <MpTextarea id="cw-prompt" v-model="prompt" is-full-width :rows="3"
              placeholder="Assign a task to Cowork — it works across HR, Sales, CRM, WMS, Finance and Production…" />
            <div class="cw-composer__foot">
              <div class="cw-conn-chips">
                <span v-for="c in connectedApps" :key="c" class="cw-conn-chip"><MpIcon name="check" size="sm" /> {{ c }}</span>
              </div>
              <MpButton is-rounded variant="primary" @click="assign(prompt)">Assign task</MpButton>
            </div>
          </section>

          <div class="cw-section-head">
            <h3 class="cw-h3">Suggested for you</h3>
            <MpPopover id="cw-module-filter" is-close-on-select>
              <MpPopoverTrigger>
                <MpSelect id="cw-module-select" placeholder="All modules" :model-value="moduleFilter" is-clearable
                  :class="css({ width: '170px' })" @mousedown.prevent @clear="moduleFilter = ''">
                  <option v-if="moduleFilter" :value="moduleFilter">{{ moduleFilter }}</option>
                </MpSelect>
              </MpPopoverTrigger>
              <MpPopoverContent :class="css({ minWidth: '170px' })">
                <MpPopoverList>
                  <MpPopoverListItem v-for="m in COWORK_MODULES" :key="m" :is-active="m === moduleFilter" @click="moduleFilter = m">{{ m }}</MpPopoverListItem>
                </MpPopoverList>
              </MpPopoverContent>
            </MpPopover>
          </div>
          <div class="cw-grid">
            <button v-for="c in suggested" :key="c.title" class="cw-card cw-card--click" type="button" @click="assign(c.prompt, c.title, c.module)">
              <MpBadge for="additionalInformation" type="announcement" size="sm">{{ c.module }}</MpBadge>
              <h4 class="cw-card__title">{{ c.title }}</h4>
              <p class="cw-muted">{{ c.desc }}</p>
              <span class="cw-card__cta">Run task <MpIcon name="arrows-right" size="sm" /></span>
            </button>
          </div>

          <div class="cw-section-head">
            <h3 class="cw-h3">Recent tasks</h3>
            <MpButton is-rounded variant="tertiary" size="sm" @click="router.push('/cowork-tasks')">View all</MpButton>
          </div>
          <div class="cw-list">
            <button v-for="t in recentTasks" :key="t.id" class="cw-list-row" type="button" @click="openTaskDetail(t)">
              <div class="cw-list-row__main">
                <MpBadge for="additionalInformation" type="announcement" size="sm">{{ t.module }}</MpBadge>
                <span class="cw-list-row__title">{{ t.title }}</span>
              </div>
              <div class="cw-list-row__meta">
                <span class="cw-muted">{{ t.metric ?? '—' }}</span>
                <ErpStatusBadge v-bind="statusProps(t.status)" />
              </div>
            </button>
            <p v-if="!recentTasks.length" class="cw-empty">No tasks yet — assign one above.</p>
          </div>
        </section>

        <!-- ── Tasks ── -->
        <section v-else-if="section === 'Tasks'">
          <div class="cw-table-wrap">
            <table class="cw-table">
              <thead>
                <tr><th>Task</th><th>Module</th><th>Status</th><th>Created</th><th>Result</th><th class="cw-th-actions" /></tr>
              </thead>
              <tbody>
                <tr v-for="t in coworkTasks" :key="t.id">
                  <td>
                    <span class="cw-cell-link" @click="openTaskDetail(t)">{{ t.title }}</span>
                    <span class="cw-cell-sub">{{ t.id }}</span>
                  </td>
                  <td><MpBadge for="additionalInformation" type="announcement" size="sm">{{ t.module }}</MpBadge></td>
                  <td><ErpStatusBadge v-bind="statusProps(t.status)" /></td>
                  <td>{{ formatDateTime(t.createdAt) }}</td>
                  <td class="cw-muted">{{ t.metric ?? '—' }}</td>
                  <td class="cw-td-actions" @click.stop>
                    <MpPopover :id="`cw-task-${t.id}`" is-close-on-select use-portal :is-keep-alive="false" placement="bottom-end">
                      <MpPopoverTrigger>
                        <button class="cw-kebab" type="button" aria-label="Actions"><MpIcon name="menu-kebab" size="md" /></button>
                      </MpPopoverTrigger>
                      <MpPopoverContent :class="css({ minWidth: '160px' })">
                        <MpPopoverList>
                          <MpPopoverListItem @click="openTaskDetail(t)">Open</MpPopoverListItem>
                          <MpPopoverListItem @click="removeTask(t.id)">Delete</MpPopoverListItem>
                        </MpPopoverList>
                      </MpPopoverContent>
                    </MpPopover>
                  </td>
                </tr>
                <tr v-if="!coworkTasks.length"><td colspan="6" class="cw-empty">No tasks yet.</td></tr>
              </tbody>
            </table>
          </div>
        </section>

        <!-- ── Schedule ── -->
        <section v-else-if="section === 'Schedule'">
          <div class="cw-section-head">
            <p class="cw-muted">Cowork runs these automatically and drops the briefing in your inbox.</p>
            <MpButton is-rounded variant="primary" @click="openSchedule"><MpIcon name="add" size="sm" /> Schedule a task</MpButton>
          </div>
          <div class="cw-table-wrap">
            <table class="cw-table">
              <thead>
                <tr><th>Task</th><th>Module</th><th>Cadence</th><th>Next run</th><th>Active</th><th class="cw-th-actions" /></tr>
              </thead>
              <tbody>
                <tr v-for="s in coworkSchedules" :key="s.id">
                  <td><span class="cw-list-row__title">{{ s.title }}</span></td>
                  <td><MpBadge for="additionalInformation" type="announcement" size="sm">{{ s.module }}</MpBadge></td>
                  <td>{{ s.cadence }} · {{ s.time }}</td>
                  <td>{{ s.nextRun }}</td>
                  <td><MpToggle :is-checked="s.enabled" :aria-label="`Toggle ${s.title}`" @update:is-checked="(v: boolean) => toggleSchedule(s.id, v)" /></td>
                  <td class="cw-td-actions">
                    <button class="cw-kebab" type="button" aria-label="Delete schedule" @click="deleteSchedule(s.id)"><MpIcon name="delete" size="md" /></button>
                  </td>
                </tr>
                <tr v-if="!coworkSchedules.length"><td colspan="6" class="cw-empty">No scheduled tasks.</td></tr>
              </tbody>
            </table>
          </div>
        </section>

        <!-- ── Connections ── -->
        <section v-else-if="section === 'Connections'">
          <div class="cw-section-head">
            <p class="cw-muted">Cowork works over the products and data sources you connect.</p>
            <MpButton is-rounded variant="secondary" @click="addConnection"><MpIcon name="add" size="sm" /> Add connection</MpButton>
          </div>
          <div class="cw-grid">
            <div v-for="c in coworkConnections" :key="c.id" class="cw-card cw-conn-card">
              <div class="cw-conn-card__top">
                <div class="cw-conn-logo">{{ c.name.slice(0, 2).toUpperCase() }}</div>
                <div class="cw-conn-badges">
                  <MpBadge v-if="c.provider === 'google'" for="additionalInformation" type="information" size="sm">Live</MpBadge>
                  <ErpStatusBadge v-if="c.connected" status="active" label="Connected" />
                </div>
              </div>
              <h4 class="cw-card__title">{{ c.name }}</h4>
              <p class="cw-muted">{{ c.category }} · {{ c.detail }}</p>
              <p v-if="connSample[c.id]" class="cw-conn-sample"><MpIcon name="check" size="sm" /> {{ connSample[c.id] }}</p>
              <p v-if="connError[c.id]" class="cw-form-error">{{ connError[c.id] }}</p>
              <div class="cw-conn-card__foot">
                <MpButton v-if="c.connected" is-rounded variant="ghost" size="sm" @click="disconnectConnection(c)">Disconnect</MpButton>
                <MpButton v-else-if="c.provider === 'google'" is-rounded variant="secondary" size="sm" :is-loading="connecting === c.id" @click="connectGoogle(c)">Connect</MpButton>
                <MpButton v-else is-rounded variant="secondary" size="sm" @click="connectFake(c)">Connect</MpButton>
              </div>
            </div>
          </div>
        </section>
    </template>

    <!-- Schedule modal -->
    <MpModal id="cw-schedule-modal" :is-open="scheduleOpen" size="md" is-close-on-esc is-close-on-overlay-click :is-keep-alive="false" @close="scheduleOpen = false">
      <MpModalOverlay />
      <MpModalContent>
        <MpModalHeader>Schedule a task</MpModalHeader>
        <MpModalCloseButton @click="scheduleOpen = false" />
        <MpModalBody>
          <MpFormControl :is-required="true" :is-error="!!schedError" :class="css({ marginBottom: '16px' })">
            <MpFormLabel>Task</MpFormLabel>
            <MpPopover id="cw-sched-task" is-close-on-select>
              <MpPopoverTrigger>
                <MpSelect id="cw-sched-task-sel" placeholder="Select a task" :model-value="schedTaskTitle" is-full-width @mousedown.prevent>
                  <option v-if="schedTaskTitle" :value="schedTaskTitle">{{ schedTaskTitle }}</option>
                </MpSelect>
              </MpPopoverTrigger>
              <MpPopoverContent :class="css({ minWidth: '360px', maxHeight: '280px', overflowY: 'auto' })">
                <MpPopoverList>
                  <MpPopoverListItem v-for="c in COWORK_CATALOG" :key="c.title" :is-active="c.title === schedTaskTitle" @click="schedTaskTitle = c.title; schedError = ''">
                    {{ c.title }} · {{ c.module }}
                  </MpPopoverListItem>
                </MpPopoverList>
              </MpPopoverContent>
            </MpPopover>
          </MpFormControl>
          <div class="cw-form-row">
            <MpFormControl>
              <MpFormLabel>Cadence</MpFormLabel>
              <MpPopover id="cw-sched-cadence" is-close-on-select>
                <MpPopoverTrigger>
                  <MpSelect id="cw-sched-cadence-sel" :model-value="schedCadence" is-full-width @mousedown.prevent>
                    <option :value="schedCadence">{{ schedCadence }}</option>
                  </MpSelect>
                </MpPopoverTrigger>
                <MpPopoverContent :class="css({ minWidth: '160px' })">
                  <MpPopoverList>
                    <MpPopoverListItem v-for="c in ['Daily','Weekly','Monthly']" :key="c" :is-active="c === schedCadence" @click="schedCadence = c as CoworkCadence">{{ c }}</MpPopoverListItem>
                  </MpPopoverList>
                </MpPopoverContent>
              </MpPopover>
            </MpFormControl>
            <MpFormControl>
              <MpFormLabel>Time</MpFormLabel>
              <MpPopover id="cw-sched-time" is-close-on-select>
                <MpPopoverTrigger>
                  <MpSelect id="cw-sched-time-sel" :model-value="schedTime" is-full-width @mousedown.prevent>
                    <option :value="schedTime">{{ schedTime }}</option>
                  </MpSelect>
                </MpPopoverTrigger>
                <MpPopoverContent :class="css({ minWidth: '120px', maxHeight: '240px', overflowY: 'auto' })">
                  <MpPopoverList>
                    <MpPopoverListItem v-for="h in ['06:00','07:00','07:30','08:00','09:00','12:00','17:00','18:00']" :key="h" :is-active="h === schedTime" @click="schedTime = h">{{ h }}</MpPopoverListItem>
                  </MpPopoverList>
                </MpPopoverContent>
              </MpPopover>
            </MpFormControl>
          </div>
          <p v-if="schedError" class="cw-form-error">{{ schedError }}</p>
        </MpModalBody>
        <MpModalFooter>
          <MpButton is-rounded variant="ghost" @click="scheduleOpen = false">Cancel</MpButton>
          <MpButton is-rounded variant="primary" @click="saveSchedule">Schedule</MpButton>
        </MpModalFooter>
      </MpModalContent>
    </MpModal>
  </div>
</template>

<style scoped>
.cowork { display: flex; flex-direction: column; }

/* Enterprise card — border 1px, no drop-shadow (surface rule). */
.cw-card { border: 1px solid var(--mp-border-default, #e3e7e9); border-radius: var(--mp-radii-xl, 12px); background: var(--mp-background-neutral, #fff); padding: var(--mp-spacing-5, 20px); }
.cw-muted { margin: 0; color: var(--mp-text-secondary, #3a4749); font-size: var(--mp-font-sizes-sm, 12px); line-height: var(--mp-line-heights-sm, 16px); }
.cw-eyebrow { margin: 0 0 var(--mp-spacing-3); font-size: var(--mp-font-sizes-sm); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-h3 { margin: 0; font-size: var(--mp-font-sizes-lg, 16px); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-mt-24 { margin-top: var(--mp-spacing-6, 24px); }

/* Composer */
.cw-composer { margin-top: 0; }
.cw-composer__foot { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); margin-top: var(--mp-spacing-3); }
.cw-conn-chips { display: flex; flex-wrap: wrap; gap: var(--mp-spacing-2); }
.cw-conn-chip { display: inline-flex; align-items: center; gap: 4px; font-size: var(--mp-font-sizes-sm); color: var(--mp-text-secondary); background: var(--mp-background-neutral-subtle, #f8f9f9); border-radius: var(--mp-radii-full, 999px); padding: 3px 10px; }
.cw-conn-chip :deep(svg) { color: var(--mp-text-success, #186f4a); }

/* Section head */
.cw-section-head { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); margin: var(--mp-spacing-8) 0 var(--mp-spacing-4); }

/* Card grid */
.cw-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: var(--mp-spacing-4); }
.cw-card--click { text-align: left; cursor: pointer; display: flex; flex-direction: column; gap: var(--mp-spacing-2); font-family: inherit; transition: border-color 100ms; }
.cw-card--click:hover { border-color: var(--mp-border-bold, #8c9596); }
.cw-card__title { margin: 4px 0 0; font-size: var(--mp-font-sizes-md, 14px); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-card__cta { margin-top: auto; display: inline-flex; align-items: center; gap: 4px; font-size: var(--mp-font-sizes-sm); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-link, #165082); padding-top: var(--mp-spacing-2); }

/* Recent list */
.cw-list { display: flex; flex-direction: column; border: 1px solid var(--mp-border-default); border-radius: var(--mp-radii-xl, 12px); overflow: hidden; }
.cw-list-row { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); padding: var(--mp-spacing-3) var(--mp-spacing-4); background: var(--mp-background-neutral, #fff); border: none; border-top: 1px solid var(--mp-border-default); cursor: pointer; font-family: inherit; text-align: left; }
.cw-list-row:first-child { border-top: none; }
.cw-list-row:hover { background: var(--mp-background-neutral-subtle, #f8f9f9); }
.cw-list-row__main { display: flex; align-items: center; gap: var(--mp-spacing-3); min-width: 0; }
.cw-list-row__title { font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); font-weight: var(--mp-font-weights-semi-bold); }
.cw-list-row__meta { display: flex; align-items: center; gap: var(--mp-spacing-4); flex-shrink: 0; }
.cw-empty { padding: var(--mp-spacing-6); text-align: center; color: var(--mp-text-secondary); font-size: var(--mp-font-sizes-sm); margin: 0; }

/* Table (ERP convention: no outer border, header fill, row bottom-border) */
.cw-table-wrap { overflow-x: auto; }
.cw-table { width: 100%; border-collapse: collapse; }
.cw-table thead th { text-align: left; padding: var(--mp-spacing-2) var(--mp-spacing-3); background: var(--mp-background-neutral-subtle, #f8f9f9); font-size: var(--mp-font-sizes-sm); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-secondary); white-space: nowrap; }
.cw-table tbody td { padding: var(--mp-spacing-2) var(--mp-spacing-3); border-bottom: 1px solid var(--mp-border-default); font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); vertical-align: middle; }
.cw-th-actions, .cw-td-actions { width: 52px; text-align: right; }
.cw-cell-link { color: var(--mp-text-link, #165082); cursor: pointer; font-weight: var(--mp-font-weights-semi-bold); }
.cw-cell-link:hover { text-decoration: underline; }
.cw-cell-sub { display: block; font-size: var(--mp-font-sizes-sm); color: var(--mp-text-secondary); }
.cw-kebab { display: inline-flex; align-items: center; justify-content: center; width: 32px; height: 32px; border: none; background: none; border-radius: var(--mp-radii-md); color: var(--mp-text-secondary); cursor: pointer; }
.cw-kebab:hover { background: var(--mp-background-neutral-subtle); color: var(--mp-text-default); }

/* Connections */
.cw-conn-card { display: flex; flex-direction: column; gap: var(--mp-spacing-2); }
.cw-conn-card__top { display: flex; align-items: center; justify-content: space-between; }
.cw-conn-badges { display: inline-flex; align-items: center; gap: var(--mp-spacing-2); }
.cw-conn-sample { display: inline-flex; align-items: center; gap: 4px; margin: 0; font-size: var(--mp-font-sizes-sm); color: var(--mp-text-success, #186f4a); }
.cw-conn-sample :deep(svg) { color: var(--mp-text-success, #186f4a); }
.cw-conn-logo { width: 40px; height: 40px; border-radius: var(--mp-radii-md, 8px); background: var(--mp-background-neutral-subtle, #f1f3f4); display: flex; align-items: center; justify-content: center; font-size: 13px; font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-secondary); }
.cw-conn-card__foot { margin-top: var(--mp-spacing-3); }

/* Form row */
.cw-form-row { display: grid; grid-template-columns: 1fr 1fr; gap: var(--mp-spacing-4); }
.cw-form-error { margin: var(--mp-spacing-2) 0 0; color: var(--mp-text-danger, #a8352d); font-size: var(--mp-font-sizes-sm); }

/* Run workspace */
.cw-back { display: inline-flex; align-items: center; gap: 4px; background: none; border: none; cursor: pointer; color: var(--mp-text-secondary); font-size: var(--mp-font-sizes-md); font-family: inherit; padding: 0; margin-bottom: var(--mp-spacing-4); }
.cw-back:hover { color: var(--mp-text-default); }
.cw-run { display: grid; grid-template-columns: minmax(0, 1fr) 320px; gap: var(--mp-spacing-4); align-items: start; }
.cw-run--single { grid-template-columns: minmax(0, 1fr) 320px; }
.cw-run__head { display: flex; align-items: flex-start; justify-content: space-between; gap: var(--mp-spacing-4); }
.cw-run__title { margin: 0 0 4px; font-size: var(--mp-font-sizes-xl, 20px); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-metric { margin: var(--mp-spacing-4) 0 0; font-size: var(--mp-font-sizes-2xl, 24px); font-weight: var(--mp-font-weights-semi-bold); letter-spacing: -0.2px; color: var(--mp-text-default); }
.cw-actions { display: flex; flex-wrap: wrap; gap: var(--mp-spacing-2); margin-top: var(--mp-spacing-4); }
.cw-steps { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: var(--mp-spacing-3); }
.cw-step { display: flex; gap: var(--mp-spacing-3); align-items: flex-start; opacity: .5; transition: opacity 250ms; }
.cw-step.is-done, .cw-step.is-active { opacity: 1; }
.cw-step__dot { flex: 0 0 auto; width: 24px; height: 24px; border-radius: 999px; background: var(--mp-background-neutral-subtle, #eef0f3); display: flex; align-items: center; justify-content: center; font-size: 12px; color: var(--mp-text-secondary); }
.cw-step.is-done .cw-step__dot { background: var(--mp-background-success-subtle, #e7f4ee); color: var(--mp-text-success, #186f4a); }
.cw-step.is-active .cw-step__dot { background: var(--mp-background-information-subtle, #dbe7f4); color: var(--mp-text-link, #165082); }
.cw-step__title { margin: 0; font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-side__title { margin: 0 0 var(--mp-spacing-3); font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-sources, .cw-prepared, .cw-summary, .cw-findings { list-style: none; margin: 0; padding: 0; }
.cw-source { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-2); padding: var(--mp-spacing-2) 0; border-bottom: 1px solid var(--mp-border-default); font-size: var(--mp-font-sizes-sm); }
.cw-source:last-child { border-bottom: none; }
.cw-prepared__item { display: flex; gap: var(--mp-spacing-3); padding: var(--mp-spacing-3) 0; border-bottom: 1px solid var(--mp-border-default); }
.cw-prepared__item:last-child { border-bottom: none; }
.cw-prepared__item :deep(svg) { color: var(--mp-text-secondary); flex-shrink: 0; }
.cw-summary__row { display: flex; align-items: flex-start; justify-content: space-between; gap: var(--mp-spacing-4); padding: var(--mp-spacing-3) 0; border-bottom: 1px solid var(--mp-border-default); }
.cw-summary__row:last-child { border-bottom: none; }
.cw-summary__title { margin: 0; font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-finding { padding: var(--mp-spacing-3) 0; border-bottom: 1px solid var(--mp-border-default); }
.cw-finding:last-child { border-bottom: none; }

@media (max-width: 900px) {
  .cw-grid { grid-template-columns: 1fr; }
  .cw-run, .cw-run--single { grid-template-columns: 1fr; }
  .cw-form-row { grid-template-columns: 1fr; }
}
</style>
