<script setup lang="ts">
/**
 * Cowork — the ERP's AI co-worker. Renders inside the standard stage (white
 * main area) with the page title bar supplied by [...slug].vue.
 *
 * Built from Pixel 3 Enterprise (DT 2.4) components — MpButton, MpBadge,
 * MpTextarea, MpSelect, MpProgress, MpToggle, MpModal, MpIcon — plus the
 * established ERP enterprise-card + table conventions. Sections are chosen by the
 * Cowork level-2 submenu (ErpSidebar panel): /cowork, /cowork-tasks,
 * /cowork-schedule, /cowork-connections. Nothing bespoke.
 *
 * Cowork takes on tasks across every module (HR, Sales/CRM, WMS, Finance,
 * Production), can schedule them to recur, and works over connected products.
 * Task briefings are generated by Gemini (/api/cowork/plan), grounded on the
 * mock DB via useCoworkContext.
 */
import { h, ref, reactive, computed, watch, onMounted, onBeforeUnmount } from 'vue'
import {
  MpButton, MpBadge, MpIcon, MpProgress, MpSpinner, MpToggle, MpSkeleton, MpSelect,
  MpPopover, MpPopoverTrigger, MpPopoverContent, MpPopoverList, MpPopoverListItem,
  css, toast,
} from '@mekari/pixel3'
import ErpStatusBadge from '~/components/patterns/ErpStatusBadge.vue'
import ErpPagination from '~/components/patterns/ErpPagination.vue'
import { getEmployee } from '~/data'
import { useCoworkContext } from '~/composables/useCoworkContext'
import { useGoogleConnect } from '~/composables/useGoogleConnect'
import { formatDateTime } from '~/utils/date'
import {
  coworkTasks, coworkSchedules, coworkConnections,
  COWORK_CATALOG, COWORK_BUILTIN,
  addTask, updateTask, deleteTask, getTask,
  addSchedule, updateSchedule, toggleSchedule, deleteSchedule, setConnection,
  type CoworkTask, type CoworkModule, type CoworkCadence, type CoworkConnection,
} from '~/data/cowork'

const route = useRoute()
const router = useRouter()
const { build } = useCoworkContext()

// First-load skeleton (ERP guideline: solid rows, ~1.2s) for Tasks + Schedule.
const loading = ref(true)
onMounted(() => { setTimeout(() => { loading.value = false }, 1200) })

// ── Tasks table state — status filter (left) + search (right) + pagination ────
const taskStatusOptions = [
  { value: 'running',   label: 'Running' },
  { value: 'completed', label: 'Completed' },
  { value: 'failed',    label: 'Failed' },
  { value: 'scheduled', label: 'Scheduled' },
]
const taskSource = computed(() => coworkTasks)
const {
  search: taskSearch, statusFilter: taskStatus, currentPage: taskPage, perPage: taskPerPage,
  paginated: taskRows, total: taskTotal, setPage: taskSetPage, setPerPage: taskSetPerPage,
} = useTableState<CoworkTask>(taskSource, {
  perPage: 10,
  filterFn: (t, s, status) =>
    (!s || t.title.toLowerCase().includes(s) || t.id.toLowerCase().includes(s) || t.module.toLowerCase().includes(s))
    && (!status || t.status === status),
})
const taskStatusLabel = computed(() => taskStatusOptions.find((o) => o.value === taskStatus.value)?.label ?? '')

// ── Schedule table state — pagination only ────────────────────────────────────
const schedSource = computed(() => coworkSchedules)
const {
  currentPage: schedPage, perPage: schedPerPage, paginated: schedRows, total: schedTotal,
  setPage: schedSetPage, setPerPage: schedSetPerPage,
} = useTableState<typeof coworkSchedules[number]>(schedSource, { perPage: 10, filterFn: () => true })

// Gemini mark — a 4-point star with Google's multi-hue gradient (not the Airene
// purple sparkle) for the model picker.
const GeminiMark = (props: { size?: number }) =>
  h('svg', { width: props.size ?? 16, height: props.size ?? 16, viewBox: '0 0 24 24', fill: 'none', 'aria-hidden': 'true' }, [
    h('defs', [
      h('linearGradient', { id: 'cw-gemini', x1: '2', y1: '3', x2: '22', y2: '21', gradientUnits: 'userSpaceOnUse' }, [
        h('stop', { offset: '0', 'stop-color': '#1BA1E3' }),
        h('stop', { offset: '0.3', 'stop-color': '#5489D6' }),
        h('stop', { offset: '0.55', 'stop-color': '#9B72CB' }),
        h('stop', { offset: '0.8', 'stop-color': '#D96570' }),
        h('stop', { offset: '1', 'stop-color': '#F49C46' }),
      ]),
    ]),
    h('path', { d: 'M12 2c.3 4.9 4.8 9.4 9.7 9.7v.6C16.8 12.6 12.3 17.1 12 22h-.6c-.3-4.9-4.8-9.4-9.7-9.7v-.6C6.6 11.4 11.1 6.9 11.4 2H12z', fill: 'url(#cw-gemini)' }),
  ])

// The active section is driven by the Cowork level-2 submenu (ErpSidebar panel):
// /cowork = Overview, /cowork/tasks, /cowork/schedule, /cowork/connections.
const section = computed(() => {
  const p = route.path
  if (p.startsWith('/cowork-tasks')) return 'Tasks'
  if (p.startsWith('/cowork-schedule')) return 'Schedule'
  if (p.startsWith('/cowork-connections')) return 'Connections'
  return 'Overview'
})

// ── Composer ─────────────────────────────────────────────────────────────────
const prompt = ref('')
const promptEl = ref<HTMLTextAreaElement | null>(null)
function focusPrompt() { requestAnimationFrame(() => promptEl.value?.focus()) }
function soon(what: string) { toast.notify({ variant: 'info', title: `${what} — coming soon` }) }

// ── Run workspace ────────────────────────────────────────────────────────────
interface Step { title: string; detail: string }
interface Source { name: string; detail: string }
interface SummaryItem { title: string; detail: string; priority: 'High' | 'Medium' | 'Low' }
interface Plan {
  taskTitle: string; intro: string; sources: Source[]; steps: Step[]
  findings: { title: string; detail: string }[]; metric: string
  summary: SummaryItem[]; alsoPrepared: { title: string; detail: string }[]
}

const openTaskId = ref<string | null>(null)
const openTask = computed(() => (openTaskId.value ? getTask(openTaskId.value) : null))
const plan = ref<Plan | null>(null)
const planSource = ref<'gemini' | 'fallback' | ''>('')
const runState = ref<'working' | 'completed'>('working')

const DEFAULT_STEPS: Step[] = [
  { title: 'Read task context', detail: 'Parsing your request and connected products.' },
  { title: 'Pull the relevant data', detail: 'Employees, customers, stock, invoices, work orders.' },
  { title: 'Cross-check the modules', detail: 'Reconciling figures across HR, CRM, WMS and finance.' },
  { title: 'Prioritise what matters', detail: 'Ranking risks, decisions and actions.' },
  { title: 'Build the briefing', detail: 'Writing the summary and follow-ups.' },
]
const liveSteps = ref<Step[]>(DEFAULT_STEPS)
const activeStepIndex = ref(0)
const apiDone = ref(false)
let stepTimer: ReturnType<typeof setInterval> | null = null

const progressValue = computed(() => {
  const total = liveSteps.value.length || 1
  return String(Math.min(100, Math.round((activeStepIndex.value / total) * 100)))
})

function assign(taskPrompt: string, title?: string, module?: CoworkModule) {
  const p = taskPrompt.trim()
  if (!p) return
  const task = addTask({
    title: title ?? (p.length > 52 ? p.slice(0, 50) + '…' : p),
    prompt: p,
    module: module ?? inferModule(p),
    status: 'running',
    createdAt: new Date().toISOString(),
  })
  prompt.value = ''
  composerScheduleId.value = null
  startRun(task)
}

function inferModule(text: string): CoworkModule {
  const t = text.toLowerCase()
  if (/(payroll|attendance|employee|contract|resign|leave|hr\b)/.test(t)) return 'HR'
  if (/(stock|warehouse|sku|inbound|outbound|fulfil|pick|pack|cycle count)/.test(t)) return 'WMS'
  if (/(invoice|receivable|payable|bill|reconcil|cash|payment|close)/.test(t)) return 'Finance'
  if (/(work order|production|bom|manufactur)/.test(t)) return 'Production'
  if (/(order|deliver|ship)/.test(t)) return 'Sales'
  return 'CRM'
}

function startRun(task: CoworkTask) {
  openTaskId.value = task.id
  plan.value = null
  planSource.value = ''
  apiDone.value = false
  runState.value = 'working'
  liveSteps.value = DEFAULT_STEPS
  activeStepIndex.value = 0
  if (stepTimer) clearInterval(stepTimer)
  stepTimer = setInterval(() => {
    if (activeStepIndex.value < liveSteps.value.length) activeStepIndex.value += 1
    maybeComplete()
  }, 1400)
  fetchPlan(task)
}

async function fetchPlan(task: CoworkTask) {
  try {
    const activeSources = sources.value.filter((s) => isSourceOn(s.id)).map((s) => s.name)
    const activeOutputs = OUTPUTS.filter((o) => isOutputOn(o.id)).map((o) => o.name)
    const res = await $fetch<{ plan: Plan; source: 'gemini' | 'fallback' }>('/api/cowork/plan', {
      method: 'POST',
      body: { task: task.prompt, context: build(), model: model.value, sources: activeSources, outputs: activeOutputs },
    })
    plan.value = res.plan
    planSource.value = res.source
    if (res.plan?.steps?.length) liveSteps.value = res.plan.steps
  } catch {
    planSource.value = 'fallback'
  } finally {
    apiDone.value = true
    maybeComplete()
  }
}

function maybeComplete() {
  if (apiDone.value && plan.value && activeStepIndex.value >= liveSteps.value.length) {
    if (stepTimer) { clearInterval(stepTimer); stepTimer = null }
    setTimeout(finishRun, 600)
  }
}
function finishRun() {
  if (!openTask.value || !plan.value) return
  runState.value = 'completed'
  updateTask(openTask.value.id, {
    status: 'completed',
    completedAt: new Date().toISOString(),
    metric: plan.value.metric,
    planJson: JSON.stringify(plan.value),
  })
}

// Reopen a finished task's cached briefing without re-running.
function openTaskDetail(task: CoworkTask) {
  openTaskId.value = task.id
  if (task.status === 'completed' && task.planJson) {
    plan.value = JSON.parse(task.planJson) as Plan
    planSource.value = 'gemini'
    runState.value = 'completed'
  } else {
    startRun(task)
  }
}

function backToIndex() {
  if (stepTimer) { clearInterval(stepTimer); stepTimer = null }
  openTaskId.value = null
  plan.value = null
}
function rerun() { if (openTask.value) startRun(openTask.value) }
function removeTask(id: string) {
  deleteTask(id)
  toast.notify({ variant: 'success', title: 'Task deleted' })
}

// ── Overview data ────────────────────────────────────────────────────────────
// Suggested tasks grouped by module (Finance, HR, Sales, CRM, WMS, Production).
const MODULE_ORDER: CoworkModule[] = ['Finance', 'HR', 'Sales', 'CRM', 'WMS', 'Production']
const suggestedGroups = computed(() =>
  MODULE_ORDER
    .map((m) => ({ module: m, items: COWORK_CATALOG.filter((c) => c.module === m) }))
    .filter((g) => g.items.length),
)
// Employees (Talenta HR DB) who have run a predefined task before → avatar stack.
function usedAvatars(ids?: string[]) {
  return (ids ?? []).map((id) => getEmployee(id)).filter(Boolean).slice(0, 4)
}
// Signed-in user (no auth in the prototype → Rizal Candra, EMP-0001). If they've
// already run a predefined task, the "Run task" affordance is dropped.
const CURRENT_USER_ID = 'EMP-0001'
function hasRun(item: { usedBy?: string[] }) { return !!item.usedBy?.includes(CURRENT_USER_ID) }

// ── Model picker ─────────────────────────────────────────────────────────────
const MODELS = [
  { id: 'gemini-flash-latest', label: 'Gemini Flash' },
  { id: 'gemini-pro-latest', label: 'Gemini Pro' },
  { id: 'gemini-flash-lite-latest', label: 'Gemini Flash Lite' },
]
const model = ref(MODELS[0].id)
const modelLabel = computed(() => MODELS.find((m) => m.id === model.value)?.label ?? 'Gemini Flash')

// ── Sources (which connected products Cowork may read) ───────────────────────
const sources = computed(() => [
  ...COWORK_BUILTIN.map((name) => ({ id: name, name })),
  ...coworkConnections.filter((c) => c.connected).map((c) => ({ id: c.id, name: c.name })),
])
const sourceOff = reactive<Record<string, boolean>>({})   // id → excluded
function isSourceOn(id: string) { return !sourceOff[id] }
function toggleSource(id: string, on: boolean) { sourceOff[id] = !on }
const activeSourceCount = computed(() => sources.value.filter((s) => isSourceOn(s.id)).length)

// ── Output (what Cowork should produce for the task) ─────────────────────────
const OUTPUTS = [
  { id: 'briefing', name: 'Briefing summary' },
  { id: 'action-items', name: 'Action items' },
  { id: 'email', name: 'Email draft' },
  { id: 'slack', name: 'Slack message' },
  { id: 'spreadsheet', name: 'Spreadsheet' },
  { id: 'pdf', name: 'PDF report' },
]
const outputOn = reactive<Record<string, boolean>>({ briefing: true })
function isOutputOn(id: string) { return !!outputOn[id] }
function toggleOutput(id: string, on: boolean) { outputOn[id] = on }
const activeOutputCount = computed(() => OUTPUTS.filter((o) => isOutputOn(o.id)).length)

function statusProps(s: CoworkTask['status']) {
  if (s === 'running') return { status: 'in progress', label: 'Running' }
  if (s === 'completed') return { status: 'completed', label: 'Completed' }
  if (s === 'failed') return { status: 'failed', label: 'Failed' }
  return { status: 'draft', label: 'Scheduled' }
}

// ── Schedule ─────────────────────────────────────────────────────────────────
// The task being scheduled IS the composer prompt — the popover only sets cadence
// and time. Empty prompt → just focus the composer so the user writes one.
const schedCadence = ref<CoworkCadence>('Weekly')
const schedTime = ref('08:00')
// Once scheduled from the composer, the button reflects it and re-opening edits.
const composerScheduleId = ref<string | null>(null)
function fmtTime(hhmm: string): string {
  const [h, m] = hhmm.split(':').map(Number)
  const ap = h! < 12 ? 'am' : 'pm'
  const h12 = h! % 12 || 12
  return m ? `${h12}:${String(m).padStart(2, '0')}${ap}` : `${h12}${ap}`
}
const cadenceWord: Record<CoworkCadence, string> = { Daily: 'day', Weekly: 'week', Monthly: 'month' }
const scheduleLabel = computed(() =>
  composerScheduleId.value ? `Every ${cadenceWord[schedCadence.value]} at ${fmtTime(schedTime.value)}` : 'Schedule',
)
function scheduleFromPrompt() {
  const t = prompt.value.trim()
  if (!t) { focusPrompt(); return }
  const nextRun = schedCadence.value === 'Daily' ? `Tomorrow · ${schedTime.value}`
    : schedCadence.value === 'Weekly' ? `Next Mon · ${schedTime.value}`
    : `1st of month · ${schedTime.value}`
  const title = t.length > 52 ? t.slice(0, 50) + '…' : t
  if (composerScheduleId.value) {
    updateSchedule(composerScheduleId.value, { title, prompt: t, module: inferModule(t), cadence: schedCadence.value, time: schedTime.value, nextRun })
    toast.notify({ variant: 'success', title: 'Schedule updated' })
  } else {
    const s = addSchedule({ title, prompt: t, module: inferModule(t), cadence: schedCadence.value, time: schedTime.value, nextRun, enabled: true })
    composerScheduleId.value = s.id
    toast.notify({ variant: 'success', title: 'Task scheduled' })
  }
}

// ── Connections ──────────────────────────────────────────────────────────────
const google = useGoogleConnect()
const connecting = ref('')                          // id currently authorising
const connError = reactive<Record<string, string>>({})   // inline error per card
const connSample = reactive<Record<string, string>>({})  // live proof per card (e.g. email)

async function connectGoogle(c: CoworkConnection) {
  connError[c.id] = ''
  if (!google.isConfigured.value) {
    connError[c.id] = 'Google client ID not configured yet (NUXT_PUBLIC_GOOGLE_CLIENT_ID).'
    return
  }
  connecting.value = c.id
  try {
    const { sample } = await google.connect(c.scope!)
    setConnection(c.id, true)
    if (sample) connSample[c.id] = sample
    toast.notify({ variant: 'success', title: `${c.name} connected` })
  } catch (e: any) {
    connError[c.id] = e?.message === 'Google client ID not configured'
      ? 'Google client ID not configured yet.'
      : 'Could not connect. Please try again.'
  } finally {
    connecting.value = ''
  }
}
function disconnectConnection(c: CoworkConnection) {
  if (c.provider === 'google' && c.scope) google.disconnect(c.scope)
  delete connSample[c.id]
  setConnection(c.id, false)
  toast.notify({ variant: 'success', title: `${c.name} disconnected` })
}
function connectFake(c: CoworkConnection) {
  setConnection(c.id, true)
  toast.notify({ variant: 'success', title: `${c.name} connected` })
}
function addConnection() { toast.notify({ variant: 'info', title: 'Browse the connections marketplace — coming soon' }) }

// Leaving a section (clicking a submenu item) closes any open task workspace.
watch(() => route.path, (n, o) => { if (openTaskId.value && n !== o) backToIndex() })

// Title-bar actions (rendered by [...slug].vue) drive the page via the URL:
//   /cowork?focus=1        → focus the composer (from "+ New task" on Tasks)
//   /cowork-schedule?new=1 → open the schedule modal (from the Schedule action)
function handleQueryTriggers() {
  const q = route.query
  if (q.focus === '1') { focusPrompt(); router.replace({ path: '/cowork', query: {} }) }
  if (q.add === '1' && section.value === 'Connections') { addConnection(); router.replace({ path: '/cowork-connections', query: {} }) }
}
watch(() => route.fullPath, handleQueryTriggers)

onMounted(() => {
  const q = route.query
  if (typeof q.task === 'string' && q.task.trim() && q.run === '1') {
    assign(q.task)
    // Strip task/run from the URL; the workspace stays open via openTask.
    router.replace({ path: '/cowork', query: {} })
  }
  handleQueryTriggers()
})
onBeforeUnmount(() => { if (stepTimer) clearInterval(stepTimer) })
</script>

<template>
  <div class="cowork">
    <!-- ══ RUN WORKSPACE ══ -->
    <template v-if="openTask">
      <button class="cw-back" type="button" @click="backToIndex">
        <MpIcon name="chevrons-left" size="sm" /> All tasks
      </button>

      <!-- Working -->
      <div v-if="runState === 'working'" class="cw-run">
        <section class="cw-card cw-card--main">
          <header class="cw-run__head">
            <div>
              <h2 class="cw-run__title">{{ plan?.taskTitle ?? openTask.title }}</h2>
              <p class="cw-muted">{{ plan?.intro ?? 'Cowork is reviewing your ERP data and identifying what needs your attention.' }}</p>
            </div>
            <ErpStatusBadge status="in progress" label="Running" badge-for="additionalInformation" />
          </header>
          <MpProgress :value="progressValue" size="sm" color="positive" :class="css({ marginTop: '16px' })" />
          <p class="cw-eyebrow cw-mt-24">What Cowork is doing</p>
          <ul class="cw-steps">
            <li v-for="(s, i) in liveSteps" :key="s.title + i" class="cw-step" :class="{ 'is-done': i < activeStepIndex, 'is-active': i === activeStepIndex }">
              <span class="cw-step__dot"><MpIcon v-if="i < activeStepIndex" name="check" size="sm" /><template v-else>{{ i + 1 }}</template></span>
              <div>
                <p class="cw-step__title">{{ s.title }}</p>
                <p class="cw-muted">{{ s.detail }}</p>
              </div>
            </li>
          </ul>
        </section>
        <aside class="cw-card cw-card--side">
          <p class="cw-side__title">Sources being used</p>
          <ul class="cw-sources">
            <li v-for="s in (plan?.sources ?? [])" :key="s.name" class="cw-source"><span>{{ s.name }}</span><span class="cw-muted">{{ s.detail }}</span></li>
            <li v-if="!plan" class="cw-source"><span class="cw-muted">Gathering sources…</span><MpSpinner size="sm" /></li>
          </ul>
        </aside>
      </div>

      <!-- Completed briefing -->
      <div v-else class="cw-run cw-run--single">
        <section class="cw-card cw-card--main">
          <header class="cw-run__head">
            <div>
              <h2 class="cw-run__title">{{ plan?.taskTitle }}</h2>
              <p class="cw-muted">{{ plan?.intro }}</p>
            </div>
            <ErpStatusBadge status="completed" badge-for="additionalInformation" />
          </header>
          <p class="cw-metric">{{ plan?.metric }}</p>
          <div class="cw-actions">
            <MpButton is-rounded variant="primary" @click="toast.notify({ variant: 'success', title: 'Action items created' })">Create action items</MpButton>
            <MpButton is-rounded variant="secondary" @click="toast.notify({ variant: 'info', title: 'Shared' })">Share briefing</MpButton>
            <MpButton is-rounded variant="ghost" @click="rerun">Run again</MpButton>
          </div>

          <p class="cw-eyebrow cw-mt-24">Executive summary</p>
          <ul class="cw-summary">
            <li v-for="(s, i) in (plan?.summary ?? [])" :key="s.title" class="cw-summary__row">
              <div>
                <p class="cw-summary__title">{{ i + 1 }}. {{ s.title }}</p>
                <p class="cw-muted">{{ s.detail }}</p>
              </div>
              <ErpStatusBadge :status="s.priority.toLowerCase()" :label="s.priority" />
            </li>
          </ul>

          <template v-if="plan?.findings?.length">
            <p class="cw-eyebrow cw-mt-24">Key findings</p>
            <ul class="cw-findings">
              <li v-for="f in plan.findings" :key="f.title" class="cw-finding">
                <p class="cw-summary__title">{{ f.title }}</p><p class="cw-muted">{{ f.detail }}</p>
              </li>
            </ul>
          </template>
        </section>

        <aside class="cw-card cw-card--side">
          <p class="cw-side__title">Cowork also prepared</p>
          <ul class="cw-prepared">
            <li v-for="a in (plan?.alsoPrepared ?? [])" :key="a.title" class="cw-prepared__item">
              <MpIcon name="document" size="md" />
              <div><p class="cw-summary__title">{{ a.title }}</p><p class="cw-muted">{{ a.detail }}</p></div>
            </li>
          </ul>
          <p class="cw-side__title cw-mt-24">Sources used</p>
          <ul class="cw-sources">
            <li v-for="s in (plan?.sources ?? [])" :key="s.name" class="cw-source"><span>{{ s.name }}</span><span class="cw-muted">{{ s.detail }}</span></li>
          </ul>
        </aside>
      </div>
    </template>

    <!-- ══ INDEX (section chosen by the page-tab bar rendered outside the stage) ══ -->
    <template v-else>
        <!-- ── Overview (Figma) ── -->
        <section v-if="section === 'Overview'" class="cw-ov">
          <div class="cw-ov__inner">
            <h1 class="cw-hero">What can I do for you?</h1>

            <!-- Composer -->
            <div class="cw-composer2">
              <textarea
                ref="promptEl"
                v-model="prompt"
                class="cw-composer2__input"
                rows="3"
                placeholder="Assign a task to Cowork — it works across HR, Sales, CRM, WMS, finance & production…"
                @keydown.enter.exact.prevent="assign(prompt)"
              />
              <div class="cw-composer2__foot">
                <div class="cw-composer2__left">
                  <!-- Output popover: what Cowork should produce for this task -->
                  <MpPopover id="cw-output" placement="bottom-start">
                    <MpPopoverTrigger>
                      <button class="cw-foot-btn" type="button"><MpIcon name="doc" size="sm" /> Output<span v-if="activeOutputCount"> ({{ activeOutputCount }})</span></button>
                    </MpPopoverTrigger>
                    <MpPopoverContent :class="css({ minWidth: '260px' })">
                      <div class="cw-src">
                        <p class="cw-src__head">Output</p>
                        <p class="cw-src__hint">Choose what Cowork should produce.</p>
                        <div v-for="o in OUTPUTS" :key="o.id" class="cw-src__row">
                          <span class="cw-src__name">{{ o.name }}</span>
                          <MpToggle :is-checked="isOutputOn(o.id)" :aria-label="`Toggle ${o.name}`" @update:is-checked="(v: boolean) => toggleOutput(o.id, v)" />
                        </div>
                      </div>
                    </MpPopoverContent>
                  </MpPopover>

                  <!-- Sources popover: connected sources with on/off toggles -->
                  <MpPopover id="cw-source" placement="bottom-start">
                    <MpPopoverTrigger>
                      <button class="cw-foot-btn" type="button"><MpIcon name="add" size="sm" /> Sources<span v-if="activeSourceCount"> ({{ activeSourceCount }})</span></button>
                    </MpPopoverTrigger>
                    <MpPopoverContent :class="css({ minWidth: '260px' })">
                      <div class="cw-src">
                        <p class="cw-src__head">Sources</p>
                        <p class="cw-src__hint">Choose which connected data Cowork may use.</p>
                        <div v-for="s in sources" :key="s.id" class="cw-src__row">
                          <span class="cw-src__name">{{ s.name }}</span>
                          <MpToggle :is-checked="isSourceOn(s.id)" :aria-label="`Toggle ${s.name}`" @update:is-checked="(v: boolean) => toggleSource(s.id, v)" />
                        </div>
                      </div>
                    </MpPopoverContent>
                  </MpPopover>

                  <!-- Schedule popover: cadence + time (the task is the prompt above) -->
                  <MpPopover id="cw-schedule" is-close-on-select placement="bottom-start">
                    <MpPopoverTrigger>
                      <button class="cw-foot-btn" type="button" :class="{ 'is-set': composerScheduleId }"><MpIcon name="time" size="sm" /> {{ scheduleLabel }}</button>
                    </MpPopoverTrigger>
                    <MpPopoverContent :class="css({ minWidth: '260px' })">
                      <div class="cw-src">
                        <p class="cw-src__head">Schedule this task</p>
                        <p class="cw-src__hint">Cowork runs your prompt automatically.</p>
                        <p class="cw-sched-label">Cadence</p>
                        <div class="cw-seg">
                          <button v-for="c in ['Daily','Weekly','Monthly']" :key="c" type="button" class="cw-seg__btn" :class="{ 'is-active': schedCadence === c }" @click="schedCadence = c as CoworkCadence">{{ c }}</button>
                        </div>
                        <p class="cw-sched-label">Time</p>
                        <div class="cw-seg">
                          <button v-for="t in ['07:00','08:00','09:00','18:00']" :key="t" type="button" class="cw-seg__btn" :class="{ 'is-active': schedTime === t }" @click="schedTime = t">{{ t }}</button>
                        </div>
                      </div>
                      <MpPopoverList>
                        <MpPopoverListItem @click="scheduleFromPrompt">{{ composerScheduleId ? 'Update schedule' : `Schedule ${schedCadence.toLowerCase()} at ${schedTime}` }}</MpPopoverListItem>
                      </MpPopoverList>
                    </MpPopoverContent>
                  </MpPopover>
                </div>

                <!-- Model picker -->
                <MpPopover id="cw-model" is-close-on-select placement="bottom-end">
                  <MpPopoverTrigger>
                    <button class="cw-model-btn" type="button">
                      <GeminiMark :size="16" />
                      {{ modelLabel }}
                      <MpIcon name="caret-down" size="sm" />
                    </button>
                  </MpPopoverTrigger>
                  <MpPopoverContent :class="css({ minWidth: '200px' })">
                    <MpPopoverList>
                      <MpPopoverListItem v-for="m in MODELS" :key="m.id" :is-active="m.id === model" @click="model = m.id">{{ m.label }}</MpPopoverListItem>
                    </MpPopoverList>
                  </MpPopoverContent>
                </MpPopover>
              </div>
            </div>

            <!-- Suggested for you -->
            <div class="cw-suggest">
              <h3 class="cw-h3">Suggested for you</h3>
              <p class="cw-muted">Ready-made tasks across your ERP — run one to see Cowork work.</p>
              <template v-for="g in suggestedGroups" :key="g.module">
                <p class="cw-module-label">{{ g.module }}</p>
                <div class="cw-suggest-grid">
                  <button v-for="c in g.items" :key="c.title" class="cw-suggest-item" type="button" @click="assign(c.prompt, c.title, c.module)">
                    <span class="cw-suggest-icon">
                      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M13 2 4.5 13.5H11l-1 8.5 8.5-11.5H12l1-8.5Z" fill="currentColor"/></svg>
                    </span>
                    <span class="cw-suggest-text">
                      <span class="cw-suggest-title">{{ c.title }}</span>
                      <span class="cw-muted">{{ c.desc }}</span>
                      <span v-if="c.usedBy?.length" class="cw-suggest-used">
                        <span class="cw-avatars">
                          <img v-for="e in usedAvatars(c.usedBy)" :key="e!.id" :src="e!.photo" :alt="e!.fullName" class="cw-avatar" :title="e!.fullName">
                        </span>
                        Used {{ c.usedBy.length }} {{ c.usedBy.length === 1 ? 'time' : 'times' }}
                      </span>
                      <span v-if="!hasRun(c)" class="cw-suggest-run">Run task <MpIcon name="arrows-right" size="sm" /></span>
                    </span>
                  </button>
                </div>
              </template>
            </div>
          </div>
        </section>

        <!-- ── Tasks ── -->
        <section v-else-if="section === 'Tasks'">
          <!-- Filter bar: status (left) + search (right) -->
          <div class="cw-filter">
            <div class="cw-filter__left">
              <MpPopover id="cw-task-status" is-close-on-select>
                <MpPopoverTrigger>
                  <MpSelect id="cw-task-status-sel" placeholder="Status" :model-value="taskStatus" is-clearable :class="css({ width: '160px' })" @mousedown.prevent @clear="taskStatus = ''">
                    <option v-if="taskStatus" :value="taskStatus">{{ taskStatusLabel }}</option>
                  </MpSelect>
                </MpPopoverTrigger>
                <MpPopoverContent :class="css({ minWidth: '160px', width: 'max-content' })">
                  <MpPopoverList>
                    <MpPopoverListItem v-for="o in taskStatusOptions" :key="o.value" :is-active="o.value === taskStatus" @click="taskStatus = o.value">{{ o.label }}</MpPopoverListItem>
                  </MpPopoverList>
                </MpPopoverContent>
              </MpPopover>
            </div>
            <div class="cw-filter__right">
              <div class="cw-search">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M22 22L20 20M21 11.5C21 16.747 16.747 21 11.5 21C6.253 21 2 16.747 2 11.5C2 6.253 6.253 2 11.5 2C16.747 2 21 6.253 21 11.5Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>
                <input v-model="taskSearch" class="cw-search__input" type="text" placeholder="Search...">
                <button v-if="taskSearch" class="cw-search__clear" type="button" aria-label="Clear search" @click="taskSearch = ''">
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M18 6L6 18M6 6l12 12" stroke="currentColor" stroke-width="1.75" stroke-linecap="round"/></svg>
                </button>
              </div>
            </div>
          </div>

          <div class="cw-table-wrap">
            <table class="cw-table">
              <thead>
                <tr><th>Task</th><th>Module</th><th>Status</th><th>Created</th><th>Result</th><th class="cw-th-actions" /></tr>
              </thead>
              <!-- First-load skeleton -->
              <tbody v-if="loading">
                <tr v-for="n in 5" :key="`sk-${n}`">
                  <td><MpSkeleton class="cw-skeleton" width="200px" height="14px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="72px" height="18px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="80px" height="18px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="120px" height="14px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="64px" height="14px" rounded="sm" duration="0s" /></td>
                  <td class="cw-td-actions"><MpSkeleton class="cw-skeleton" width="20px" height="20px" rounded="sm" duration="0s" /></td>
                </tr>
              </tbody>
              <tbody v-else>
                <tr v-for="t in taskRows" :key="t.id">
                  <td>
                    <span class="cw-cell-link" @click="openTaskDetail(t)">{{ t.title }}</span>
                    <span class="cw-cell-sub">{{ t.id }}</span>
                  </td>
                  <td><MpBadge for="additionalInformation" type="announcement" size="sm">{{ t.module }}</MpBadge></td>
                  <td><ErpStatusBadge v-bind="statusProps(t.status)" /></td>
                  <td>{{ formatDateTime(t.createdAt) }}</td>
                  <td class="cw-muted">{{ t.metric ?? '—' }}</td>
                  <td class="cw-td-actions" @click.stop>
                    <MpPopover :id="`cw-task-${t.id}`" is-close-on-select use-portal :is-keep-alive="false" placement="bottom-end">
                      <MpPopoverTrigger>
                        <button class="cw-kebab" type="button" aria-label="Actions"><MpIcon name="menu-kebab" size="md" /></button>
                      </MpPopoverTrigger>
                      <MpPopoverContent :class="css({ minWidth: '160px' })">
                        <MpPopoverList>
                          <MpPopoverListItem @click="openTaskDetail(t)">Open</MpPopoverListItem>
                          <MpPopoverListItem @click="removeTask(t.id)">Delete</MpPopoverListItem>
                        </MpPopoverList>
                      </MpPopoverContent>
                    </MpPopover>
                  </td>
                </tr>
                <tr v-if="!taskRows.length"><td colspan="6" class="cw-empty">No tasks match your filters.</td></tr>
              </tbody>
            </table>
          </div>
          <ErpPagination :current-page="taskPage" :per-page="taskPerPage" :total="taskTotal" @page-change="taskSetPage" @per-page-change="taskSetPerPage" />
        </section>

        <!-- ── Schedule ── -->
        <section v-else-if="section === 'Schedule'">
          <div class="cw-table-wrap">
            <table class="cw-table">
              <thead>
                <tr><th>Task</th><th>Module</th><th>Cadence</th><th>Next run</th><th>Active</th><th class="cw-th-actions" /></tr>
              </thead>
              <!-- First-load skeleton -->
              <tbody v-if="loading">
                <tr v-for="n in 5" :key="`sk-${n}`">
                  <td><MpSkeleton class="cw-skeleton" width="200px" height="14px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="72px" height="18px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="110px" height="14px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="120px" height="14px" rounded="sm" duration="0s" /></td>
                  <td><MpSkeleton class="cw-skeleton" width="36px" height="20px" rounded="sm" duration="0s" /></td>
                  <td class="cw-td-actions"><MpSkeleton class="cw-skeleton" width="20px" height="20px" rounded="sm" duration="0s" /></td>
                </tr>
              </tbody>
              <tbody v-else>
                <tr v-for="s in schedRows" :key="s.id">
                  <td><span class="cw-list-row__title">{{ s.title }}</span></td>
                  <td><MpBadge for="additionalInformation" type="announcement" size="sm">{{ s.module }}</MpBadge></td>
                  <td>{{ s.cadence }} · {{ s.time }}</td>
                  <td>{{ s.nextRun }}</td>
                  <td><MpToggle :is-checked="s.enabled" :aria-label="`Toggle ${s.title}`" @update:is-checked="(v: boolean) => toggleSchedule(s.id, v)" /></td>
                  <td class="cw-td-actions">
                    <button class="cw-kebab" type="button" aria-label="Delete schedule" @click="deleteSchedule(s.id)"><MpIcon name="delete" size="md" /></button>
                  </td>
                </tr>
                <tr v-if="!schedRows.length"><td colspan="6" class="cw-empty">No scheduled tasks.</td></tr>
              </tbody>
            </table>
          </div>
          <ErpPagination :current-page="schedPage" :per-page="schedPerPage" :total="schedTotal" @page-change="schedSetPage" @per-page-change="schedSetPerPage" />
        </section>

        <!-- ── Connections ── -->
        <section v-else-if="section === 'Connections'">
          <p class="cw-muted cw-conn-lead">Cowork works over the products and data sources you connect.</p>
          <div class="cw-grid">
            <div v-for="c in coworkConnections" :key="c.id" class="cw-card cw-conn-card">
              <div class="cw-conn-card__top">
                <div class="cw-conn-logo">{{ c.name.slice(0, 2).toUpperCase() }}</div>
                <div class="cw-conn-badges">
                  <MpBadge v-if="c.provider === 'google'" for="additionalInformation" type="information" size="sm">Live</MpBadge>
                  <ErpStatusBadge v-if="c.connected" status="active" label="Connected" />
                </div>
              </div>
              <h4 class="cw-card__title">{{ c.name }}</h4>
              <p class="cw-muted">{{ c.category }} · {{ c.detail }}</p>
              <p v-if="connSample[c.id]" class="cw-conn-sample"><MpIcon name="check" size="sm" /> {{ connSample[c.id] }}</p>
              <p v-if="connError[c.id]" class="cw-form-error">{{ connError[c.id] }}</p>
              <div class="cw-conn-card__foot">
                <MpButton v-if="c.connected" is-rounded variant="ghost" size="sm" @click="disconnectConnection(c)">Disconnect</MpButton>
                <MpButton v-else-if="c.provider === 'google'" is-rounded variant="secondary" size="sm" :is-loading="connecting === c.id" @click="connectGoogle(c)">Connect</MpButton>
                <MpButton v-else is-rounded variant="secondary" size="sm" @click="connectFake(c)">Connect</MpButton>
              </div>
            </div>
          </div>
        </section>
    </template>
  </div>
</template>

<style scoped>
.cowork { display: flex; flex-direction: column; }

/* Enterprise card — border 1px, no drop-shadow (surface rule). */
.cw-card { border: 1px solid var(--mp-border-default, #e3e7e9); border-radius: var(--mp-radii-xl, 12px); background: var(--mp-background-neutral, #fff); padding: var(--mp-spacing-5, 20px); }
.cw-muted { margin: 0; color: var(--mp-text-secondary, #3a4749); font-size: var(--mp-font-sizes-sm, 12px); line-height: var(--mp-line-heights-sm, 16px); }
.cw-eyebrow { margin: 0 0 var(--mp-spacing-3); font-size: var(--mp-font-sizes-sm); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-h3 { margin: 0; font-size: var(--mp-font-sizes-lg, 16px); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-mt-24 { margin-top: var(--mp-spacing-6, 24px); }

/* Composer */
.cw-composer { margin-top: 0; }

/* ── Overview (Figma) — centered composer + module-grouped suggestions ── */
.cw-ov__inner { max-width: 880px; margin: 0 auto; width: 100%; }
.cw-hero { text-align: center; margin: var(--mp-spacing-2) 0 var(--mp-spacing-6); font-size: var(--mp-font-sizes-2xl, 24px); line-height: var(--mp-line-heights-xl, 32px); font-weight: var(--mp-font-weights-semi-bold); letter-spacing: var(--mp-letter-spacings-tight, -0.2px); color: var(--mp-text-default); }

/* Gray-subtle tray (20px), holding a fully-rounded white input card on top and
   the footer row below — so the input has rounded corners top AND bottom. */
.cw-composer2 { border: 1px solid var(--mp-border-default, #e3e7e9); border-radius: 20px; background: var(--mp-background-neutral-subtle, #f8f9f9); padding: var(--mp-spacing-1, 4px); }
.cw-composer2__input { display: block; width: 100%; border: 1px solid var(--mp-border-default, #e3e7e9); border-radius: 20px; outline: none; resize: none; font-family: inherit; font-size: var(--mp-font-sizes-md, 14px); line-height: var(--mp-line-heights-md, 20px); color: var(--mp-text-default); padding: var(--mp-spacing-4); background: var(--mp-background-neutral, #fff); min-height: 76px; }
.cw-composer2__input::placeholder { color: var(--mp-text-placeholder, #6e7a7c); }
.cw-composer2__input:focus { border-color: var(--mp-border-bold, #8c9596); }
/* Symmetric gap around the button row: the 4px tray padding below is topped up by
   the footer's 4px bottom so buttons→edge equals buttons→input (8px). */
.cw-composer2__foot { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); padding: var(--mp-spacing-2) var(--mp-spacing-2) var(--mp-spacing-1); background: var(--mp-background-neutral-subtle, #f8f9f9); }
.cw-composer2__left { display: flex; align-items: center; gap: var(--mp-spacing-1); }
.cw-foot-btn { display: inline-flex; align-items: center; gap: 4px; background: none; border: none; cursor: pointer; font-family: inherit; font-size: var(--mp-font-sizes-md); color: var(--mp-text-secondary); padding: var(--mp-spacing-1\.5, 6px) var(--mp-spacing-3); border-radius: var(--mp-radii-full, 999px); }
.cw-foot-btn:hover { background: var(--mp-background-neutral-pressed, #ebf0f1); color: var(--mp-text-default); }
.cw-foot-btn.is-set { color: var(--mp-text-selected, #0f6d4d); }
.cw-foot-btn.is-set :deep(svg), .cw-foot-btn.is-set :deep(path) { color: var(--mp-text-selected, #0f6d4d); }
.cw-foot-btn :deep(svg) { color: var(--mp-icon-default, #536062); }
.cw-model-btn { display: inline-flex; align-items: center; gap: var(--mp-spacing-2); background: none; border: none; cursor: pointer; font-family: inherit; font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-regular); color: var(--mp-text-default); padding: var(--mp-spacing-1\.5, 6px) var(--mp-spacing-2); border-radius: var(--mp-radii-md, 8px); }
.cw-model-btn:hover { background: var(--mp-background-neutral-pressed, #ebf0f1); }
.cw-model-btn > svg:first-child { flex-shrink: 0; }

.cw-src { padding: var(--mp-spacing-2); }
.cw-src__head { margin: 0; font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-src__hint { margin: 2px 0 var(--mp-spacing-2); font-size: var(--mp-font-sizes-sm); color: var(--mp-text-secondary); }
.cw-src__row { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); padding: var(--mp-spacing-1\.5, 6px) var(--mp-spacing-1); }
.cw-src__name { font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); }
.cw-sched-label { margin: var(--mp-spacing-3) 0 var(--mp-spacing-1); font-size: var(--mp-font-sizes-sm); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-secondary); }
.cw-seg { display: flex; gap: var(--mp-spacing-1); flex-wrap: wrap; }
.cw-seg__btn { flex: 1 1 auto; min-width: 52px; padding: 6px 10px; border: 1px solid var(--mp-border-default, #e3e7e9); background: var(--mp-background-neutral, #fff); border-radius: var(--mp-radii-full, 999px); font-size: var(--mp-font-sizes-sm); color: var(--mp-text-default); cursor: pointer; font-family: inherit; }
.cw-seg__btn.is-active { border-color: var(--mp-text-selected, #0f6d4d); background: var(--mp-background-brand-selected, #d6f4e9); color: var(--mp-text-selected, #0f6d4d); font-weight: var(--mp-font-weights-semi-bold); }

.cw-suggest { margin-top: var(--mp-spacing-8, 32px); }
.cw-suggest .cw-h3 { font-size: var(--mp-font-sizes-xl, 20px); line-height: var(--mp-line-heights-xl, 28px); }
.cw-suggest > .cw-muted { margin-top: 2px; }
.cw-module-label { margin: var(--mp-spacing-10, 40px) 0 var(--mp-spacing-3); font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
/* First module label sits right under the "Suggested for you" caption. */
.cw-suggest > .cw-muted + .cw-module-label { margin-top: var(--mp-spacing-6, 24px); }
.cw-suggest-grid { display: grid; grid-template-columns: 1fr 1fr; gap: var(--mp-spacing-3) var(--mp-spacing-10, 40px); }
.cw-suggest-item { display: flex; gap: var(--mp-spacing-3); align-items: flex-start; background: none; border: none; padding: var(--mp-spacing-2) 0; cursor: pointer; text-align: left; font-family: inherit; }
.cw-suggest-icon { flex: 0 0 auto; width: 40px; height: 40px; border-radius: var(--mp-radii-full, 999px); background: #F8F8F8; border: 1px solid var(--mp-border-bold, #8c9596); box-shadow: 0 1px 2px rgba(16, 24, 40, 0.08); display: flex; align-items: center; justify-content: center; color: var(--mp-text-default); }
.cw-suggest-text { display: flex; flex-direction: column; gap: 2px; min-width: 0; }
.cw-suggest-title { font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-suggest-run { display: inline-flex; align-items: center; gap: 4px; margin-top: var(--mp-spacing-2); font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-regular); color: var(--mp-text-link, #165082); }
.cw-suggest-used { display: inline-flex; align-items: center; gap: var(--mp-spacing-2); margin-top: var(--mp-spacing-2); font-size: var(--mp-font-sizes-md); color: var(--mp-text-secondary); }
.cw-avatars { display: inline-flex; }
.cw-avatar { width: 32px; height: 32px; border-radius: var(--mp-radii-full, 999px); object-fit: cover; border: 2px solid var(--mp-background-neutral, #fff); background: var(--mp-background-neutral-subtle, #f8f9f9); }
.cw-avatar + .cw-avatar { margin-left: -12px; }
.cw-suggest-item:hover .cw-suggest-run { text-decoration: underline; text-underline-offset: 2px; }
@media (max-width: 900px) { .cw-suggest-grid { grid-template-columns: 1fr; } }
.cw-composer__foot { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); margin-top: var(--mp-spacing-3); }
.cw-conn-chips { display: flex; flex-wrap: wrap; gap: var(--mp-spacing-2); }
.cw-conn-chip { display: inline-flex; align-items: center; gap: 4px; font-size: var(--mp-font-sizes-sm); color: var(--mp-text-secondary); background: var(--mp-background-neutral-subtle, #f8f9f9); border-radius: var(--mp-radii-full, 999px); padding: 3px 10px; }
.cw-conn-chip :deep(svg) { color: var(--mp-text-success, #186f4a); }

/* Section head */
.cw-section-head { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); margin: var(--mp-spacing-8) 0 var(--mp-spacing-4); }

/* Card grid */
.cw-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: var(--mp-spacing-4); }
.cw-card--click { text-align: left; cursor: pointer; display: flex; flex-direction: column; gap: var(--mp-spacing-2); font-family: inherit; transition: border-color 100ms; }
.cw-card--click:hover { border-color: var(--mp-border-bold, #8c9596); }
.cw-card__title { margin: 4px 0 0; font-size: var(--mp-font-sizes-md, 14px); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-card__cta { margin-top: auto; display: inline-flex; align-items: center; gap: 4px; font-size: var(--mp-font-sizes-sm); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-link, #165082); padding-top: var(--mp-spacing-2); }

/* Recent list */
.cw-list { display: flex; flex-direction: column; border: 1px solid var(--mp-border-default); border-radius: var(--mp-radii-xl, 12px); overflow: hidden; }
.cw-list-row { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-3); padding: var(--mp-spacing-3) var(--mp-spacing-4); background: var(--mp-background-neutral, #fff); border: none; border-top: 1px solid var(--mp-border-default); cursor: pointer; font-family: inherit; text-align: left; }
.cw-list-row:first-child { border-top: none; }
.cw-list-row:hover { background: var(--mp-background-neutral-subtle, #f8f9f9); }
.cw-list-row__main { display: flex; align-items: center; gap: var(--mp-spacing-3); min-width: 0; }
.cw-list-row__title { font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); font-weight: var(--mp-font-weights-regular); }
.cw-list-row__meta { display: flex; align-items: center; gap: var(--mp-spacing-4); flex-shrink: 0; }
.cw-empty { padding: var(--mp-spacing-6); text-align: center; color: var(--mp-text-secondary); font-size: var(--mp-font-sizes-sm); margin: 0; }

/* Table (ERP convention: no outer border, header fill, row bottom-border) */
/* Filter bar (Tasks): status left, search right — mirrors the ERP index filter bar. */
.cw-filter { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-4); margin-bottom: var(--mp-spacing-4); }
.cw-filter__left { display: flex; align-items: center; gap: var(--mp-spacing-3); }
.cw-filter__right { display: flex; align-items: center; gap: var(--mp-spacing-3); }
.cw-search { display: flex; align-items: center; gap: var(--mp-spacing-2); width: 248px; padding: var(--mp-spacing-2) var(--mp-spacing-3); background: var(--mp-background-neutral, #fff); border: 1px solid var(--mp-border-default); border-radius: var(--mp-radii-full, 999px); color: var(--mp-text-subtle); }
.cw-search__input { flex: 1; border: none; outline: none; background: transparent; font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); min-width: 0; }
.cw-search__input::placeholder { color: var(--mp-text-placeholder); }
.cw-search__clear { display: inline-flex; align-items: center; justify-content: center; flex-shrink: 0; width: 18px; height: 18px; padding: 0; border: none; background: none; cursor: pointer; color: var(--mp-text-secondary); border-radius: 999px; }
.cw-search__clear:hover { background: var(--mp-background-neutral-hovered); }

/* First-load skeleton — solid, no shimmer/animation (ERP guideline). */
.cw-skeleton { background-image: none !important; background-color: var(--mp-border-default) !important; animation: none !important; }

.cw-table-wrap { overflow-x: auto; }
.cw-table { width: 100%; border-collapse: collapse; }
.cw-table thead th { text-align: left; padding: var(--mp-spacing-2) var(--mp-spacing-3); background: var(--mp-background-neutral-subtle, #f8f9f9); font-size: var(--mp-font-sizes-sm); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-secondary); white-space: nowrap; }
.cw-table tbody td { padding: var(--mp-spacing-2) var(--mp-spacing-3); border-bottom: 1px solid var(--mp-border-default); font-size: var(--mp-font-sizes-md); color: var(--mp-text-default); vertical-align: middle; }
.cw-th-actions, .cw-td-actions { width: 52px; text-align: right; }
.cw-cell-link { color: var(--mp-text-link, #165082); cursor: pointer; font-weight: var(--mp-font-weights-regular); }
.cw-cell-link:hover { text-decoration: underline; }
.cw-cell-sub { display: block; font-size: var(--mp-font-sizes-sm); color: var(--mp-text-secondary); }
.cw-kebab { display: inline-flex; align-items: center; justify-content: center; width: 32px; height: 32px; border: none; background: none; border-radius: var(--mp-radii-md); color: var(--mp-text-secondary); cursor: pointer; }
.cw-kebab:hover { background: var(--mp-background-neutral-subtle); color: var(--mp-text-default); }

/* Connections */
.cw-conn-card { display: flex; flex-direction: column; gap: var(--mp-spacing-2); }
.cw-conn-card__top { display: flex; align-items: center; justify-content: space-between; }
.cw-conn-badges { display: inline-flex; align-items: center; gap: var(--mp-spacing-2); }
.cw-conn-sample { display: inline-flex; align-items: center; gap: 4px; margin: 0; font-size: var(--mp-font-sizes-sm); color: var(--mp-text-success, #186f4a); }
.cw-conn-sample :deep(svg) { color: var(--mp-text-success, #186f4a); }
.cw-conn-logo { width: 40px; height: 40px; border-radius: var(--mp-radii-md, 8px); background: var(--mp-background-neutral-subtle, #f1f3f4); display: flex; align-items: center; justify-content: center; font-size: 13px; font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-secondary); }
.cw-conn-card__foot { margin-top: var(--mp-spacing-3); }

/* Form row */
.cw-form-row { display: grid; grid-template-columns: 1fr 1fr; gap: var(--mp-spacing-4); }
.cw-form-error { margin: var(--mp-spacing-2) 0 0; color: var(--mp-text-danger, #a8352d); font-size: var(--mp-font-sizes-sm); }

/* Run workspace — the left (task summary) column is not boxed; only the side rail is. */
.cw-run .cw-card--main, .cw-run--single .cw-card--main { border: none; background: none; padding: 0; }
.cw-conn-lead { margin-bottom: var(--mp-spacing-4); }
.cw-back { display: inline-flex; align-items: center; gap: 4px; background: none; border: none; cursor: pointer; color: var(--mp-text-secondary); font-size: var(--mp-font-sizes-md); font-family: inherit; padding: 0; margin-bottom: var(--mp-spacing-4); }
.cw-back:hover { color: var(--mp-text-default); }
.cw-run { display: grid; grid-template-columns: minmax(0, 1fr) 320px; gap: var(--mp-spacing-4); align-items: start; }
.cw-run--single { grid-template-columns: minmax(0, 1fr) 320px; }
.cw-run__head { display: flex; align-items: flex-start; justify-content: space-between; gap: var(--mp-spacing-4); }
.cw-run__title { margin: 0 0 4px; font-size: var(--mp-font-sizes-xl, 20px); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-metric { margin: var(--mp-spacing-4) 0 0; font-size: var(--mp-font-sizes-2xl, 24px); font-weight: var(--mp-font-weights-semi-bold); letter-spacing: -0.2px; color: var(--mp-text-default); }
.cw-actions { display: flex; flex-wrap: wrap; gap: var(--mp-spacing-2); margin-top: var(--mp-spacing-4); }
.cw-steps { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: var(--mp-spacing-3); }
.cw-step { display: flex; gap: var(--mp-spacing-3); align-items: flex-start; opacity: .5; transition: opacity 250ms; }
.cw-step.is-done, .cw-step.is-active { opacity: 1; }
.cw-step__dot { flex: 0 0 auto; width: 24px; height: 24px; border-radius: 999px; background: var(--mp-background-neutral-subtle, #eef0f3); display: flex; align-items: center; justify-content: center; font-size: 12px; color: var(--mp-text-secondary); }
.cw-step.is-done .cw-step__dot { background: var(--mp-background-success-subtle, #e7f4ee); color: var(--mp-text-success, #186f4a); }
.cw-step.is-active .cw-step__dot { background: var(--mp-background-information-subtle, #dbe7f4); color: var(--mp-text-link, #165082); }
.cw-step__title { margin: 0; font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-side__title { margin: 0 0 var(--mp-spacing-3); font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-sources, .cw-prepared, .cw-summary, .cw-findings { list-style: none; margin: 0; padding: 0; }
.cw-source { display: flex; align-items: center; justify-content: space-between; gap: var(--mp-spacing-2); padding: var(--mp-spacing-2) 0; border-bottom: 1px solid var(--mp-border-default); font-size: var(--mp-font-sizes-sm); }
.cw-source:last-child { border-bottom: none; }
.cw-prepared__item { display: flex; gap: var(--mp-spacing-3); padding: var(--mp-spacing-3) 0; border-bottom: 1px solid var(--mp-border-default); }
.cw-prepared__item:last-child { border-bottom: none; }
.cw-prepared__item :deep(svg) { color: var(--mp-text-secondary); flex-shrink: 0; }
.cw-summary__row { display: flex; align-items: flex-start; justify-content: space-between; gap: var(--mp-spacing-4); padding: var(--mp-spacing-3) 0; border-bottom: 1px solid var(--mp-border-default); }
.cw-summary__row:last-child { border-bottom: none; }
.cw-summary__title { margin: 0; font-size: var(--mp-font-sizes-md); font-weight: var(--mp-font-weights-semi-bold); color: var(--mp-text-default); }
.cw-finding { padding: var(--mp-spacing-3) 0; border-bottom: 1px solid var(--mp-border-default); }
.cw-finding:last-child { border-bottom: none; }

@media (max-width: 900px) {
  .cw-grid { grid-template-columns: 1fr; }
  .cw-run, .cw-run--single { grid-template-columns: 1fr; }
  .cw-form-row { grid-template-columns: 1fr; }
}
</style>
